### ISSUE TITLE
As a Mac user, I would like to know that it is safe to continue when my Mac warns me about

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#13984]
https://github.com/TheOdinProject/curriculum/blob/master/web_development_101/installations/text_editors.md

A user has reported that after installing VSCode, they were warned about it not being trusted. The directions should be updated to let the users know this is expected and VSCode can be trusted.

**Comment by wuworkshop** [comment]
Would also be good to link to this Common question about macOS Catalina:
https://code.visualstudio.com/docs/setup/mac#_unable-to-open-on-macos-catalina

**Comment by olav35** [comment]
If you find something you can improve you should preferably fix it yourself rather than asking for someone else to do it. The way you fix an issue in a repository that you do not control yourself is by creating a pull request that the owners can merge.

TOP has a [video](https://www.youtube.com/watch?v=V74l_zS1x8E) about creating pull requests. iirc this video is specifically for adding your solution to a project / assignment, but the process is mostly the same.

**Comment by zachmmeyer** [comment]
I created a pull request regarding this issue
https://github.com/TheOdinProject/curriculum/pull/14972
