### ISSUE TITLE
WebDev101: Assign: Git Workflow/ Add Another File instruct out of order

### ISSUE THREAD

**Issue by sicou2** [TheOdinProject/curriculum#15850]
In the [Assignment](https://www.theodinproject.com/courses/web-development-101/lessons/practicing-git-basics?ref=lnav#assignment) for this section under "Use the Git Workflow" the student creates a `README.md` (step 1), stages that file (step 3) and commits it (step 4). 

However, in the next section "Add Another File", the student first creates `hello_world.txt` and then modifies `README.md`. In step 3 the instruction text says "Back in your terminal, type git status, and notice that README.md is no longer staged".

This might be confusing to a student still learning the steps to Git. The problem seems to be that `README.md` would not be staged regardless if the student followed step 2 to add text to `README.md`. This is because it was committed in the previous step and the student was working tree clean. 

If this is intentional then please close this issue. Otherwise, maybe one of a couple of corrections should be made. 

1) Do not commit in step 4 of "Use the Git Workflow"
2) Have the student:
    a. make a change to `README.md` 
    b. stage `README.md`
    c. have them make a second change to `README.md`
    d. then have them move on to current step 3 and "notice that `README.md` is no longer staged".
EDIT TO ADD: 3) clarify what the student see in this step noting the modified file as opposed to an untracked or staged file. 

<s>It feels that the second option is more inline with that it seems the purpose of the lesson is.</s>
EDIT: Option three seems to fulfill the spirit of the lesson without needing to make any structural changes to the lesson and would provide exactly what the student should be seeing at that step.

**Comment by anampartho** [comment]
> The problem seems to be that README.md would not be staged regardless if the student followed step 2 to add text to README.md.

This is correct. After the first commit, the `README.md` file will be moved from **Staged** to the **Commited** state. So if we run `git status` now, there won't be any modified file in the working directory, because every **modification** has already been **staged** and then **committed**. So we don't see any staged file as well. This will make the reader think about why the files aren't staying **staged** after the **commit**. They'll learn about the **[The Three States](https://git-scm.com/book/en/v2/Getting-Started-What-is-Git%3F#_the_three_states)
** of git through this as well. Which are **Modified**, **Staged**, **Committed**.

ps: This is my first ever comment on github, hope this doesn't break any rules and makes sense. Thank you!

**Comment by anampartho** [comment]
> The problem seems to be that README.md would not be staged regardless if the student followed step 2 to add text to README.md.

This is correct. After the first commit, the `README.md` file will be moved from **Staged** to the **Commited** state. So if we run `git status` now, there won't be any modified file in the working directory, because every **modification** has already been **staged** and then **committed**. So we don't see any staged file as well. This will make the reader think about why the files aren't staying **staged** after the **commit**. They'll learn about the **[The Three States](https://git-scm.com/book/en/v2/Getting-Started-What-is-Git%3F#_the_three_states)
** of git through this as well. Which are **Modified**, **Staged**, **Committed**.

ps: This is my first ever comment on github, hope this doesn't break any rules and makes sense. Thank you!

**Comment by sicou2** [comment]
I agree with everything you said! 👍  

I think that the wording has the potential to be a little confusing for a new student, since the order is currently:

1. make `README.md` / git status (`README.md` untracked file)
2. git add `README.md` / git status (staged file)
3. git commit / git status (no files, tree clean, also first time showing that `README.md` is committed and not staged) / git log
4. make `hello_world.txt` / git status (`hello_world.txt` untracked, and second time showing `README.md` is committed and not staged)
5. open and edit `README.md` / git status (`hello_world.txt` untracked, and `README.md` is modified)

So the student sees (for `README.md`) > untracked > staged > committed > committed > modified. 
That is why I think at step 3 in Add Another File - "Back in your terminal, type git status, and notice that README.md is no longer staged" might be confusing. 

It has not been staged (and the student has seen it not) be staged for 3 steps. Why suddenly bring the attention back to staged? Maybe it should say 'see how it is no longer committed and is showing modified? Or is something else out of order?

I guess, I feel that explicit instruction about what is being said at this point in the Git learning process is better than implicit. Cheers!

**Comment by I3uckwheat** [comment]
@sicou2 I think you are spot on with this: 
> I guess, I feel that explicit instruction about what is being said at this point in the Git learning process is better than implicit. Cheers!

Could you please make this more explicit? It would be great to have a PR from you, as you clearly have a handle on the issue.
