### ISSUE TITLE
Dead link in Ruby lessons

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/curriculum#16014]
https://www.theodinproject.com/courses/ruby-programming/lessons/ruby-building-blocks

very first link on that page has been moved or deleted... not sure where that content went.

If it was removed then we can just reword and delete that link.. if it was moved somewhere else we should fix the link.

**Comment by Tenacious-Qi** [comment]
Hello! So here is a related PR: https://github.com/TheOdinProject/curriculum/commit/33ff741cdcdf1e2f5493419b2059d66649432dd7

This PR replaced the broken link to the webdev101 section, the content of which had been moved to Ruby Basics. When I did this PR, I checked to verify the link was working and it was. The problem seems to have happened within the past two--three days.

As has been noted, the problem seems to be that the Ruby Basics section has been removed from the Basic Ruby section here: https://www.theodinproject.com/courses/ruby-programming 

The ruby_basics_lesson.md ( https://github.com/TheOdinProject/curriculum/blob/master/ruby_programming/basic_ruby/ruby_basics_lesson.md ) is still in the curriculum repo, but for reasons I don't understand, it's not being listed on the page. 

Would updating the ruby programming README.md to include ruby_basics_lesson.md fix this?

**Comment by codyloyd** [comment]
@CouchofTomato I'll let you double-check this... I'm way out of the loop on what's going on with the Ruby stuff.

**Comment by KevinMulhern** [comment]
This was caused by me @codyloyd, I removed some lessons in preparation for the new Ruby Basics section going out this weekend.

That link can be removed in the mean time :)

**Comment by I3uckwheat** [comment]
@KevinMulhern You think a good alternative is to just link to the github markdown page?

**Comment by Tenacious-Qi** [comment]
I created a [PR](https://github.com/TheOdinProject/curriculum/pull/16034) that replaces broken link with a link to github markdown page
