### ISSUE TITLE
Article link leads to 'error establishing a database connection'

### ISSUE THREAD

**Issue by RandyFoo07** [TheOdinProject/curriculum#16588]
https://www.theodinproject.com/lessons/objects-and-object-constructors#the-prototype

First link on The Prototype section leads to the problem, seems like the website itself is down at the moment. Any help is appreciated!

**Comment by marvingay** [comment]
@RandyFoo07
This issue was resolved today. The view of the curriculum on the website will not update until 5/2/2020 (If you're in a U.S. timezone).
 https://github.com/TheOdinProject/curriculum/issues/16525

You may can grab the updated way of viewing this resource [here](https://github.com/TheOdinProject/curriculum/blob/master/javascript/organizing-js/objects-constructors.md) or by passing the link into the WayBackMachine/archive on your own.
