### ISSUE TITLE
New VirtualBox images are not responsive and page can't scroll horizontally.

### ISSUE THREAD

**Issue by martink-rsa** [TheOdinProject/curriculum#17302]
#### Description

The images added in the Virtual Box instructions (#16915) are not responsive and extend past the page. Additionally, no horizontal scrollbar is added so a user can't scroll to see the rest of the image.

![image](https://user-images.githubusercontent.com/52622303/82438375-3ea69600-9a99-11ea-8676-97c163de91bd.png)

#### Scenarios

Simply loading the page will show that the images aren't responsive and overlap past the page. 

#### Files/Pages

Site map: [Web Development 101 ](https://www.theodinproject.com/courses/web-development-101)- [Pre-requisites](https://www.theodinproject.com/courses/web-development-101/lessons/prerequisites#step-1-download-virtualbox-and-xubuntu) 

Direct link: https://www.theodinproject.com/courses/web-development-101/lessons/prerequisites#step-1-download-virtualbox-and-xubuntu

#### Tasks

- [ ] Make pages responsive.

**Comment by KevinMulhern** [comment]
Thanks for reporting this @martink-rsa it looks like the images are being wrapped in p tags when they are parsed on the site. 

The git basics project has responsive images, we are wrapping them in <a> tags there, probably a hack to get around some quirk in the markdown parser we use for rendering the lessons in html.

But it works so that would be the suggested fix for this for whoever picks it up.

Link to the git basics project: https://github.com/TheOdinProject/curriculum/blob/master/web_development_101/git_basics/project_practicing_git_basics.md

**Comment by themetar** [comment]
@KevinMulhern No, there's an inline style="width:initial" that makes the images always their original size.

There are images that are usually narrower than the surrounding text so I guess the style was added to keep them from stretching to width:100% (as per .lesson-content img rule).

The git basics project page has mostly giant images that are squeezed down to 100%.

**Comment by themetar** [comment]
I can fix this, but should the fix be just to the inline styles or should we also change the website css (on the website repository)? // Replacing width: 100% with max-width:100% to only size-down images.

**Comment by I3uckwheat** [comment]
@KevinMulhern What do you think? ☝️

**Comment by SidWorks** [comment]
I will do it!

**Comment by ZachBaird** [comment]
Hey @SidWorks ! Feel free to shoot up a PR! Make sure to link this issue #.
