### ISSUE TITLE
Binary Search Tree Project Suggestions

### ISSUE THREAD

**Issue by andrewjh271** [TheOdinProject/curriculum#17956]
Lesson: https://www.theodinproject.com/courses/ruby-programming/lessons/data-structures-and-algorithms

I recently finished the Binary Search Tree project in Ruby, and I have a number of suggestions I wanted to put out there, in case they’re helpful.

Step 3. I wonder if it could be more explicit that making a balanced tree with the `build_tree` method is possible because the array it builds from will be sorted. I was confused here for a while, because the curriculum doesn’t mention building balanced trees from sorted arrays. At first I was thinking we were supposed to build a self-balancing tree. I also feel it could be worth clarifying that in the situation where you’re inserting one value at a time, a sorted array would produce the worst case scenario of a linked-list.

Step 4. Regarding the `delete` method: this is the first time in the TOP curriculum I felt like I was being asked to do something non-trivial that wasn’t ever mentioned before. Of course it’s easy enough to google, and lots of students figured it out (I did too), but still — I felt like this wasn’t in the style I’d encountered in the past, and it threw me off. Maybe there could be a link or two to some helpful resources.

Step 10. According to the Ruby Style Guide, an exclamation mark belongs at the end of methods for which a safe version exists:

```
# bad - there is no matching 'safe' method
class Person
  def update!
  end
end

# good
class Person
  def update
  end
end
```
My understanding is that there should not be an exclamation mark in `rebalance`.

Regarding the metaprogramming bonus section, I found these resources very helpful, and not what comes up first in google searches. Clues like using `send`, and that `yield` doesn’t work inside a `define_method` block would make this section a little more friendly. 
http://rubylearning.com/blog/2010/11/23/dont-know-metaprogramming-in-ruby/
http://rubymonk.com/learning/books/2-metaprogramming-ruby/chapters/25-dynamic-methods/lessons/65-send#solution4186
https://stackoverflow.com/questions/2306731/using-yield-inside-define-method-in-ruby

**Comment by rlmoser99** [comment]
Since I am working on the other chore for this lesson, I'll tackle this one too... I have a few questions.

I did not find step 3 confusing, but I can try to clarify it. However, I am confused by @andrewjh271 statement "I also feel it could be worth clarifying that in the situation where you’re inserting one value at a time, a sorted array would produce the worst case scenario of a linked-list."

I think mentioning a linked-link in this project would cause even more confusion, because the linked list is the project before this one & a binary search tree is different then a linked list. However, I do think a resource showing a balance binary search tree would be very helpful. I'll look for something else, but one resource that did help me when I did this project, was doing the binary search section (in javascript!) from the Khan Academy Link on this lesson: https://www.theodinproject.com/courses/ruby-programming/lessons/common-data-structures-and-algorithms

Step 4 was very confusing to me, because there was tons of conflicting information on deleting a node. I remember talking with Fensus about this on Discord. He recommended https://www.geeksforgeeks.org/binary-search-tree-set-2-delete/ and said that it didn't matter if you can chose to use the inorder predecessor or successor. So, I just went with the inorder successor. I just found this video: https://www.youtube.com/watch?v=wcIRPqTR3Kc. It seems to be a pretty useful visual for inserting & deleting. Does anyone object to using this video?

Step 10-  I agree that '!' should not be at the end of the rebalance method name.

Who decides if we keep or remove the metaprogramming bonus section? I think this decision should come from the moderators with the most Ruby experience. The only reason that it is part of the other chore on this lesson is because Fensus & Timato made a few comments such as "It's kinda a silly exercise though, should probably remove it" and "Yeah it's probably not the best use for pushing metaprogramming. And really doesn't show off it's power well." So, is there a process to go through where more experienced people make this decisions?

**Comment by andrewjh271** [comment]
Awesome, thanks for working on this.

All the resources on trees up to this point in the curriculum talk about inserting a node one at a time, including Additional Resources. (I think — I double checked this at one point). Just in the last week I’ve seen multiple people on Discord asking questions about this, assuming they’re inserting one Node at a time. I feel it could be useful being very explicit stating the `build_tree` method will be a different situation — we have a whole set of data that we’re sorting first, then building a tree from all at once.

If you take a sorted array and insert each item into a basic binary tree one at a time, you’ll get a binary tree with the number of levels equal to number of nodes — essentially a linked list. I think this is useful to mention because it illustrates that the benefits from a binary tree only exist if it’s balanced. I think with a picture this is pretty easily digestible. 

Section 3.1 of this link illustrates this well [https://www.cs.odu.edu/~zeil/cs361/latest/Public/bst/](https://www.cs.odu.edu/~zeil/cs361/latest/Public/bst/)

Actually their section on deletion is pretty good too. I thought the video you suggest looks good, but maybe both would be nice? I always like having an option I can read.

**Comment by rlmoser99** [comment]
Thanks for your input! I am just now looking at all the resources again in the previous lesson about BST and honestly, I am thinking that a few of the resources need to be re-evaluated. But, I am trying to read/watch them all before I propose any changes.

I have found a decent resource about how to build a balanced binary tree, but I am nearly positive that when I went through this lesson that I watched something similar. I am fairly certain of this because as soon as I read the #build_tree instructions, I knew that I needed to recursively half the array to build it out. However, it is no longer there and I can't find it. Maybe I can shift through my browser history & see if I can find it. This video is not using Ruby, so it really just serves as really good pseudo-code:
https://www.youtube.com/watch?v=VCTP81Ij-EM

**Comment by rlmoser99** [comment]
LOL! The video that I think I was remembering was actually from the Harvard's CS50 video on bubble_sort. However, in doing all the digging through my browser history, I am fairly certain that I learned the algorithm for the build_tree method from doing the binary search section from the Khan Academy Link which is the first additional resource of this page: https://www.theodinproject.com/courses/ruby-programming/lessons/common-data-structures-and-algorithms

Right now I am looking through the CS section as a whole and I am wondering why there is so much info on BST before the linked list project. The linked list assignment has a few additional links on the project page. So, right now I am wondering about moving some of the links that are only about BST to the BST project page. But, I need to review everything to see what is needed to understand the linked link assignment.

**Comment by Tenacious-Qi** [comment]
Hello all! I'd like to suggest changing #depth (Step 8) to #height. As I learned from this [video](https://www.youtube.com/watch?v=_pnqMz5nrRs) height and depth are often confused. The way Step 8 defines #depth would return the equivalent of how the video defines height.

Video defines height as "number of edges in longest path from the node to a leaf node"
--This is equivalent to how Step 8 defines #depth (number or levels beneath a node). If there are 3 edges from a node to the leaf, then that means there are 3 levels beneath that node.

Video defines depth as "number of edges in path from root to that node" (therefore root has a depth of zero).

Not a huge deal I guess since you can make the tree work either way, but thought I'd mention it.

**Comment by andrewjh271** [comment]
@rlmoser99 I see what you mean about the tree stuff coming right before the linked list. I didn't do the Khan Academy section you mentioned — you're saying you applied what they said about doing a binary search to the build_tree method, not that they directly went over that, right? That could definitely be a good clue.

The video about building a tree looks useful. Maybe even a positive that it's not in Ruby, so it doesn't just give the answer away.

@Tenacious-Qi I didn't know that about depth vs. height, but I think you're right. I found a confirmation on  [stackoverflow](https://stackoverflow.com/questions/2603692/what-is-the-difference-between-tree-depth-and-height#:~:text=The%20depth%20of%20a%20node%20M%20in%20the%20tree%20is,and%20its%20depth%20is%200.)

**Comment by Tenacious-Qi** [comment]
@andrewjh271 Good to have confirmation. I'll do a PR sometime soon.
