### ISSUE TITLE
Testing Your Ruby Code warm-up suggestions

### ISSUE THREAD

**Issue by remiborfigat** [TheOdinProject/curriculum#18444]
Hi everyone,

I just completed the [Testing Your Ruby Code](https://www.theodinproject.com/courses/ruby-programming/lessons/testing-your-ruby-code) assignments and I’d like to share some thoughts while it’s still fresh in my mind.

The first assignment (i.e. warm-up) could be improved by replacing the Tic Tac Toe testing part by writing tests for the three other similar Caesar Cipher projects: [Sub Strings](https://www.theodinproject.com/courses/ruby-programming/lessons/sub-strings), [Stock Picker](https://www.theodinproject.com/courses/ruby-programming/lessons/stock-picker) and [Bubble Sort](https://www.theodinproject.com/courses/ruby-programming/lessons/bubble-sort).
The reason is that it seems to be a waste of time to write tests for a ‘big’ project like Tic Tac Toe after having actually completed it. It defeats the TDD purpose. Writing tests for smaller projects, like it had been first initiated with Caesar Cipher, is more manageable and offers a smoother transition to the main TDD project of this course.

This is my humble opinion of course. Honestly, I didn’t write the tests for Tic Tac Toe and jumped straight away to Connect Four because it felt redundant.

Finally, if it’s the voted for solution, I don’t mind re-writing this warm-up assignment part.

**Comment by rlmoser99** [comment]
Writing tests for the Tic-Tac-Toe game is not to practice TDD, because Test Driven Development is when you write tests before you write the code. However, before one can tackle doing TDD with a new project, like Connect Four, you need to learn how to write tests for a project like Tic-Tac-Toe. 

Writing tests for Tic-Tac-Toe gives students the opportunity to learn how to use mocks/doubles to isolate methods and other rspec matchers then `eq` or `eql`. In addition, students may discover that some of their methods are too difficult to test because it is doing too much. So, they learn the importance of having small methods that only accomplish one thing. These lessons are important to learn before you do TDD with Connect Four.

Thank you for taking the time to submit this issue. You are welcome to submit a pull request to add Sub Strings, Stock Picker and Bubble Sort as additional practice in Assignment 1. However, writing tests for Tic-Tac-Toe is an important part of this assignment.
