### ISSUE TITLE
Incorrect filepath in example code

### ISSUE THREAD

**Issue by nanyaDev** [TheOdinProject/curriculum#21961]
**EDIT: Original issue is mistaken. See the follow up comment instead.**

[Project: Event Manager](https://www.theodinproject.com/courses/ruby-programming/lessons/event-manager-ruby-programming) instructs students to set up a file tree for the project, which can be boiled down to the following 2 quotes: 

1. "The filepaths we use in this tutorial will assume that we have put our event_manager.rb file within the lib directory."
2. "Download the small sample csv file and save it in the root of the project directory, event_manager."

This creates the following file structure:
```
event_manager
├── event_attendees.csv
└── lib
    └── event_manager.rb
```
However, the example code for event_manager.rb uses `contents = File.read "event_attendees.csv"`. This should be changed to `content = File.read "../event_attendees.csv"` since the .csv file is in the directory above the .rb file.

**Comment by nanyaDev** [comment]
As I worked through the rest of the lesson, I came across the part that requires inserting an html file next to the csv file. Here, the lesson notes that: 

"It is important to define the form_letter.html file in the root of project directory [..] because **when the application runs it assumes the place that you started the application is where all file references will be located.**"

After reading this I realized that the lesson expects you to run the ruby file while still in the root directory, by using `ruby lib/event_manager.rb`. This is non-obvious, since my instinct as a novice is to cd right into the directory containing the code. I think the bolded information should be mentioned at the start, since it is just as relevant to accessing the CSV file as well.

**Comment by rlmoser99** [comment]
@nanyaDev Thank you for taking the time to submit an issue, however I believe the directions are fairly clear in the Initial Setup section. It indicates to use `ruby lib/event_manager.rb` in 3 places and warns students to pay attention to file paths. https://www.theodinproject.com/courses/ruby-programming/lessons/event-manager-ruby-programming#initial-setup

I understand that your instinct was to cd into the directory that you created, but when following a tutorial it is very important to read everything thoroughly. 

I will keep my eyes open for other students that have issues with these instructions, but for the time being I am going to close this issue because I do not believe the line in bold needs to be duplicated in the setup section.
