### ISSUE TITLE
Ruby / OOP: Two linked quizzes largely ignore style guide and best practices

### ISSUE THREAD

**Issue by dwiehoff** [TheOdinProject/curriculum#22097]
[OOP](https://www.theodinproject.com/courses/ruby-programming/lessons/object-oriented-programming-ruby-programming)

The quizzes linked at the bottom (#5 and #7) ignore what's being taught before that and should likely be removed or replaced.

**Comment by rlmoser99** [comment]
@dwiehoff Thank you for taking the time to submit an issue. I have reviewed those quizzes and I think the biggest style guide violations were:
- double quotes instead of single quotes
- explicitly using `return`
- parenthesis in `method_name()`
- explicitly using self in `self.method_name`

While these quizzes largely ignore the style guide, I think they cover a lot of useful material and should not be removed because of these style guide violations. The students will learn the style guide as they use rubocop. 

In the long run, we will be expanding our OOP lessons and I will add this concern to those lesson plans. It will probably make the most sense for us to write our own material to replace those quizzes. 

However, I will leave this issue open for the time being & review it with other maintainers to see if we should increase the priority of the material covered in those quizzes.

**Comment by CouchofTomato** [comment]
@dwiehoff 

Thanks for the feedback. Can you be a little more specific on what they are ignoring as I'm not clear what you are referring to. If it is just style guide stuff then it's not worth us investing the time to find a replacement although will happily review any material you think is better. If it's something more fundamental then we can prioritise it as we don't want to show students something that may harm their development.

**Comment by I3uckwheat** [comment]
Style guides are often enforced by automatic linters. I don't think these minor violations are worth replacing this resource.

**Comment by I3uckwheat** [comment]
Closing due to lack of replies from the PR author.

**Comment by dwiehoff** [comment]
Thanks for the quick response and sorry for not getting back immediately. For me, personally, I might not see as much value in the exercises as you do and would consider them quite confusing to a beginner learner. I figured there should be a better resource which you might be aware of. If that's not the case and you see it differently, that's alright. Just thought I'd let you know my thoughts and let you do with it whatever you'd see as best. I would agree with @rlmoser99, though, that "writing our own material [as a replacement]" would be the best course of action 💯

**Comment by CouchofTomato** [comment]
@dwiehoff Thanks for coming back to us.

We would love to write more of our own material but that comes with the cost of having to maintain it more than just having to find a new resource if any become out of date. That's not easy as we are a relatively small team.

We do welcome feedback though so please keep it coming if you see any areas you feel could be improved.
