### ISSUE TITLE
Installations Overview: Make it obvious we have instructions on how to set up Windows computers to do TOP

### ISSUE THREAD

**Issue by CatQueenCodes** [TheOdinProject/curriculum#22174]
https://www.theodinproject.com/courses/foundations/lessons/installation-overview#os-options

Have been noticing people thinking they NEED a mac to Odin so they never start, and say things like "I wish I could do this without a mac/you had options to make it work for Windows people"

It was briefly discussed in Discord. People see **Mac** and **Linux** and nothing about **Windows** in bold at first glance (yea, they should be reading, but I guess a lot don't)

Adjust OS Options section to make it clear just because you have a windows computer does NOT mean you can't do odin. People seem to think if you must have a mac, or there aren't options (VM/Dual Boot) that can make a windows computer work. 

The words "OS/operating system" and "Linux"  "VM Dual boot" and installation stuff is often foreign to a lot of people who never have messed with this type of thing and just start using their computer right out of the box. So making it clear that the VM DualBoot section is for Windows people would be helpful! (possibly by changing the "**Virtual Machines and Dual-Boots**" heading in this section to "**Windows**" and adjust that section accordingly.

**Comment by wise-king-sullyman** [comment]
I can take a crack at this if you'd like.

**Comment by CatQueenCodes** [comment]
@wise-king-sullyman assined ya! Have at it :)

**Comment by xandora** [comment]
Those poor Widows!

**Comment by wise-king-sullyman** [comment]
Since Windows is the most common OS and it requires "extra work" to set up as a development environment; should it be moved to come before the Mac and Linux sections so that people don't read **Mac** and think the rest of the page doesn't apply to them?

If so should:
- The whole thing (VM/dual-boot section and "Concerned About Installing A New OS" section since that appears to be targeted at Windows users as well) be moved together?
- Just a Windows heading be placed above the Mac/Linux headings with a short blurb or two, and directions to read the sections on VM's/etc, with those sections remaining below the Mac/Linux sections?
- A Windows heading be placed at the top with a dropdown (like was done [here](https://www.theodinproject.com/courses/foundations/lessons/prerequisites#setup)) which, when expanded, shows the sections on VM's/etc so that these additional Windows user related items are kept in the Windows heading without pushing the Mac and Linux sections way down the page?
- Something else be done?

The dropdown is my favorite option because it would cut down on the length of the lesson for non Windows users, look less intimidating (I think), keep all the Windows stuff together without pushing the Mac/Linux stuff way down, and just *maybe* guide a higher percentage of windows users to actually read the stuff that they are supposed to read.

**Comment by twalton83** [comment]
Hey team! Can we revisit this?

**Comment by CatQueenCodes** [comment]
I think Having a "Mac" drop-down, and then a "Windows/Other" drop-down that then has the VM/Dualboot options inside it (possibly as drop downs as well)
