### ISSUE TITLE
Rubyrogues 131 Episode has really bad audio quality

### ISSUE THREAD

**Issue by bigfatbird** [TheOdinProject/curriculum#23072]
I am doing the curriculum at the moment and the RR Ep 131 about learning has really bad audio quality. It is very difficult to understand sometimes. 

Is there anything we can do about this, or find a better resource?

**Comment by rlmoser99** [comment]
@bigfatbird In the future it would be very helpful to include links so that we can easily find the lesson & resource that you are referencing.

Lesson: https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/gearing-up
Podcast: https://devchat.tv/ruby-rogues/131-rr-how-to-learn/

I just listened to a few minutes of it and skipped around and although the audio quality is not the greatest, I would not say that it is really bad audio quality compared to other podcasts and videos that I have watched. Could you provide specific time stamps of when you thought it was very difficult to understand?

Although this resource, just like any of our other resources, can be replaced if someone finds a resource that achieves the same objectives and is better quality.

**Comment by bigfatbird** [comment]
@rlmoser99 I am hearing it right now and the speaker that i dont understand mentions he has a disease if i understand correctly... I wasn't aware of that, so I am sorry if that came of as rude. I thought his/her audio stream or mic was broken. So I guess there is that.

Doesn't change the fact that I have to really concentrate hard to understand the things he/she says. I think i will just try to listen to the end and move on with TOP.
