### ISSUE TITLE
Factory functions lesson doesn't mention performance penalty compared to constructors

### ISSUE THREAD

**Issue by EmilioAK** [TheOdinProject/curriculum#23105]
[The lesson in question](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/factory-functions-and-the-module-pattern)

The resources in the previous lessons talked about how important it was to put methods on the prototype instead of the constructor itself, since that would mean the method isn't duplicated on every instance. However, that isn't done on factory functions at all. In my opinion this feels confusing, having the prototype introduced and talked about in terms of efficiency and in this lesson having it ignored. 

I suggest that an explanation for this be added so that it doesn't leave you confused as to why the prototype was introduced previously (e.g. Using factory functions doesn't utilize the prototype, which makes them less efficient, but they are a good choice when [insert when]).

**Comment by parent-tobias** [comment]
As a general rule, though, the memory/performance hit between either a constructor function or a factory function aren't that significant. Unless you're making hundreds of thousands of 'em.

I do agree, though, that a discussion of why inheritance is more brittle, and how factories address that brittleness, might be in order.

**Comment by EmilioAK** [comment]
What confused me was that in the previous lesson the prototype was introduced with a focus on that its important to use it because of efficency. To me at least, just one sentence as I suggested would have alleviated that confusion. Since that wasn't there I sort of assumed that the prototype was being used here in some way not metioned since it seemd off to me that efficiency was mentioned as important earlier and shouldn't just be dropped without a hint as to why.

**Comment by thatblindgeye** [comment]
The lesson that introduces the prototype *does* state that "**If you’re using constructors to make your objects** it is best to define functions on the prototype of that object." (emphasis mine). 

That said, I can see how a simple sentence or two could alleviate some confusion. One idea I can think of is updating the first example in the [factory function introduction[(https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/factory-functions-and-the-module-pattern#factory-function-introduction) section so that the constructor version uses the prototype, and a disclaimer after the code block stating something along the lines of "Notice how our factory function doesn't use the prototype" or something.

But I'd also like to hear y'all's suggestions if you have any!

**Comment by thatblindgeye** [comment]
@EmilioAK @parent-tobias Would either of you have any opinions on the above comment?

**Comment by thatblindgeye** [comment]
@parent-tobias @EmilioAK been a minute, but wanted to check to see whether y'all think this is still an issue, and if either of you would be interested in submitting a PR for it?

**Comment by EmilioAK** [comment]
> @parent-tobias @EmilioAK been a minute, but wanted to check to see whether y'all think this is still an issue, and if either of you would be interested in submitting a PR for it?

I think this is still relevant. I could create a PR for it if it's wanted

**Comment by thatblindgeye** [comment]
@EmilioAK That'd be great! I've assigned you
