### ISSUE TITLE
Adjust Minor Content Error

### ISSUE THREAD

**Issue by Conor-Developer** [TheOdinProject/curriculum#23139]
### Description

The wording in "Additional Resources" states there are more methods than covered in the lesson (with the example of #one). However, the lesson does in-fact cover the "**#one?**" enumerable method. Students will learn this during the exercise and within the article you read as part of the assignment.

#### Expected Behavior

https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/predicate-enumerable-methods

**Comment by thatblindgeye** [comment]
@Conor-Developer Just an FYI for the future when submitting a PR, please be sure to include a keyword and the Issue number in your PR if one exists so that when the PR is merged, the issue will also be closed. You had accidentally used "N/A" for Step 2 of your PR triage questions.

Closing this as the issue has been fixed in  #23140
