### ISSUE TITLE
CORS is the default option in Fetch docs

### ISSUE THREAD

**Issue by Mclilzee** [TheOdinProject/curriculum#23232]
in https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/working-with-apis#cors

we get told "For security reasons, by default, browsers restrict HTTP requests to outside sources" and the fix is to put `{mode: 'cors'} `.

Yet in the documentation, it says that `mode: 'cors'` is the default option for fetch.
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#supplying_request_options

not sure if i misunderstood it or it was just overlooked. hope i could be of help.

**Comment by fortypercenttitanium** [comment]
@Mclilzee Thanks for pointing this out! I think the best solution is to keep the intent of introducing CORS in the lesson intact while still removing the part about adding the `mode: 'cors'` to the options object. I also think we should still be teaching about passing the options object to the fetch method.

Would you like to take on this issue or do you want me to find someone else to assign it to?

**Comment by I3uckwheat** [comment]
The specification for fetch directly says: 
> "A request has an associated mode, which is "same-origin", "cors", "no-cors", "navigate", or "websocket". Unless stated otherwise, it is "no-cors"."

See here: https://fetch.spec.whatwg.org/#concept-request-mode

---

In reality, the context of how this gets decided is more complicated than a default, see here: https://stackoverflow.com/questions/44121783/fetch-api-default-cross-origin-behavior

Because the specification directly states 'no-cors' as the value when not passing anything, It's best to leave this as-is to prevent confusion in the future.

**Comment by Mclilzee** [comment]
This is weird, the site you posted is conflicting with the documentation. I thought the information provided by the documentation is reliable.
