### ISSUE TITLE
Improperly embedded CodePen Edit Link in INTERMEDIATE CSS - CSS Functions

### ISSUE THREAD

**Issue by gregolive** [TheOdinProject/curriculum#23404]
<img width="916" alt="Screen Shot 2022-01-26 at 10 28 07 PM" src="https://user-images.githubusercontent.com/89794134/151172118-52bb15ad-c8e2-4e26-852e-74c4b555fb41.png">

There is a link to Edit a CodePen in the CSS Functions lesson of INTERMEDIATE CSS that links to an Imgur image. I'm not sure if the fix would be as simple as moving the Embedded CodePen from above down to where this link is or if it is better have an external link to the CodePen.

**Comment by thatblindgeye** [comment]
For reference, this issue is related to PR #23430

**Comment by gregolive** [comment]
Hey @thatblindgeye, I see that this still looks like an open issue and that PR #23430 has not been updated recently. Should I create a PR that fixes this according to your [comment on the PR](https://github.com/TheOdinProject/curriculum/pull/23430#pullrequestreview-866798910)?

**Comment by thatblindgeye** [comment]
@gregolive thank you for checking the open PRs! I'm going to give that PR another day or two for the contributor to respond just because I said I would give a few days. That said, if we do not get a response I will definitely @ you here again to to check if you'd still like to work on this, at which point if you do I can assign you 🙂

**Comment by gregolive** [comment]
@thatblindgeye sounds good! 👍 Thanks for getting back to me!
