### ISSUE TITLE
Incorrect link or unclear link text in JS Fundamentals Part 2 

### ISSUE THREAD

**Issue by dunkOnIT** [TheOdinProject/curriculum#23529]
## Description of issue:

The 9th link in the "[Knowledge Check](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/fundamentals-part-2)" section of Javascript Fundamentals Part 2 reads "What are methods?". However, the link leads to [this page](https://www.w3schools.com/js/js_string_methods.asp) describing only the Javascript string methods.

By the lesson's own definition, methods are not exclusive to strings. As such I would expect the link in question to lead to a general discussion of what a method is conceptually in Javascript, not a list of string methods.

## Possible fixes:

Assuming I have correctly identified the issue, there are two possible fixes, depending on what the knowledge check is intended to do.

1. **If the knowledge check is intended to check whether the student knows what methods are:** I propose the link destionation be changed in this case.
2. **If the knowledge check is intended to check whether the student knows what the JS string methods are:** I propose the link text be changed to something reflecting this - eg, "What are the string methods?".

## Intended resolution of this issue

I am happy to make the PR for whatever change is necessary, but it isn't clear to me what the intention of the link in question is. If someone familiar with the lesson and its purpose is able to give guidance, I would be happy to implement it.

**Comment by 01zulfi** [comment]
Thanks for bringing this up. I agree the link text is misleading as it says "What are methods?" and then links to the [w3schools string methods](https://www.w3schools.com/js/js_string_methods.asp) page.

Let's talk about the possible fixes you presented:

> 1. If the knowledge check is intended to check whether the student knows what methods are: I propose the link destionation be changed in this case.

Methods only get a one sentence mention in the "Strings" section of the lesson. With only that to go off of, I don't believe it justifies a knowledge check, even if "Define what a method is." is in the learning outcomes of the lesson.

> 2. If the knowledge check is intended to check whether the student knows what the JS string methods are: I propose the link text be changed to something reflecting this - eg, "What are the string methods?".

This would be ideal, but since the very next knowledge check is "What is the difference between slice/substring/substr?", there might a bit of duplication.

What I suggest is:

- Remove the "What are methods?" knowledge check
- Change the verbiage of the next knowledge check to "What is the difference between slice/substring/substr string methods?"

If you have an alternate solution or if you want further justify any of your solutions, please don't hesitate to bring it up.

And if you still want to work on the PR, let me know so that I can assign you.

**Comment by dunkOnIT** [comment]
Thanks for the response! 

I think your fix sounds great. I would just make one additional suggestion: 
* Under "Learning Outcomes", change "Define what a method is." to "Understand what a method is." 

Two reasons for this change: 
* it is more in line with the current amount of emphasis placed on educating the student on methods in the lesson
* anecdotally, as someone busy doing the fundamentals course (albeit with a Python background already), a basic understanding of what "method" refers to seems sufficient at this stage of the course

@01zulfi Notwithstanding your opinion on the above suggestion, please assign me the PR!

**Comment by 01zulfi** [comment]
That sounds great. 

 Here's the acceptance criteria for the PR:

- [ ] Reword "Define what a method is" to "Understand what a method is." in learning outcomes
- [ ] Remove "What are methods?" knowledge check
- [ ] Reword "What is the difference between slice/substring/substr?" to "What is the difference between slice/substring/substr string methods?" 

I've assigned you, good luck! 🚀
