### ISSUE TITLE
intermediate-html-and-css/lessons/creating-a-grid - Knowledge check issues

### ISSUE THREAD

**Issue by krzt96** [TheOdinProject/curriculum#23531]
https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/creating-a-grid

![image](https://user-images.githubusercontent.com/94806776/153410683-60424994-ddab-463b-a17d-bd6cfcbbc4eb.png)

Feels like the first question should be referring to defining grid container. I don't know if this question was supposed to be tricky or something, but asking such questions on this stage, when we don't yet know what's head (maybe there is a way of defining grid items by other means that declaring the direct parent as a grid container... how should I know at this stage?) makes little sense to me.

Also, the third link doesn't work.

**Comment by reservecrate** [comment]
No idea about the first question. But, I can fix the broken (3rd) link, since I think we should just change `https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/creating-a-grid#grid-gaps` to `https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/creating-a-grid#gap`.

**Comment by PremSagarS** [comment]
I think the first question is supposed to be "Explain how to define a grid container" or it's a trick question.... you define an element as grid item by defining it's parent element as a grid container.
