### ISSUE TITLE
/foundations/html_css/html-foundations/elements-and-tags - knowledge check

### ISSUE THREAD

**Issue by melihthedev** [TheOdinProject/curriculum#23562]
On the knowledge check part, answer to this question; "What are the three parts of an HTML element?" is shown through a p tag, which is opening and closing tags and the content. Since we have self-closing tags such as img or input tags, I thought this could cause some misunderstandings in the following lessons. A following explanation regarding to this might be added.

**Comment by wise-king-sullyman** [comment]
@melihthedev I'm not sure if this paragraph was a new addition since you filed this issue, but the below paragraph discusses self closing tags and follows where the p tag you reference is in the lesson.

![image](https://user-images.githubusercontent.com/7115053/169177224-435338dc-d448-4090-8e6c-e77fc3130960.png)

Since it seems like this has already been addressed I'm going to close this issue, but thank you for taking the time to file it!
