### ISSUE TITLE
Additional resources for Object and Object Constructors lesson.

### ISSUE THREAD

**Issue by ls-madhu** [TheOdinProject/curriculum#23640]
- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
- [x] The title of this issue follows the `where the change occurs: brief description of request` format, e.g. `Global SCSS file: Buttons should have XYZ`

- [ ] I would like to be assigned this issue to work on it

**Description of the Feature Request**

I came across these two articles about Prototypes and Inheritance with a very good explanation, and I think they will be a good addition to the Addition resources in the "Object and Object Constructors" lesson:
1. [A Beginner’s Guide to JavaScript’s Prototype](https://medium.com/free-code-camp/a-beginners-guide-to-javascript-s-prototype-9c049fe7b34)
2. [JavaScript Inheritance and the Prototype Chain](https://medium.com/free-code-camp/javascript-inheritance-and-the-prototype-chain-d4298619bdae)

**Comment by LeoKirasic** [comment]
@ls-madhu, is there anything not covered by the already existing additional resources or lesson that the articles cover? We want to avoid having **too** many additional resources.

**Comment by ls-madhu** [comment]
@LeoKirasic No, everything is covered in the existing resources. But IMO the explanation in these articles are easy for beginners to understand.

**Comment by LeoKirasic** [comment]
@ls-madhu The articles you linked are good articles. Thanks for making the issue!

If anyone would like to work on this, please tag me and I'll assign you. 

We should add one additional resource, containing both of the links, since they're written by the same person and are best read in order. For clarification, [A Beginner’s Guide to JavaScript’s Prototype](https://medium.com/free-code-camp/a-beginners-guide-to-javascript-s-prototype-9c049fe7b34) should be the first article in the new additional resource, and [JavaScript Inheritance and the Prototype Chain](https://medium.com/free-code-camp/javascript-inheritance-and-the-prototype-chain-d4298619bdae) should be the second one.

**Comment by DaeguDude** [comment]
Can I take this one?

**Comment by LeoKirasic** [comment]
@DaeguDude Go for it!
