### ISSUE TITLE
Bug - : Heading in Introduction to node

### ISSUE THREAD

**Issue by ls-madhu** [TheOdinProject/curriculum#23707]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

There is something wrong with the heading "What is Node?" in [Introduction to Node](https://www.theodinproject.com/paths/full-stack-javascript/courses/nodejs/lessons/introduction-what-is-nodejs) lesson, the "is Node?" part is showing up two times. There is no problem with the markdown.

**2. How To Reproduce:**

1. Go to the [Introduction to Node](https://www.theodinproject.com/paths/full-stack-javascript/courses/nodejs/lessons/introduction-what-is-nodejs) lesson.
2. See the "What is Node?" heading.

**3. Desktop/Device:**

-   Device: Asus Tuf Gaming
-   OS: Window 11
-   Browser: Google Chrome
-   Version: Version 99.0.4844.51

**Comment by ls-madhu** [comment]
@01zulfi  Why remove all of them, since other underscores are not causing any problem. And how about replacing ```_``` with ```*```, will it still cause the problem.

**Comment by 01zulfi** [comment]
@ls-madhu This is the line I'm referring to:

```
### What _is_ Node?  
```

Markdown parser at the Odin website wraps all the text in underscores in an `em` element. It works fine in paragraph text on the website, but it does not work in lesson headings for now. That's why I've asked to remove them so the heading renders correctly. Unfortunately, `*` will not work either. 

The above acceptance criteria still holds if anyone wants to work on it!
