### ISSUE TITLE
Bug - : Rails Project Forms: Authentication Token error fails to appear

### ISSUE THREAD

**Issue by mgrigoriev8109** [TheOdinProject/curriculum#23753]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`
-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
In the [Rails Project: Forms](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/forms), Step 3 of the **HTML Form** part of the project, which states: "Submit your form and view the server output. Oops, we don’t have the right CSRF authenticity token (ActionController::InvalidAuthenticityToken) to protect against cross site scripting attacks and form hijacking. If you do not get an error, you used the wrong method from step 1." does not work after installing Rails 7.

**2. How To Reproduce:**
You can recreate this bug by cloning my repository and attempting the same step of the project using [this commit](https://github.com/mgrigoriev8109/re-former/commit/5e2ffa5e47d74c04f4e7f9834cfac29978e55a12). 

**3. Expected Behavior:**
You should receive an Authentication Token error, which does not occur - everything loads properly.

**4. Desktop/Device:**
On any computer.

**5. Additional Information:**
It appears as if the bug is related to TURBO_STREAM, and the error 
will appear if you add a `data-turbo="false"` attribute to the form. My suggestion for improving this lesson and fixing this bug is to ask learners to include this piece of code as a form attribute, to show them what would happen if they were running this form on a version of Rails that's earlier than Rails 7 (which might happen in some workplaces).

**Comment by RolandStuder** [comment]
This is a symptom of a bigger thing, generally the forms lesson is not up to date, updating it is actually somewhat a challenge, since forms now request a TurboStream, so one has to opt out of that, which is somewhat hard to explain, especially since the scaffold generator is not even using turbo streams but is returning a render with `status :unprocessable_entity`.

So just suggesting to use a `data-turbo="false"` attribute will not do, we should introduce that rails does special stuff with forms thanks to turbo drive. I started going through the lesson and I will try to update it.

**Comment by ChargrilledChook** [comment]
> the scaffold generator is not even using turbo streams but is returning a render with `status :unprocessable_entity`.

@RolandStuder I've noticed when using Rails 7 that form errors will not display unless you specify a status (that is not `:ok`) in the call to `render`. I'm _fairly_ certain this wasn't the case pre Rails 7 - have you encountered this at all? Would it also be related to turbo/drive changes?

**Comment by CouchofTomato** [comment]
@ChargrilledChook 

Yeah it's a turbo thing. I already have a PR waiting to be reviewed to address this in the lessons.

**Comment by nicolasseine** [comment]
I'm using rails 7.0.2.3
And I just had the Authentication Error when working on the project, which confused me because it was not the expected output acording to the lesson.
Had to add   
`skip_before_action :verify_authenticity_token
`
on my controller to get a 204 response as expected.

So maybe the "old" lesson content could be kept there, for information, i case other people stumble on this ?

**Comment by CouchofTomato** [comment]
@nicolasseine 

Can you give us some more information around this please

* Which project?
* Do you have any code you can link us to on github? If so which pages should we be looking at
* What output do you see in your terminal / browser. You can share screenshots etc.

Might be better to open this as a separate issue if you think our lesson isn't reflecting the output you are seeing so we can investigate.

**Comment by ChargrilledChook** [comment]
@nicolasseine This issue seems to have been resolved by the fixes in #23797. If you think there are still some potential problems, please feel free to open another issue per the last comment
