### ISSUE TITLE
Pattern matching lesson - Ruby track: Weblink duplication 

### ISSUE THREAD

**Issue by MLGabe** [TheOdinProject/curriculum#23817]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
Both assignments links covers the same content, even using the same examples. We could remove one of then, and if possible, add another one with a slightly different take. This way learners will have the opportunity to see the concept from a different point of view.

**2. Acceptance Criteria:**
- [ ] Remove one of the links
- [ ] Add a new link with a different explanation

**3. Additional Information:**
N/A

**Comment by wise-king-sullyman** [comment]
It's hard to give a solid yes/no on if this is something that's needed without a replacement resource suggestion, do you have one in mind?

**Comment by ChargrilledChook** [comment]
This issue popped up in discord again recently: [see discussion here](https://discord.com/channels/505093832157691914/540903304046182425/984501342309580860)

I did a bit of research and it seems the purpose of this site is simply to improve the default formatting of rdoc generated pages. The author was actually selected to improve the official Ruby docs, but the project is on hold due to conflict in the author's country.

Given the link is lagging behind in versions and is a duplicate in the first place, it makes sense to remove it. Ideally we should find a replacement, but if a good one can't be found I'm happy to just take it out.

**Comment by ChargrilledChook** [comment]
@thatblindgeye Yes, and I believe an extra duplicate has snuck in too

**Comment by Colo-Codes** [comment]
I would like to start contributing to The Odin Project, and this issue seems a good starting point for a Junior like me. Can I start working on this?

**Comment by ChargrilledChook** [comment]
All yours @Colo-Codes, feel free to tag me here if you need any assistance

**Comment by ChargrilledChook** [comment]
Hey @Colo-Codes, just checking in. Are you still working on this?

**Comment by ls1955** [comment]
I would like to start contributing to The Odin Project with this being the starting point. Can I work on this issue?

**Comment by ChargrilledChook** [comment]
Sure thing @ls1955, thanks for helping out :rocket: I've assigned it to you

**Comment by M-Sviridov** [comment]
@MLGabe I have found this link https://www.toptal.com/ruby/ruby-pattern-matching-tutorial that is very similar.

Otherwise there is this https://medium.com/@baweaver/ruby-2-7-pattern-matching-first-impressions-cdb93c6246e6 from Brandon Weaver, the same person who wrote the medium articles about find, reduce, etc introduced in TOP Ruby's path. But I felt like it wasn't as clear as the current resource.

Let me know what you think!

**Comment by MLGabe** [comment]
I liked the first one. Let's if anyone else agrees :)

**Comment by ChargrilledChook** [comment]
Happy for people to add more links to the extra reading. First link seems fine, but a little old (only covering it from Ruby 2.7). Most of it is probably still relevant, though. 

I've also seen people suggest https://womanonrails.com/ruby-pattern-matching and https://womanonrails.com/ruby-pattern-matching-second-look, with the second link being a bit more up to date

**Comment by M-Sviridov** [comment]
I really like those two links you provided!
