### ISSUE TITLE
Javascript Course: Instructions for Firebase users are unable to verify server side the user's completion time. 

### ISSUE THREAD

**Issue by zakia98** [TheOdinProject/curriculum#23922]
Complete the following REQUIRED checkboxes:
-   [ X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ X] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Firebase users are unable to create a system where users of their where's waldo  games completion time is verified server side to prevent hacking. Thus, the instructions need to be changed for firebase users. 

**2. Acceptance Criteria:**

[  ] Enhanced instructions  for firebase users

**3. Additional Information:**

**Comment by LeoKirasic** [comment]
Hey, @zakia98 thanks for creating the issue. The instructions should definitely be modified.

The line that needs changing is "do this on the server side otherwise the user could hack their score"

This needs to be changed to include a note that this is only for people using rails as their backend, and if learners are using firebase as the backend they don't have to attempt to do the timer on the backend.

**Comment by iawong** [comment]
@LeoKirasic Hey, can I work on this?

**Comment by LeoKirasic** [comment]
@iawong  go for it!
