### ISSUE TITLE
Moving the fetch docs in the Working with APIs lesson

### ISSUE THREAD

**Issue by eltonbautista** [TheOdinProject/curriculum#23926]
Complete the following REQUIRED checkboxes:
-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
Hi! I was going through the Working with APIs lesson and by the end of the code along I was a bit confused on what was happening with the fetch and then functions. I see that in the assignment section the first step mentions reading the documents for the Fetch API. Wouldn't it be more helpful if the reader went through the Fetch API docs before moving forward through the rest of the lesson? This way while doing the code along there would be less mental gaps and they understand to a better degree what is happening with fetch and .json() since that point in the curriculum is the first time they're seeing them. I've noticed in a handful of other lessons this was the structure of the lesson and it helped me understand what was going on a bit better. 

**2. Acceptance Criteria:**
Moving the "Read the Fetch API docs" earlier in the lesson. 

**3. Additional Information:**
Link to the Lesson: https://www.theodinproject.com/lessons/node-path-javascript-working-with-apis

![image](https://user-images.githubusercontent.com/94667178/161075300-fe2d934e-0d8e-459e-af4e-2d8025821d0d.png)

I'm thinking the reference to read the Fetch API docs could be somewhere here?

**Comment by 01zulfi** [comment]
Hello! It is ideal to have all the lesson readings in one place (i.e in the Assignment section) rather than sprinkling them throughout the lesson. 

I think the lesson does an adequate job of showing how `fetch` works for the code examples. Users are also expected to have knowledge on `then` function going into the lesson. Furthermore, I don't believe the understanding of the `.json` method is imperative to the lesson. 

If you believe moving the fetch docs is ideal, do explain your thoughts. I'm happy to reassess. Lastly, if you think the lesson could do a better job on explaining `fetch`, let us know.

**Comment by 01zulfi** [comment]
@eltonbautista Closing this now, if you have any questions, feel free to share.
