### ISSUE TITLE
NodeJS - React - Hooks : Update Code Snipper

### ISSUE THREAD

**Issue by Mclilzee** [TheOdinProject/curriculum#24115]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

In the Functional React component lifecycle lesson precicesly this code snippit : https://www.theodinproject.com/lessons/node-path-javascript-hooks#useeffect

The code have multiple issues with it, the first one is we passing in dependency which is "color", this makes us remove and reattach the same event listener multiple times unecessarly - not entirely unecessarly more on that later -.

In reality we only need one event listener and we can keep the React.useEffect hook to have an empty array [ ] dependency, this insures that the event listener is only attached once and removed once, after we unmount. However that is not the case and i can understand why it is so, when we remove the "color" dependency from our Effect hook, the function does not work as intended anymore and that is because we are relying on what "color" is to update our colors. That is the second issue, we should never rely on the state to update our state and actually use the call back function that is provided by setState to know our previous state.

**2. Acceptance Criteria:**

 - [ ] Change the snippet to properly reflect the way we should use setState() with a call back function, if we rely on the previous state.
 - [ ] Update the effect hook to take empty array with a console.log("I have been called") to show a better example that our Effect hook being called once.
 - [ ] Add a second snippet to reflect that including a dependency in the array will call that function everytime the dependency changes, with another console.log() perhaps.

**3. Additional Information:**

**Comment by wise-king-sullyman** [comment]
While yes, this isn't perfect React (and there is definitely good logic behind not wanting our examples to show code that isn't best practices), I'm not sure I fully agree with the solution proposed here. If we were going to really get into what would be the "best" way to implement the behavior in the code snippet referenced above I believe that would be to completely omit the useEffect and pass the color changing callback as an onClick to the div.

Since the focus of the snippet in question is on the useEffect hook I don't think we should introduce the `setCount(prevCount=> prevCount + 1)`  syntax here, and rather discuss it (and when/why to use it) in the `useState` section.

Broadly I do agree that the example for useEffect could be improved though. But I don't think I'd want to see something that just uses console.log to demonstrate that.

**Comment by NeptuneRjo** [comment]
Would it be too complex to use an onClick listener on the div that fires "setColor(color)"? This essentially removes the need for mounting an event in the hook AND the "changeColorOnClick" function can be simplified to just the if/else statement. 

I think it would actually be easier to read while still communicating that updating "color" will cause useEffect to fire because it is a dependency.

It's still not the *best* practice, but as mention before, best practice isn't exactly the goal.

**Comment by thatblindgeye** [comment]
@01zulfi do you feel this issue would be made invalid by the React lessons revamp?

**Comment by 01zulfi** [comment]
Yeah, this issue would be made invalid when the new React lessons ship. That said, I'd like to keep this issue open until we have the new React lessons out just as a reminder that the code examples need to be clear and easily understood. I'd also like to reread the points made in the above discussion when the newer lessons are ready. I hope that makes sense.

**Comment by thatblindgeye** [comment]
@01zulfi  Sounds good. Put an on hold label just so it doesn't get worked on/closed

**Comment by Lofty-Brambles** [comment]
@01zulfi - would this issue be closed? This becomes a non-issue with the newly merged effects lesson.

**Comment by 01zulfi** [comment]
@Lofty-Brambles Yes, will be closing this after we ship the new lessons.

**Comment by 01zulfi** [comment]
Closed as irrelevant with the new React course
