### ISSUE TITLE
Bug - Understanding Errors lesson: Image not corresponding to the example code

### ISSUE THREAD

**Issue by andras-tsitskan** [TheOdinProject/curriculum#24250]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:
-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
An example code is presented in "Type Error" subdivison of the ["Understanding Errors" lesson](https://www.theodinproject.com/lessons/foundations-understanding-errors#type-error). Beneath the code there is a screenshot of the error message which is thrown after running the example code right above it. The screenshot shows that the error occurred on line 4, whereas the example code has only three lines. The screenshot should be updated to correspond to the example code.

**2. How To Reproduce:**
1. Go to "Type Error" subdivison of the ["Understanding Errors" lesson](https://www.theodinproject.com/lessons/foundations-understanding-errors#type-error) and see the screenshot.

**3. Expected Behavior:**
1. The image should correspond to the code, i.e. show that the error occurred on line 3. Screenshot should be updated.

**Comment by giovanniPepi** [comment]
Screenshot is actually accurate if you copy the entire code, because there is an empty line between the variable declarations and the console.log : 

![image](https://user-images.githubusercontent.com/5255535/175958227-0d867f88-a8d8-4e77-b6d6-efa70f55ea3d.png)

Whereas if you type the code without an empty line, it shows the error as happening on line 3:

![image](https://user-images.githubusercontent.com/5255535/175957991-3725df68-ec97-448f-a1cf-1372e51b06e0.png)

Let's wait and see what the Odin Team decides, but this behavior does not seem to be a bug per se

**Comment by thatblindgeye** [comment]
@giovanniPepi the code they are referring to is the one that ends with `const message = str1.push(str2);`.

@andras-tsitskan I've assigned you to this issue.
