### ISSUE TITLE
Ruby Installation Lesson: Update with instructions for updating ruby-build

### ISSUE THREAD

**Issue by ChargrilledChook** [TheOdinProject/curriculum#24264]
**Overview**

We have recently updated our recommended Ruby version to 3.1. As part of this upgrade, we have encouraged learners to go back and update their Ruby version using the [Installing Ruby Lesson](https://www.theodinproject.com/lessons/ruby-installing-ruby).

One potential issue when attempting to update Ruby via rbenv is missing versions for Ruby build. While the fix for this is relatively simple (follow the command in the error message) we should add a small line in the lesson to make this possible step explicit. See screenshot for an example error message and fix.

:spiral_notepad:  **Acceptance Criteria**
* [ ] Instructions are updated for Linux 
* [ ] Instructions are updated for Mac (nb - I am unsure of the exact process on Mac, but possibly different)

:eyes: **Contributions Wanted**

Please respond here to be assigned this issue. It may require a bit of independent research for the Mac side. Feel free to ping me here if you need any extra guidance or clarification.

:lady_beetle: **Example Error With Fix**

![error screenshot](https://cdn.discordapp.com/attachments/543074220691947531/985482348726476810/unknown.png)

**Comment by matristle** [comment]
I'm up for this! @ChargrilledChook

**Comment by ChargrilledChook** [comment]
@matristle All yours, thanks!

**Comment by matristle** [comment]
- [ ] Instructions are updated for Linux

#### Proposed Addition

>If you've already installed `rbenv`, we'll need to update the `ruby-build` plugin. As such, let's pull in the latest Ruby version definition:
>
>```bash
>git -C "$(rbenv root)"/plugins/ruby-build pull
>```


I'm thinking of adding it:

![image](https://user-images.githubusercontent.com/97355883/174480448-4b056ab9-7616-44aa-afe4-aa91f95487a6.png)

That way, it doesn't interrupt the flow of the paragraph after `rbenv install 3.1.2 --verbose` and only extends it.

#### Source
https://github.com/rbenv/ruby-build/wiki#updating-ruby-build

---

 - [ ] Instructions are updated for Mac (nb - I am unsure of the exact process on Mac, but possibly different)
 
#### Proposed Addition
I'm thinking of almost following suit for macOS (at Step 3.3), but since it's not installed as a plugin as on Linux, `ruby-build` seems to need to be updated/installed with Homebrew via `brew upgrade ruby-build` to update an existing `ruby-build` and/or `brew install ruby-build` to install it if necessary.

In the [rbenv Installation doc](https://github.com/rbenv/rbenv#homebrew), the command is listed as:
```bash
brew install rbenv ruby-build
```
`ruby-build` isn't listed as an argument in the lesson, which seems to imply that it isn't installed.

Subsequently, I think it would be reasonable to make the lesson command as the above block command to also install `ruby-build`.

@ChargrilledChook That said about the macOS command, should I just append `ruby-build` to the lesson command or would it be preferred to add an explicit line talking about `ruby-build` for this portion of the macOS installation (at Step 3.1)?

#### Source
https://github.com/rbenv/rbenv#homebrew
