### ISSUE TITLE
Bug - Foundations/Inspecting HTML and CSS: Different style applied to h1 than shown in the lesson's screenshot

### ISSUE THREAD

**Issue by notmyf4ulty** [TheOdinProject/curriculum#24305]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

In the "Inspecting Elements" part of the lesson, there is a screenshot showing what should be displayed to the user when inspecting TOP's homepage. Imo it should be something else there.

**2. How To Reproduce:**

1. Log in
2. Visit the Inspecting HTML and CSS lesson page from the Foundations Course
3. Go to the "Inspecting Elements" part of this lesson
4. Note [this screenshot](https://cdn.statically.io/gh/TheOdinProject/curriculum/594984d7c9f9e744577f19ea475b3864e8cc7c91/html_css/v2/foundations/inspecting-html-and-css/imgs/02.png)
5. Visit the TOP homepage in incognito mode and inspect the same part of the page with Chrome Dev Tools.
6. [The following will be shown (at least in my case)](https://i.imgur.com/H0CC80p.png)
7. The style applied to h1 is completely different than in the screenshot from the lesson

**3. Expected Behavior:**

I'd say that "my" version should be shown in the lesson.

**4. Desktop/Device:**

-   Device:  Lenovo Thinkpad T590
-   OS:  Windows 10 (yup, I know it's not Linux, but does it matter in this case?)
-   Browser:  Chrome
-   Version:  102

**5. Additional Information:**

**Acceptance Criteria (added by @thatblindgeye )**
- In the "The Inspector" section, remove the verbiage about going to the TOP homepage and instead ask users to inspect the lesson page itself and use that to follow along
- In the "The Inspector" section, remove the image
- In the "Inspecting Elements" section, remove the second image (the one that shows the devtools and homepage side by side; we should only need the 3rd image that shows overwritten styles and applied styles)
- In the "Testing Styles in the Inspector" section, update the verbiage and remove the image. We should just explain what updating styles in dev tools does and what it doesn't do ("...the webpage responds with the changes in real-time. This won’t affect the source code in your text editor, but it is extremely useful for quickly testing out various attributes and values without needing to reload the page over and over again.")

**Comment by sheilaJava** [comment]
Hi 👋 Are you talking about the size and margin of the heading ?
  If so I think they're different on your screen because they are defined using % and rem units in the CSS, as you can see in the _Styles_ tab in the _DevTools_. % and rem are **relative [units](https://www.w3schools.com/cssref/css_units.asp)**, which would explain why the elements' sizes are different on every screen (**depending on the screen size**). I hope I didn't misunderstand your issue and answered appropriately !

**Comment by notmyf4ulty** [comment]
Hi @sheilaJava, thanks for your comment. 

It's not what I meant though. If you compare two links that I provided in my original post, you will notice that it's not about specific dimensions / other properties being different, but **the whole classes**.

1. In the lesson's screenshot there are the following assigned to the `h1` element: `accent`, `hero__main-heading`
2. In my case it's: `text-4xl`, `font-light`, `text-gold-500`, `mx-auto`, `pb-4`

**Comment by notmyf4ulty** [comment]
> They may have changed the HTML/CSS after taking this screenshot. 

@sheilaJava That's what I think as well. Although I didn't have a problem with this part of the lesson as I'm somewhat proficient with frontend dev basics, it took me some time to figure out that probably this is a problem with a screenshot. 

The reason why I created the issue is that I thought about other participants (many of them probably at the very beginning of their web dev journey), and this could be a little problematic for them to understand why the result in their inspector is different than the one from the screenshot.

**Comment by thatblindgeye** [comment]
I wouldn't object to a PR being made to update this screen shot, but I think it's important to keep in mind that the point of that section of the lesson isn't to show the current styles of the home page, but rather to give an overview of what the inspector looks like when inspecting an element.

So while updating the screenshot would work *for now*, a better solution might be to just mention that users shouldn't be focusing on the styles that are actually applied, but rather to get a feel for how things *in general* look when inspecting things with the inspector.

**Comment by DigitalKnight0** [comment]
@thatblindgeye coming from the other issue, i personally think that directing learners to site's main page is bit unnecessary (partially because it displays a ton of tailwinds classes, which new learners might find intimidating due to the complexity). Maybe we can redirect them to a someplace simpler with minimal and simple css? Or just exclude the redirection at all and just use the picture as is to show them how devtools look like

**Comment by thatblindgeye** [comment]
@DigitalKnight0 I wouldn't be opposed to using a site that has simpler CSS, but at the same time we do several times link to things that may include concepts beyond what a user should know at that point because the user is meant to zoom out and focus on the higher level thing rather than a specific piece. In this case users should just get a feel for what inspecting a page's HTML/CSS looks like, not so much *what* the CSS actually is. Again, not that I would "shut down" using another site with simpler CSS, but wanted to provide reasoning for using the TOP site itself in the first place.

I would actually opt for removing the link to the homepage and just having users inspect the page of the actual lesson itself.

**Comment by Hoslok-1** [comment]
Hello @thatblindgeye, I've almost finished resolving this issue. I've replaced the screenshots in the img folder and re-written parts of the lesson to reflect the said new screenshots. That being said, I do not know how to replace ![Chrome Inspector] part in the .md file. 

For reference: 
![doubt](https://user-images.githubusercontent.com/107808312/181916422-b6c8ba2c-2141-405f-af77-276963bfbd99.png)

I've copy and pasted my modification into the https://www.theodinproject.com/lessons/preview tool and everything works fine apart from the images.

There are also few more like this called ![Inspector Icon], ![Styles Pane] etc.
I'm not sure what it does and how I can go about changing it to the images I've replaced in the .img folder, can I know what I can do to get this right?

**Comment by exertustfm** [comment]
@Hoslok-1 I just submitted a pull request at the same time you've made this comment, lol. Admittedly I didn't do anything except change the first image. (the way you do that is by [hyperlinking with markdown](https://anvilproject.org/guides/content/creating-links), you need the link to your new image which for mine is in my repository fork where I've uploaded it).
I didn't notice that maybe more than the first screenshot should be changed and whether it would be out of scope in this issue. I proposed the idea of a future rewrite of the lesson in the [pull request.](https://github.com/TheOdinProject/curriculum/pull/24475)
Your own commits may be helpful if you wish to add them.

**Comment by Hoslok-1** [comment]
Haha no worries @exertustfm, I replaced all the images because I didn't want one of the reference images to be the home page and the other one to be on the current page. But, I am still a little confused on how to replace the images. In my case, I've simply deleted the previous images and replaced it with the new one with the same name. Do I still need to change the link for it? 

With the post you've referenced, I understand there are different ways to creating links. This seems to be an external link since it's a statically.io. Do I need to host it there and then link it in the .md file?This is my first time I'm contributing on an open source project so I'm a little lost.

**Comment by exertustfm** [comment]
@Hoslok-1 Yes you need to change the links for them. I didn't know what statically.io was until I just researched it now, it's basically a type of file caching service. It already works with files on Github by
 [following this conversion method called "staticzap"](https://statically.io/docs/using-staticzap/)

[How to hyperlink](https://user-images.githubusercontent.com/54768149/182029267-4447f5b6-3f94-4112-9ec1-46d801a17e4c.png)
The screenshot here shows how to hyperlink on markdown, you wrap some text in brackets, then put the link it goes to in parentheses.

I just hyperlinked it with the direct link to my forked github repository image that I uploaded, I didn't delete any others because I didn't know if I should or not.

With all that said, it's probably correct to use the statically.io converted link instead of direct links to github repositories.

**Comment by Hoslok-1** [comment]
Thank you @exertustfm, I was able to replace the images!

**Comment by keshav-rockwinder** [comment]
hey i would like to contribute to this project.please create a pull request

**Comment by thatblindgeye** [comment]
@keshav-rockwinder are you still interested in this? I've updated the original comment with acceptance criteria for guidelines on how this issue should be resolved.
