### ISSUE TITLE
Broken link in Foundations curriculum's Git Basics section

### ISSUE THREAD

**Issue by roman-thapa** [TheOdinProject/curriculum#24426]
[Github's Foundation repository](https://github.com/TheOdinProject/curriculum/tree/main/foundations)
In this repository in [README.md](https://github.com/TheOdinProject/curriculum/tree/main/foundations#readme) link to [Git Basics section's](https://github.com/TheOdinProject/curriculum/tree/main/foundations#:~:text=Up%20Git%20%2D%20lesson-,Git%20Basics,-Introduction%20to%20Git) lesson link are broken

 
thank you (since this is my first time reporting any issue if there is any mistakes please try understanding it)
i hope you will look into it

**Comment by roman-thapa** [comment]
seems like problem with [Github repository](https://github.com/TheOdinProject/cu%20rriculum)
is fixed now it redirecting to correct repository 
I'll be removing that part from the issue 
since broken link of [Git Basics section's](https://github.com/TheOdinProject/curriculum/tree/main/foundations#:~:text=Up%20Git%20%2D%20lesson-,Git%20Basics,-Introduction%20to%20Git) is yet to be fixed Im not closing issue

**Comment by ericjmorey** [comment]
I'm not familiar with the intent of the maintainers. It looks like different topics were grouped under main. For example all **git** topics in the curriculum would be under:
main/git
with subdirectories:
foundations_git
intermediate_git

The new structure seems to intend to place each topic in sequence of presentation to learners. For example all topics presented to learners in the Foundations path would be under:
main/foundations
Where **git** would have its own subdirectory containing only those git lessons intended for the Foundations path. That is:
main/foundations/git/introduction_to_git.md
main/foundations/git/git_basics.md

It should be pointed out that under the current structure, there exists:
main/git/foundations_git/[commit_messages.md](https://github.com/TheOdinProject/curriculum/blob/main/git/foundations_git/commit_messages.md)
This lesson is not currently pulled into The Odin Project website by the TOP app. It's not clear if this is intentional. 

I'd like to help out. However, there are several open questions about what is intended by the maintainers.
