### ISSUE TITLE
Hoslok-1:replacing_screenshots_issue#24305

### ISSUE THREAD

**Issue by Shinobione-Kinobi** [TheOdinProject/curriculum#24676]
Hoslok-1:replacing_screenshots_issue#24305

_Originally posted by @Shinobione-Kinobi in https://github.com/TheOdinProject/curriculum/issues/24653#issuecomment-1256719143_

**Comment by rlmoser99** [comment]
@Shinobione-Kinobi I am not sure if you intended to make an issue, as this does not provide any information. Since this looks like a mistake, I am going to close this issue. However, if you intended to leave more information, please create a new issue using our `Bug Report` or `Feature Request` issue templates.
