### ISSUE TITLE
Installations: Update VirtualBox Instructions to reflect VirtualBox 7.0 release

### ISSUE THREAD

**Issue by xandora** [TheOdinProject/curriculum#24793]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Oracle released VirtualBox 7.0 on 10/10/22. There are some significant UI changes and our screenshot instructions may no longer match what is shown to a user that installs this new version.

We need someone to take on replacing any screenshots that are now out of date in the Installations lesson.

**2. Acceptance Criteria:**

TBD

**3. Additional Information:**

**Comment by zapxcero** [comment]
I installed the latest version and the steps were somewhat reduced or compressed. For example, it didn't show the option to dynamically allocate/fixed size hard disk file. Definitely needs an update.

**Comment by scheals** [comment]
Just my silly take on this - link to previous version and wait like two months until they iron out everything with 7.0 and then switch. Looking at their forums yesterday didn't give me much confidence in the release. They have also released 6.1.40 today.

**Comment by xandora** [comment]
That's definitely another possibility, I didn't set any acceptance criteria for the Issue for this reason. :D

**Comment by scheals** [comment]
I have ninja-edited the comment about people having issues with 7.0.0 - not as many reports as I thought there were. Yet.

I'm happy to do whatever changes needed to the instructions, I've already attempted to improve them in proposed #24776 but that's for the current version.  I imagine various changes would still transfer to the new instructions if y'all decide to move to 7.0.0. I could also reinstall VBox on my laptop and test things out there, although I won't be able to gauge performance in any meaningful way due to laptop's low specs.

**Comment by xandora** [comment]
@scheals I think that's the best option for now. Would you like to make that PR?

**Comment by scheals** [comment]
> @scheals I think that's the best option for now. Would you like to make that PR?

#24808 ready!

**Comment by scheals** [comment]
@xandora 
I might be interested in re-doing the instructions for 7.0. I think reasonable amount of time has passed, enough users have trailblazed this version and so far, the sudoers issue is the only one we need to give instructions for. We could do that either through terminal or the GUI. Otherwise, our instructions should greatly reduce in length due to no need for the GuestAdditions one & the fact that the unattended installation is a lot more streamlined, reducing the amount of other various notes we needed, like how to deal with the already inserted GuestAdditions CD issue.

I also think that due to the space we should get thanks to this we could include some of our most asked questions - those revolving around performance and the one about scrolling speed. This should improve non-discord learners' experience significantly in addition to various notes we already have on there.

**Comment by xandora** [comment]
@scheals I was just thinking this a couple days ago. It'd be nice to be able to remove the GA instructions.
