### ISSUE TITLE
Installing Ruby: MacOS arm architecture will often need to reinstall command line tools before installing Ruby

### ISSUE THREAD

**Issue by JaeGif** [TheOdinProject/curriculum#24915]
### Describe your suggestion

In Installing Ruby, the instructions for installing on MacOS are slightly dated as the process for new Apple Silicon chips could be slightly different. 

When running the command:
`rbenv install 3.1.2 --verbose`
in the terminal, if a user's computer has an ARM chip, they will instead get an error: 

`xcrun: error: unable to load libxcrun (dlopen(/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib, 0x0005): tried: '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need '')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (no such file), '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need '')))`

A similar issue is detailed here on the apple forums: 
https://developer.apple.com/forums/thread/652377l

The recommended solution is to remove the command line tools
`sudo rm -r /Library/Developer/CommandLineTools`

Followed by:
`xcode-select --install`

To reinstall the command line tools. 

After reinstalling the command line tools, the rest of the installing Ruby section works fine. 

Note: Simply updating the command line tools or Xcode does NOT solve the issue. 

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-installing-ruby

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Additional Comments

Running sudo command has the potential to go horribly wrong for new developers. If anyone can find a solution that doesn't require uninstalling CLT's that should be preferred.

**Comment by ChargrilledChook** [comment]
Thanks for the detailed report @JaeGif, much appreciated. 

I personally don't have experience with this but can cross reference with some people at work who use M1 Macs and see if there's an alternative. Open to ideas from others as well, but your proposed solution seems good at a glance 

I agree with your additional comments, but it's not necessarily a deal breaker in this case as it is something we have learners do when needed

**Comment by JaeGif** [comment]
No worries, I'm not entirely sure why I only got this error when trying to install Ruby as I'm following the Node path and haven't had any issues with installing node libraries or git. Cruising the forums seems to imply it might be related to updating the OS mentioned [here](https://apple.stackexchange.com/questions/433751/git-not-working-on-m1-chip-after-migration.) and [here](https://stackoverflow.com/questions/66064033/unable-to-run-git-on-mac-os-big-sur). This would track as I just updated my OS yesterday. 

If anyone else runs into the same issue it might be worth adding a note to the section, but it doesn't seem to be a very common issue, just often enough that there's a handful of forum posts.

**Comment by royojeda** [comment]
This issue came up just recently [in this discord discussion](https://discord.com/channels/505093832157691914/1068919323747422329).

Unfortunately, even with

- reinstalling Xcode,
- verifying that rbenv is installed correctly (using [information from rbenv's wiki](https://github.com/rbenv/rbenv/wiki) including using [rbenv doctor](https://github.com/rbenv/rbenv/wiki)),
- properly configuring the build environment for ruby-build (using [instructions from ruby-build's wiki ](https://github.com/rbenv/ruby-build/wiki#suggested-build-environment))
- restarting the user's computer, and
- attempting to install different ruby versions (3.1.2 and 3.2.0 are attempted),

we were unable to install ruby on an M1 Macbook Pro. If anyone has any other idea to try, the user having this problem can be and informed through the linked discord thread.
