### ISSUE TITLE
JS: Fix prereq knowledge being uncovered by an assignment in JS fundamentals part 4

### ISSUE THREAD

**Issue by antwonthedamaja** [TheOdinProject/curriculum#25094]
### Describe your suggestion

The assignment 04_removeFromArray in the JS fundamentals part 4 section seems to require array knowledge not yet covered or linked to by Odin. The assignment seems to require the use of filter, map, or forEach, which I personally have not seen before this.

Solution: Link this article after the two on arrays
https://www.w3schools.com/js/js_array_iteration.asp

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-4

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by ManonLef** [comment]
I think with the problem here could be the more advanced solution shown. The solution does indeed use methods that are not covered yet. This exercise is however solvable with the array methods and loops introduced.

For example:

```js 
const removeFromArray = function(array, ...arg) {

    let resultArray;
    let original = array; 
    let items = [...arg];

    for (let i = array.length; i >= 0; i--) {
        for (let j = items.length; j > 0; j--) {
            if (array[i] === items[j-1]) {
                resultArray = array.splice(i, 1);
            } else {
                continue;
            }
    }
}
```

I often see people asking in discord about the major difference in their solution vs the solution in the solutions branch. Perhaps that could be something to look into instead: 
- providing a solution with the methods covered so far 
&
- add a solution that would be optimal when one has covered more JS and wishes to optimise these in the future
