### ISSUE TITLE
Ruby on Rails: Standardize "Learning Outcomes" to "Lesson Overview"

### ISSUE THREAD

**Issue by xsherryhe** [TheOdinProject/curriculum#25140]
### Describe your suggestion

Some of the RoR lessons have an overview section titled "Learning Outcomes", while others have the title "Lesson Overview". Also, some of the bullet points in the overview sections are phrased as questions (e.g., "What is an ORM?"), while others are phrased as actions (e.g., "Name and describe the 7 RESTful controller actions."). 

I propose standardizing the overview sections following the current [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md). This means changing overview sections to all have the following format:

> ### Lesson Overview
> This section contains a general overview of topics that you will learn in this lesson.
> - What an ORM is.
> - Using Active Record to execute SQL.
> - ...

This was fixed last year for the Foundations lessons in [a series of issues](https://github.com/TheOdinProject/curriculum/issues?q=is%3Aissue+learning+outcomes+label%3A%22Project%3A+Style+Guide%22+). I would like to fix it for the Ruby on Rails lessons.

If approved, I would love to be assigned to this issue!

#### Acceptance Criteria

Replaced "Learning Outcomes" with "Lesson Overview", and ensure bullet verbiage matches the layout style guide, for the following Ruby on Rails course sections:
- [x] Introduction
- [x] Rails Basics
- [x] Active Records Basics
- [x] Assets and Navigation
- [x] Forms and Authentication
- [x] Advanced Form and Active Record
- [x] APIs
- [ ] Rails Sprinkles
- [ ] Mailers and Advanced Topics

### Path

Ruby / Rails

### Lesson Url

Example overview section that would need to be fixed: https://www.theodinproject.com/lessons/ruby-on-rails-active-record-basics

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

xsherryhe

**Comment by thatblindgeye** [comment]
@xsherryhe thanks for making this issue! You are right that lessons in the Rails path haven't been updated yet. Eventually we will move onto the full stack paths to make updates similar to Foundations.

I can definitely assign you to this update in the Ruby on Rails course, though! Since there are quite a bit of lessons in that course, it'd be better to make a PR for each section rather than updating everything in one. So a PR for "Ruby on Rails > Introduction section", "Ruby on Rails > Rails Basics section", etc. I updated your original comment to add checkboxes for each section.

Do you want to work on all of those sections, or would you prefer being assigned an issue for one section at a time?

**Comment by xsherryhe** [comment]
Ok, sounds great! I can work on all these sections and I will make a separate PR for each section that I update as I go along.

I won't need to be assigned a separate issue for each section; I'm fine with just updating the checkboxes here. But if it's easier/clearer to have a separate issue for each section, then I'm totally okay with that too. Whatever works best!

**Comment by xsherryhe** [comment]
The Introduction section needs no changes. I submitted PR #25181 for the Rails Basics section. 

(The other closed PR had a forking/upstream repo association error on my part; it can be ignored.)
