### ISSUE TITLE
Computer Science (Ruby & JavaScript): Potentially incorrect information

### ISSUE THREAD

**Issue by DevonTheDeveloper** [TheOdinProject/curriculum#25458]
### Describe your suggestion

There is some potentially incorrect information in step 5 of the assignment in the lesson [Common Data Structures and Algorithms](https://www.theodinproject.com/lessons/ruby-common-data-structures-and-algorithms) in both paths. 

The problem is that there are duplicate nodes in the example of the video, and I think this should be pointed out before people go into the mist with this. Correct me if I’m wrong, but I believe that’s one of the main rules of a Binary Search Tree.

### Path

Ruby / Rails & Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/ruby-common-data-structures-and-algorithms

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

Devon#1910

**Comment by dm-murphy** [comment]
Hi @DevonTheDeveloper 👋 

Thanks for creating an issue and including the details here!

I believe the video is correct. The example is for constructing a binary search tree from an unordered array that includes a duplicate pair of elements. This is a good real world example as often an array can contain duplicate values. The video places the second `7` correctly on the right subtree.

Here's a discussion on this topic from Stack Overflow: https://stackoverflow.com/questions/300935/are-duplicate-keys-allowed-in-the-definition-of-binary-search-trees

There can be different "definitions" or "rules" of what a binary search tree is. It might be easier to understand a BST without any duplicates but it will also be important to know what to do when duplicates are part of an array. This situation might even come up at certain points in the Ruby curriculum.

Personally I've seen a number of BST videos out there and think this is one of the better ones. But interested to hear from others if this seems confusing?

**Comment by wise-king-sullyman** [comment]
@TheOdinProject/ds-a thoughts?

**Comment by CouchofTomato** [comment]
Generally most BSTs used when teaching won't allow duplicate values just because of the additional complexity it introduces, but there are types of BST which allow for duplicate values and either place it to the right, or just keep track of the number of values at that node in the tree.

I guess the question here is does the video introduce too much complexity for what we're trying to teach. Based on what Daniel said it's one of the better videos so I'd rather keep it. Maybe we could add a note where we link to the resource to clarify or something though.
