### ISSUE TITLE
Foundations: Examples of bad and good commits

### ISSUE THREAD

**Issue by CBID2** [TheOdinProject/curriculum#25664]
## Problem 
There’s no code snippets that show how to create a good commit message. As someone who’s currently learning this topic elsewhere, it’s harder to grasp the components of a good commit message when there is no visual aid.

## Possible Solution 
- Add the syntax of a specific commit (preferably a commonly used one) and then provide a snippet where it’s used in a certain situation.

## Possible Benefit 
- Learners, especially coding newbies, will a gain a better understanding of how to create a commit message. It’ll also help them understand the additional resources better.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-commit-messages

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Chrissy

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @CBID2. There are quite a few examples in [the assignment of that lesson](https://cbea.ms/git-commit/)?

**Comment by CBID2** [comment]
> Thanks for the suggestion @CBID2. There are quite a few examples in [the assignment of that lesson](https://cbea.ms/git-commit/)? we'd only be repeating whats in that imo.

Thanks for pointing this out @KevinMulhern. Personally, I think it'd be beneficial to put some of them at the beginning of the lesson instead of the assignment. That way, learners can grasp it earlier on and not click through the lesson feeling confused.

**Comment by KevinMulhern** [comment]
I don't disagree, our preference is to have content on site instead of relying on external resources where possible.

We could include a "Examples of good commits" section between the [Are Commit Messages So Important They Deserve Their Own Lesson?](https://www.theodinproject.com/lessons/foundations-commit-messages#are-commit-messages-so-important-they-deserve-their-own-lesson) and [When to Commit](https://www.theodinproject.com/lessons/foundations-commit-messages#when-to-commit).

Some things we'd like to see in it:
* Example of a bad commit, something simple like "Fix Bug"
* Example of a good commit, basically a summary of the most important stuff in the assignment:
  * Separate subject and body
   * The body should use an easy to understand template the learner can apply to their own projects - I think we use a pretty good [template](https://raw.githubusercontent.com/TheOdinProject/curriculum/main/.github/PULL_REQUEST_TEMPLATE.md) with our TOP repos. We have "Because" and "This PR" prompts to make it easier to write good PR bodies. The same thing can be applied to commits with this.

If you're happy with those requirements, Would you like to be assigned to this @CBID2?

**Comment by CBID2** [comment]
> I don't disagree, our preference is to have content on site instead of relying on external resources where possible.
> 
> 
> 
> We could include a "Examples of good commits" section between the [Are Commit Messages So Important They Deserve Their Own Lesson?](https://www.theodinproject.com/lessons/foundations-commit-messages#are-commit-messages-so-important-they-deserve-their-own-lesson) and [When to Commit](https://www.theodinproject.com/lessons/foundations-commit-messages#when-to-commit).
> 
> 
> 
> Some things we'd like to see in it:
> 
> * Example of a bad commit, something simple like "Fix Bug"
> 
> * Example of a good commit, basically a summary of the most important stuff in the assignment:
> 
>   * Separate subject and body
> 
>    * The body should use an easy to understand template the learner can apply to their own projects - I think we use a pretty good [template](https://raw.githubusercontent.com/TheOdinProject/curriculum/main/.github/PULL_REQUEST_TEMPLATE.md) with our TOP repos. We have "Because" and "This PR" prompts to make it easier to write good PR bodies. The same thing can be applied to commits with this.
> 
> 
> 
> If you're happy with those requirements, Would you like to be assigned to this @CBID2?
> 
> 

Perfect!

**Comment by CBID2** [comment]
> It's all yours, thanks @CBID2 💪 

Thanks for giving me a chance @KevinMulhern
