### ISSUE TITLE
Foundations Course: Incorrect CSS selectors in cascade example

### ISSUE THREAD

**Issue by pebaha-** [TheOdinProject/curriculum#25742]
### Describe your suggestion

Describe your suggestion
Course/Path: Foundations
Section: CSS Foundations
Lesson: The Cascade

The third example in the [Specificity](https://www.theodinproject.com/lessons/foundations-the-cascade#specificity) part of The Cascade lesson in the CSS Foundations section contains CSS where the selectors do not match any HTML element.

Currently the snippet is as follows:

```

<!-- index.html -->

<div class="main">
  <div class="list" id="subsection"></div>
</div>

/* rule 1 */
#subsection .list {
  background-color: yellow;
  color: blue;
}

/* rule 2 */
#subsection .main .list {
  color: red;
}

```

Neither rule 1 nor rule 2 match any of the div elements in the HTML, since they both use **descendant selectors**.

I propose the following changes to make the selectors match while retaining the specificity point of the example:

Adjust the first selector to match both the ID #subsection and the class .list
Adjust the second selector to match both the ID #subsection, the class .main and the class .list

```

/* rule 1 */
#subsection.list {
  background-color: yellow;
  color: blue;
}

/* rule 2 */
.main .list#subsection {
  color: red;
}

```

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-the-cascade#specificity

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by erinsophie** [comment]
Hey, I am doing the Using Git In The Real World lesson atm and would like to fix this issue? :)

**Comment by CouchofTomato** [comment]
@TheOdinProject/intermediate-html-css Thoughts on this?

**Comment by Mclilzee** [comment]
In my opinion going from descendant combinator to chaining selector might confuse the students because this section was before the section that talks about combining special symbols (>, +, ~ and an empty space) that they do not change cascading ruling.

```css
/* rule 1 */
#subsection {
  background-color: yellow;
  color: blue;
}

/* rule 2 */
.main #subsection {
 color: red;
}
```
Would be my go to option, i would also go further and remove the `background-color` property from the first rule, that is because if someone tries this in a playground, they may notice that the background became yellow without realizing the font went red, and may believe that rule 1 is taking precedence over rule 2. 

As a note it already mentions this in the paragraph that follow pointing out that the background becomes yellow that is because rule 2 has no conflicts with that, but rule 2 wins over the red color, so its not a big deal to change that especialy now that you would need to change the pharagraph.

**Comment by pebaha-** [comment]
Good point about sticking to a descendant combinator in this example as the two preceeding examples also use those.

I think keeping `background-color` has value, though. It shows students that rule 1 is still partially applied because there's no conflicts with that specific property.

**Comment by CouchofTomato** [comment]
Feel free to open a PR @pebaha-

**Comment by pebaha-** [comment]
> Hey, I am doing the Using Git In The Real World lesson atm and would like to fix this issue? :)

Would you still like to fix this issue? If so, it's all yours.

**Comment by ManonLef** [comment]
@erinsophie Would you like this to be assigned to you?

**Comment by erinsophie** [comment]
@ManonLef sorry didnt see this, yeah sure!

**Comment by ManonLef** [comment]
@erinsophie you're assigned!
