### ISSUE TITLE
HTML Boilerplate: remove codesnippet from heading

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#25942]
### Describe your suggestion

The "What is the `lang` attribute" heading needs the backticks surroundings "lang" removed so that it renders as plain text.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-html-boilerplate

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by shady54** [comment]
@thatblindgeye  @ManonLef  - Can this issue be assigned to me please. 
Seems I can start with this very basic one, if I understood the issue correctly.

**Comment by shady54** [comment]
@ManonLef - Thank you. Going through the contributing guidelines.

**Comment by shady54** [comment]
@ManonLef -- Due to lack of my knowledge, I just realized while going through guidelines, that I need to clone the forked repo to my local machine. Unfortunately, due to some policy and system restrictions, I cannot do that. And I do not possess any personal machine to work. 
I will have to let go of this issue. Seems, not my time yet, for my first contribution. 

My apologies for the inconvenience, I have caused because of this. 😞

**Comment by janaiscoding** [comment]
Hey, if it wouldn't be a problem that I contributed once before, I would gladly work on this issue 😊

**Comment by TJancenkovas** [comment]
Hello, I'm currently on the "Using Git in the Real World" section. So it would be great to get some practice in on this issue. Thank you!

**Comment by ManonLef** [comment]
@shady54 no problem and no inconvenience caused!

@janaiscoding I'll assign you since you asked first. 
@TJancenkovas maybe you can have a look at the [other good first issues](https://github.com/TheOdinProject/curriculum/labels/Type%3A%20Good%20First%20Issue) they update regularly :)
