### ISSUE TITLE
<React, using Nodejs>: <out of place recommendations>

### ISSUE THREAD

**Issue by OmarNaguib** [TheOdinProject/curriculum#25998]
### Describe your suggestion

![image](https://github.com/TheOdinProject/curriculum/assets/55961349/804e146c-641c-4628-8b5c-120ffa9d3330)

It says:

"For now, just keep in mind that this is something we’ll be discussing in depth later and head over to the next lesson and continue working through the curriculum."

but NodeJs *is* the next thing in the curriculum and not a distant thing in the future

I wonder if this lesson is out of place, or if it means to convey another message.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/react-new-using-nodejs-for-your-backend

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by 01zulfi** [comment]
@theodinproject/javascript can someone take a look please

**Comment by ManonLef** [comment]
While there's one lesson left, I do agree that since the last lesson is just a conclusion, it would make sense to revise this lesson. I considered they could be somehow merged together so it doesn't seem like we have a lesson here on hooking up React to a backend. 

It would be nice to gather some ideas or proposals on this. @01zulfi would you think this is worthy of moving to a discussion or should we open it up to welcome ideas before assigning?

**Comment by 01zulfi** [comment]
Whatever feels best to you @ManonLef

**Comment by ManonLef** [comment]
Would love to hear ideas on this. 

I personally think this lesson can be removed and information transferred to the last lesson. 
Open to other input.

**Comment by wise-king-sullyman** [comment]
+1 to your suggestion @ManonLef

**Comment by OmarNaguib** [comment]
Just letting you guys know i am now ready to work on this if you decide to go through with it.
@ManonLef @wise-king-sullyman

**Comment by ManonLef** [comment]
All yours @OmarNaguib !
