### ISSUE TITLE
Foundations: Prerequisites: Setting up Git: macOS Ventura git installation issue

### ISSUE THREAD

**Issue by fruitsofbabylon** [TheOdinProject/curriculum#26031]
### Describe your suggestion

According to your guideline "MacOS already comes with a version of Git" which is not entirely correct. When I run `git --version` (I decided to check the git state on my computer since I used it before) I get an error. To fix it I ran `xcode-select --install` like in the example of the same issue discussed here: https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a
Only after this fix I could manage to run the command `brew install git` without any errors. 

Link to the line that mentions this:
https://github.com/TheOdinProject/curriculum/blob/cfab4818afbb0e483372a146cddbf73f6c832f9a/foundations/installations/setting_up_git.md?plain=1#L67

I would suggest to add `xcode-select --install` to the installation guidelines to make sure that git is installed without any issues. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-setting-up-git

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

fruitsofbabylon

**Comment by fabulousgk** [comment]
Were you unable to install git without first running the xcode command?

I ask because you are correct that git does not come preinstalled, you have to install xcode or or the cli tools to get it.  But I believe that we get around that with the brew install.

In which case it would seem the better edit would be to remove the reference that it is installed by defualt.

**Comment by fruitsofbabylon** [comment]
Yes, I was unable to install git without this command. 
`brew install git` was failing with this output: `Error: 'git' must be installed and in your PATH!`

**Comment by fruitsofbabylon** [comment]
Note: I didn't install brew itself now because I already had it on my laptop, so I started with `brew install git`

**Comment by fabulousgk** [comment]
This seems to sum up the issues and there can apparently be several, should we link this instead: https://www.programmerhat.com/git-must-be-installed-and-in-your-path/

**Comment by ManonLef** [comment]
Could anyone from @TheOdinProject/installations have a look at this?

**Comment by fruitsofbabylon** [comment]
Well, the last section (Install command line tools in MacOS) in this article helped me a lot and there is a good explanation why I got the error in the first place. I guess to link this article is a great idea!

**Comment by ManonLef** [comment]
I've had a look at this. In [step 1 `installing Homebrew`, it is mentioned to check the requirements](https://github.com/TheOdinProject/curriculum/blob/cfab4818afbb0e483372a146cddbf73f6c832f9a/foundations/installations/setting_up_git.md?plain=1#L55). One of the MAcOS requirements is actually having XCode CLT installed, including the instructions:
![Screenshot 2023-08-04 at 23 10 19](https://github.com/TheOdinProject/curriculum/assets/81025586/483f3d69-f343-418a-9b1e-40043ce3447c)

Thank you for bringing it up! However, since it's already in the official HomeBrew documentation learners are instructed to follow, I will close this for now.
