### ISSUE TITLE
Foundations: Intro to CSS

### ISSUE THREAD

**Issue by housepanther** [TheOdinProject/curriculum#26030]
### Describe your suggestion

In the section called **Order matters!**, kindly consider offering an explanation as to why elements with both the .first-selector and .last-selector would get the .last-selector applied to it. I am brand new to CSS and I am struggling to understand this. I am struggling to figure out specificity. Thank you for your consideration.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-intro-to-css

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### (Optional) Additional Comments

Please keep doing the good work that you're doing.

**Comment by fabulousgk** [comment]
@housepanther I am trying to think how it could be rephrased and need your input.  The text says "When two selectors have the same level of specificity, the rule that is defined last has the most precedence; that is, the last rule overrides any rules before it."

I feel like that is very specific, but at the same time I too had to read that section a couple times to fully comprehend it.  Do you have thoughts on how to reword it?

**Comment by housepanther** [comment]
I think I see where there could be some improvements. I actually did a separate google search to find out what the meaning of the comma is between selectors. It made more sense when I learned that the comma is actually an OR operation. So in the curriculum example, it would read in English as .first-selector OR .last-selector. Once I understood that my thinking was incorrect that the comma was an AND operator, it made sense that the more specific one would be the last on in the listed precedence because not only is it last, but it is specific to that single element. Am I correct in my explanation? Thanks!

**Comment by fabulousgk** [comment]
You bring up an interesting insight.  I wonder why that first section of CSS is in the code example.  Does it need to be?  Perhaps removing that bit and having just the two single selectors would bring some clarification, since the section is about order.

**Comment by housepanther** [comment]
It's possible but we would need to consider a situation in real life where we could see that pop up. I have to wonder if the outcome would change if we did the following:
```
.last-declared, .first-declared {
    background-color: rgb(200, 50, 150);
    font-weight: 800;
}

.first_declared {
  color: rgb(50, 50, 200);
  font-size: 32px;
}

.last_declared {
  font-size: 14px;
  font-weight: 800;
}
````
I am going to test it in VS Code now because I am genuinely curious. :-)

**Comment by housepanther** [comment]
I updated my previous comment. Kindly look it over when you have the chance. Thanks!

**Comment by fabulousgk** [comment]
You did not check the box saying you wanted to take this on, just making sure that is correct.  I am not a maintienter just a part of the community FYI.  Just trying to figure out how I would edit it if I took the issue.

**Comment by housepanther** [comment]
I didn't check the box originally because I wasn't sure how to answer the original question. Now that I kind of know how to word it, yes, I would be willing to take this on.

**Comment by fabulousgk** [comment]
Excelent, one of the maintainers will be along to assign it to you before long!

**Comment by ManonLef** [comment]
Thanks for your issue!

I am currently unsure how this could be enhanced. The basic idea is that when you read the CSS file top to bottom, the bottom one will override any previously styles defined higher up. 

That's what's also mentioned exactly here: 
>  the selector last_declared would override the first_declared selector. Any HTML element with both of those classes would have the styles defined in .last_declared instead of .first_declared.

Watching the discussion up there with the example code, yes that is indeed how it would look in a real situation (both those classes on one element) but that's already described in the above and I'm of the opinion that adding that whole code segment will complicate the lesson by adding even more content. 

I do believe that the best way to gain understanding here, is to indeed have your VSCode open to play around in while grasping the content. Exactly how you did up there. 

For now I will close this issue since I do believe what's explained in the lesson is correct and clear. IF you think of a way to give a better example that would have made it more clear to you from the start, feel free to file a PR :)
