### ISSUE TITLE
Recipes: Enabling Pages on a private repo requires a paid account

### ISSUE THREAD

**Issue by jamieschmid** [TheOdinProject/curriculum#26091]
### Describe your suggestion

You offer the steps to set up pages, but if your repo is private it requires an account upgrade. It is worth mentioning this for people who want to keep their repo private. You do mention there are multiple ways, but adding a note about what the other ways are is helpful.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-recipes

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Additional Comments

Thank you for this wonderful resource, I am utilizing it to teach my niece to code! <3

**Comment by codyloyd** [comment]
You're right about this limitation in Github Pages.  I'm not entirely sure it's worth mentioning in the lesson because as you've noted, it is very clear on the GH website that you either need a paid account or to make your repo public.

I'm not sure it would _hurt_ either.

@TheOdinProject/foundations what do y'all think?

**Comment by wise-king-sullyman** [comment]
I'm not against it as a quick mention.
