### ISSUE TITLE
HTML Boilerplate: Kevin's Video Repetitive

### ISSUE THREAD

**Issue by chrisgford** [TheOdinProject/curriculum#26092]
### Describe your suggestion

I get that we are reinforcing learning, but maybe Kevin's video should be on additional resources as it just goes through the text again.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-html-boilerplate

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by chrisgford** [comment]
Same can be said in other parts of the Foundations course. Maybe the reinforcement is helpful for some, but the Odin Project text is actually giving more advanced information, faster.

**Comment by CouchofTomato** [comment]
@TheOdinProject/intermediate-html-css Thoughts on this?

**Comment by codyloyd** [comment]
I agree to some extent... but I still think some Learners need the repetition and reinforcement.  I might feel differently about it if it were longer, or if this were later in the curriculum, but since it's one of our very earliest lessons I think it's worth watching someone go through all the steps of setting things up for the first time.
