### ISSUE TITLE
Introduction to Flexbox: Errors found in image

### ISSUE THREAD

**Issue by housepanther** [TheOdinProject/curriculum#26137]
### Describe your suggestion

Greetings! In the section named Flex containers and flex items of the Foundations: Introduction to Flexbox lesson, is an [image](https://cdn.statically.io/gh/TheOdinProject/curriculum/495704c6eb6bf33bc927534f231533a82b27b2ac/html_css/v2/foundations/flexbox/imgs/03.png) with two errors on it. The CSS selectors named `.container` and `.item` should have the background-color property instead of background.   

Also, may I recommend introducing the CSS gap property and including links to the [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) and  [W3 Schools](https://www.w3schools.com/cssref/css3_pr_gap.php) documentation on it? It would be useful to offer a little bit of text separate from the image briefly introducing gap and that it is shorthand. Users like myself with disabilities may inadvertently overlook this and the errors in the image link above if they do not try them out in VS Code.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-flexbox

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Additional Comments

Thank you for your time, attention, and all that you do to make Odin a really wonderful learning experience thus far! Please keep up the good work.

**Comment by fabulousgk** [comment]
The gap property is introduced and explained in the alignment module 3-4 lessons later.

The background property is perfectly valid CSS code.

**Comment by housepanther** [comment]
I will buy that I made a mistake about the background property. However, if course content is going to be introduced, it needs to be explained at the time it is being introduced. Since the CSS gap property is being introduced at this point, it should be explained. I have formal experience as an educator and my approach was to never simply introduce a new concept without explaining it there and then, or at the very least, a very basic statement with what it does and explain that detail covering the concept will come later in a curriculum.

**Comment by fabulousgk** [comment]
I think you have a valid observation. I am thinking personally the solution might be to trim that image and remove the CSS part entirely, I am not sure that is needed for that part of the lesson.

We will see what the maintainers say.

**Comment by housepanther** [comment]
I appreciate the time you've taken to read my response. Thank you for taking it in the right stride. :-)

**Comment by housepanther** [comment]
@fabulousgk Do you think you might consider also a brief expalanation of the background property in this section as well because it is introduced there? Thank you again for being so receptive.

**Comment by wise-king-sullyman** [comment]
While (as discussed already) these aren't really "errors" I don't think removing the properties from the example image would be a bad thing, they aren't the focus here anyway.

For that same kind of reason, I don't _think_ we'd want to go into the background or gap properties here or have learners go out and dig into them on their own at this point, I think cropping the image to remove the CSS part as was suggested by @fabulousgk would make sense.

Alternatively, we could update the CSS part and replace `background` with `background-color` and `gap` with `margin` since those properties are already covered.

**Comment by ManonLef** [comment]
@housepanther checking in to see if you've caught the above suggestion/ideas and would like to work on any of those alternatives suggested by @wise-king-sullyman?

**Comment by aconstas** [comment]
@ManonLef 

If this issue is still looking to be closed, I have cropped the image (maintaining the original size) and would be happy to send a PR. :)

![03](https://github.com/TheOdinProject/curriculum/assets/82304192/6ba68bb1-3e56-4685-9ecb-4361180dde3e)

**Comment by wise-king-sullyman** [comment]
@aconstas since we haven't heard back from the issue opener in a while I'm happy to assign you. Thanks!

I would prefer us to keep the CSS in and just change the properties, but if that would be a big problem I wouldn't block a PR over it.

Also if you've never added images to our curriculum before I strongly encourage you to reference our wiki for how to do so, it's a bit confusing.

**Comment by aconstas** [comment]
@wise-king-sullyman Thanks for the heads up! I'll change the css properties and make a PR by the end of the day. Thanks again for letting me contribute!
