### ISSUE TITLE
Javascript Computer Science: Add a brief roadmap/summary on how students can start drilling/studying algorithms for interviews

### ISSUE THREAD

**Issue by joyceawt** [TheOdinProject/curriculum#26147]
### Describe your suggestion

After reading the section on data structures/algorithms I felt like there was a huge gap to fill in terms of how to get started on studying for interviews. While doing my own research on what to do, I actually ended up creating my own PR to help improve on this. I realize the contributing guide says to create an issue before submitting a PR unless it's a simple issue, but I felt this was a pretty simple enhancement that I came up with from my own research and reading people's recommendations.

PR opened: https://github.com/TheOdinProject/curriculum/pull/26146 

### Path

Node / JS

### Lesson Url

https://github.com/joyceawt/curriculum/tree/main/javascript/computer_science

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by wise-king-sullyman** [comment]
Thanks for making this!

I've gone ahead and assigned you since you already have a PR up.

For the sake of clarity: unlike in most cases, this shouldn't be taken as an "approval" of the suggestion. I will leave that decision up to the reviewer of the PR since it's a pretty substantial work.

Also, just a note for the future, once you have a PR up you don't really need to file an issue here, we aren't sticklers about that. I do appreciate that you took the time to do so though 🙂
