### ISSUE TITLE
Factory Functions and the Module Pattern

### ISSUE THREAD

**Issue by rjqocampo** [TheOdinProject/curriculum#26206]
### Describe your suggestion

The linked article from Medium: 3 Different Kinds of Prototypal Inheritance: ES6+ Edition completely lost me. The examples provided contained a lot of jargons for me. 

I got into a rabbit hole trying to figure out what on(), emit(), getters, setters and event emitter are. What is a Backbone-style event emitting model? 

I asked the Discord community for help but they didn't understand it as well. And just advised it's not necessary to dwell on it. It kinda detached me from the current lesson because it's emphasized that it's rewarding to learn. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern#back-to-factory-functions

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by KevinMulhern** [comment]
@TheOdinProject/javascript any thoughts on this?

**Comment by ManonLef** [comment]
I'm very sorry but I'm having a really hard time finding the mentioned article. Could you please link to the section that contains it and include a link to the article itself.

**Comment by wise-king-sullyman** [comment]
@ManonLef I think it's [this one](https://medium.com/javascript-scene/3-different-kinds-of-prototypal-inheritance-es6-edition-32d777fa16c9), but I'd appreciate confirmation from @rjqocampo.

I think this resource is overall quite good, but it does seem a bit complex for where this lesson is. Maybe it would make more sense in a later lesson?

**Comment by ManonLef** [comment]
I think you're right @wise-king-sullyman ! Another reason we need more descriptive links and keep them contained to the assignment section mostly! [This lesson already has an issue assigned for a rewrite](https://github.com/TheOdinProject/curriculum/issues/26225)

I do agree it's lingo heavy. It should be mostly familiar. If it's not required reading material, it could possibly be an additional resource. I'm not sure if it fits any of the later lessons. However, since it does seem like quite a valuable resource, how about adding more specific instructions on what information to focus on and that it's okay if learners don't grasp all the code or methods introduced?

**Comment by wise-king-sullyman** [comment]
@ManonLef that sounds like a plan to me!

**Comment by ManonLef** [comment]
> how about adding more specific instructions on what information to focus on and that it's okay if learners don't grasp all the code or methods introduced?

I'll open it up for someone that would like to propose added clarification through a PR, that way we can review it there

**Comment by ManonLef** [comment]
This lesson is getting a full rewrite and the article will be moved to the additional resources section. I don't think it will need the disclaimer there since people by that point will know that additional resources might go out of scope here and there.
