### ISSUE TITLE
Foundations: An Error in Javascript Basics part of the Course

### ISSUE THREAD

**Issue by bcsamrudh** [TheOdinProject/curriculum#26200]
### Describe your suggestion

An Error in [Javascript Basics](https://github.com/TheOdinProject/curriculum/blob/main/foundations/javascript_basics/fundamentals-1.md) at the Line 97

* As you might have noticed by running Javascript code in the console, the console prints the result of the code it executes (called a return statement). You will learn more about these in the next lessons, however for now it is good to remember that a declaration with an assignment (such as let b = 7 * a) returns undefined and so you cannot declare and assign a value to a variable and read its value in the same line.

Suggested Fixes:
- The code should be: `let b =7*b;`
- It does not return `undefined` but returns an Error: `"Uncaught ReferenceError: Cannot access 'b' before initialization"`

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-fundamentals-part-1

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

bcsamrudh

**Comment by ManonLef** [comment]
![Screenshot 2023-08-23 at 15 25 52](https://github.com/TheOdinProject/curriculum/assets/81025586/ba5d358a-ad10-4cf3-bb7f-70f4d77b014a)

As you can see in the above screenshot, the console returns undefined when you've declared `b` with a value of `7 * a`. You `declare b` but the `value can't be read yet` in the same line.

It is not a mistake, it's noted because in the exercises you will continuously come across this. 
If you need more help with understanding what's happening here, I suggest you join the discord if you haven't already, since people there are generally very helpful :)

**Comment by bcsamrudh** [comment]
![image](https://github.com/TheOdinProject/curriculum/assets/114090255/10964ec0-f362-4b2a-b56b-f0b3ea023cb0)

But this  works!

![image](https://github.com/TheOdinProject/curriculum/assets/114090255/21885b05-007a-4eb8-a153-2abb89bb5f57)
