### ISSUE TITLE
React: Remove API reference from Memory Card project

### ISSUE THREAD

**Issue by phoenixstout** [TheOdinProject/curriculum#26294]
### Describe your suggestion

The second step of the memory card project states, "Take some time to think about the features you want to implement, which components you need, how to structure your application, **and how to get the images from an API**". This is misguiding as the curriculum for Fetching Data In React comes later in the course. In my experience, I faced a lot of unnecessary turmoil because I didn't know how to properly assign async data from the image APIs to my React nodes.

I propose either remove the implication that images should come from an API, or point the student to the [Fetching Data In React Lesson](https://www.theodinproject.com/lessons/node-path-react-new-fetching-data-in-react) that comes later in the curriculum as some guidance.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-memory-card

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

phoenix2u

**Comment by 01zulfi** [comment]
@phoenixstout Thanks for the suggestion. The placement of the fetching data lesson and the API requirement for the memory card project is intentional. In the earlier lessons, learners have had practice with the Fetch API in vanilla JS and learned about `useEffect` and `useState`. We've left fetching in React as an exercise for the learner. Figuring it out can become tricky but it serves as a valuable learning experience, and if they get stuck they are always advised to visit our Discord's help channels for guidance. I'd love to hear your thoughts, thanks

**Comment by ManonLef** [comment]
I will close this as I agree with @01zulfi here. I do agree it would look out of place if following the React section on its own, but learners have experience with fetch requests and setting state. Wrapping this inside a useEffect is covered in the previous lesson. Thanks for opening the issue/suggestion though!
