### ISSUE TITLE
<JavaScript>: too specific instructions for Knights Travails

### ISSUE THREAD

**Issue by OmarNaguib** [TheOdinProject/curriculum#26301]
### Describe your suggestion

This is related to this [discord discussion](https://discord.com/channels/505093832157691914/514204569572605952/1148248156165898250).

1. assignment instructs learners to create a Board and Knight factories/classes.
This isn't needed to solve KT and it doesn't relate to the previous lessons either, I found that confusing and unnecessary.

2.assignment instructs learners to use a specific data structure, that is trees.
it says: "you’ll need to use a data structure that’s similar (but not identical) to a binary tree."

This isn't needed either, but it's related to previous lessons, so I understand that it could be a deliberate choice to restrict learners to use trees for this specific problem.

If it is deliberate then it would be more appropriate to reword  the above quoted instructions.
And if it isn't then the instructions would need to be changed a little.

Here is an [example of a project](https://github.com/OmarNaguib/Knights-Travails) that doesn't create a board or a knight, and doesn't use trees either.

![image](https://github.com/TheOdinProject/curriculum/assets/55961349/35880326-e1ed-49fd-b933-4bf01d073b43)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-knights-travails

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Omar (onsmak) @onsmak

**Comment by Baguirre03** [comment]
I agree. The instructions on this project kind of threw me off, and I think it has for other people too. This definitely is a project that can be somewhat open ended too since the many different ways to solve it.

Simplify this === agreed.

**Comment by rlmoser99** [comment]
Can someone from the @TheOdinProject/ds-a team please review this issue

**Comment by codyloyd** [comment]
re-pinging @TheOdinProject/ds-a

**Comment by ManonLef** [comment]
I think some simplification could be very useful on this project. I personally even made a game board + UI before I realised I misunderstood the assignment. This project can definitely be solved in multiple ways and I've seen many different solutions come by already. 

I also think that picking the search algorithm mention is more important for this project than the mention of it being a tree or not. Especially since when going the tree route, this resembles a non-binary/game-like tree which might be confusing and make a few of the previously learned methods non applicable. 

Since you've indicated you'd like to work on this, I suggest you create a PR and we can discuss your proposal there. Let me know if you'd like to do that!
