### ISSUE TITLE
<overall>: <replace mdn webdocs>

### ISSUE THREAD

**Issue by sfldjkr** [TheOdinProject/curriculum#26335]
### Describe your suggestion

I've been seeing alot of reddits and facing myself about mdn webdocs becomming incompotent and confusing for us beginners to comprehend source and we had to choose alternate ourself...i suggest mdn webdocs should be replaces with beginner friendly docs like javascript.info

### Path

Node / JS

### Lesson Url

null

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by ManonLef** [comment]
Hi there and thank you for your suggestion! I personally disagree with MDN not being the correct choice. It's practically the standard for JavaScript. 

For each lesson, the resources get handpicked by contributors. They usually pick the article they think explains a topic best. This is not just limited to MDN, and you will come across javascript.info resources as well. 

If you however come across an article you think is best replaced by an alternative article, feel free to make a suggestion on the specific lesson and article to be replaced, detailing why you think the switch should happen. You could do this through an issue or a PR. 

Thanks again for your input, I will close this for now since we accept articles of various resources and don't specifically limit ourselves to MDN.
