### ISSUE TITLE
Join the Odin Community: <Short description of your suggestion>

### ISSUE THREAD

**Issue by Gershrom** [TheOdinProject/curriculum#26386]
### Describe your suggestion

The link provided to discord is not working. Does not display channel.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-join-the-odin-community

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

Gershom

**Comment by codyloyd** [comment]
The link is working for me as well.  Are you seeing a specific error?  Can you share a screenshot?

**Comment by ManonLef** [comment]
This seems to be a Discord issue. I have the same issues with not being able to join communities through the invite links at the moment. It merely shows me the list of contacts instead of the server I wish to join. 

What worked for me was copying the invite link from your browser and manually. We can't do anything else about this since our link is working and active as intended. 

![Image](https://github.com/TheOdinProject/curriculum/assets/81025586/0cf6373b-bb2a-4438-b0be-0ea65780273a)
