### ISSUE TITLE
Alignment: Exercise 7 symbol issue

### ISSUE THREAD

**Issue by ryanleslie1997** [TheOdinProject/curriculum#26439]
### Describe your suggestion

A symbol on the webpage on the exercise 7 isn't showing correctly. I will provide a screenshot.

![image](https://github.com/TheOdinProject/curriculum/assets/49491916/9037f8da-8b76-4251-b4ad-9fee0845b612)
![image](https://github.com/TheOdinProject/curriculum/assets/49491916/c5fdda2b-80cc-4c8f-a261-fcc6ff08a816)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-alignment

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

rleslie97

**Comment by ManonLef** [comment]
Hi there, 

it looks like the emojis are not showing up in your html file. This could be due to many things, perhaps your OS settings, VSCode settings, installed system fonts etc.

I can't reproduce this on my end. Perhaps [this google search query](https://www.google.com/search?q=vscode+emoji+not+working&sca_esv=571601278&ei=hK8hZa_4J5TFi-gP3MCIkAs&oq=vscode+no+emoji+&gs_lp=Egxnd3Mtd2l6LXNlcnAiEHZzY29kZSBubyBlbW9qaSAqAggAMgYQABgWGB4yCBAAGIoFGIYDMggQABiKBRiGAzIIEAAYigUYhgNIqjtQAFihL3ADeACQAQCYAXqgAf8KqgEEMTYuM7gBA8gBAPgBAagCAMICCBAAGIoFGJECwgIFEAAYgATCAgsQLhiABBjHARjRA8ICBRAuGIAEwgIOEC4YigUYxwEY0QMYkQLCAgsQLhiABBjHARivAcICBxAAGIoFGEPCAgUQIRigAcICCBAhGBYYHhgdwgIIEAAYCBgeGA3iAwQYACBBiAYB&sclient=gws-wiz-serp) might help you 

![Image](https://github.com/TheOdinProject/curriculum/assets/81025586/40e7eb15-7f64-4ca0-aa51-a73a8d6a0b56)

**Comment by fabulousgk** [comment]
This is a common issue related to a missing font in linux.

**Comment by ryanleslie1997** [comment]
Hi, thanks for the advice guys. I'll check out that link @ManonLef .
