### ISSUE TITLE
Intro to CSS: <the part for chaining of selectors is not clear>

### ISSUE THREAD

**Issue by albani21** [TheOdinProject/curriculum#26442]
### Describe your suggestion

in this part "This syntax basically works for chaining any combination of selectors, except for chaining more than one type selector." to me it does not make sense, it says that you can make any combination of selectors but then it says that except more than one type

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-intro-to-css#selectors

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Additional Comments

thank you for all the work that you all have done and I love the journey so fare.

**Comment by CBID2** [comment]
Can I make this edit @albani21?

**Comment by ManonLef** [comment]
@CBID2 this first has to go through the maintainers. When it's opened up, a maintainer can assign it to a contributor.

**Comment by CBID2** [comment]
> @CBID2 this first has to go through the maintainers. When it's opened up, a maintainer can assign it to a contributor.

Thanks for clarifying @ManonLef

**Comment by ManonLef** [comment]
@albani21 Thank you. This is specifically talking about "type selectors" which refers to selectors that target a specific element like `div` or `p`. The "type selector" is explained a little above the chaining section. This is explained below the sentence you quoted. 

So you can chain a lot of selectors, but not "type selectors", and it then gives an example, a link to "type selectors" and below the code blocks an extra section on *why* `div` and `p` would be causing issues when chaining. 

I don't really have a solution to making it clearer than it's already described. You will often encounter exceptions like this. I will close it since the lesson does elaborate on that exception further along in that header section. 

![Image](https://github.com/TheOdinProject/curriculum/assets/81025586/82a8c195-17d8-402e-aef0-9116d68f315b)
