### ISSUE TITLE
Installing Ruby: Update VS Code Extension Recommendation

### ISSUE THREAD

**Issue by kyledanamarsh** [TheOdinProject/curriculum#26511]
### Describe your suggestion

The VScode extension "Ruby" is deprecated and it's now recommended to use Ruby LSP by Shopify.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-installing-ruby

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by wise-king-sullyman** [comment]
Thanks for making this issue!

Looks like you've already got a PR up for this so I'll go ahead and assign you, though as someone whos been out of the Ruby ecosystem for a while I'm not positive if the change is needed, that will be up to the reviewer of your PR.

Also just so that you know for the future, we don't require issues to be made. If you have a quick change you want to make (and are alright if it's rejected) you can just put the PR up directly.
