### ISSUE TITLE
Time Complexity: Broken link to "Big Omega" knowledge check

### ISSUE THREAD

**Issue by marlatte** [TheOdinProject/curriculum#26742]
### Describe your suggestion

The last link in the "Knowledge Check" section asks _"What is Big Omega and why isn’t it as useful?"_ The link points to `#big-937-omega-notation`, but there isn't anything with that `id` on the page. The closest thing is in the `section#alternatives-to-big-o`, where there's a `h4#big--omega-notation`. I'm guessing it's just a typo, and will be relatively easy to fix, but I wanted to ask if there's a reason behind the number `937` in the link. I don't see any in the other links, or indeed in any other `id`'s.

It looks like there was an attempt to fix this back in March with commit #25184, but that updating links from HTML to MD formatting in May with commit #25455 may have affected this.

Some quick research points to ampersands basically escape anything that comes after them, so the markdown header 
`#### Big &#937; (Omega Notation)` becomes the `id="big--omega-notation"`, effectively removing the number.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-time-complexity

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

Marlatte

**Comment by JoshDevHub** [comment]
Nice spot! This should be fixed. Looks like you should be able to have everything good to go by just changing the `href` so it points to `#big--omega-notation`

Since you've indicated, you'd like to work on this issue, I've assigned it to you @marlatte 

One more thing: would you be comfortable making this same fix for the ruby course's version of this lesson? You can find it [here](https://www.theodinproject.com/lessons/ruby-time-complexity#big-937-omega-notation), and it has the same issue. You won't have to understand or interact with any Ruby code to make the changes. It'll just be the same change you're making for the JavaScript course lesson.

**Comment by marlatte** [comment]
Sure, I can do both node and ruby fixes.

Do you know why the header would have `&#937;` in it in the first place?

**Comment by JoshDevHub** [comment]
@marlatte It's the encoding for the "Omega" symbol's HTML entity.

I don't think there is a good way to eliminate the double dash. It emerges from how the curriculum Markdown documents are parsed into HTML content that's displayed on the site. The parser is strict about what character set it uses to define the heading ids and will strip out characters it interprets as invalid.

In theory this could probably be changed, but I'm disinclined to pursue it because:
1. Changing the parsing logic for this would not be an easy task.
2. The parser does this for a reason. HTML5 doesn't really care about what characters show up in id values, but if the id is to be selected in a CSS rule, then there are restrictions about what characters can be in the id.

So if we want  to have the omega symbol in the heading, it's going to have the double dash.

**Comment by marlatte** [comment]
Sounds good. I've left it as a double dash.

I also noticed that the Ruby markdown had links in HTML format rather than md, whereas the Node course has them in md format (i.e. `[text](url)`). I updated the Ruby ones to match.

Lastly, before I submit a PR, I noticed that the Ruby version has [an extra youtube video](https://www.youtube.com/watch?v=D6xkbGLQesk) in `Additional Resources`. It looks like the examples given are in Ruby, but since some of the other material in the Node course had examples in C/C++, it might be worthwhile to just include the link for Node students as well.

**Comment by marlatte** [comment]
@JoshDevHub any thoughts on that last point about the youtube video?

**Comment by JoshDevHub** [comment]
@marlatte Thanks for asking again! I completely missed your comment last week.

Yeah you can feel free to add that YouTube video to the Node course. He's actually using the Python language there. No reason not to have it in both paths in my opinion.

And yeah, reformatting the knowledge check links to use markdown is a work in progress throughout the curriculum. Some lessons will have that done and some won't. You can include that change in your PR if you want.

**Comment by marlatte** [comment]
@JoshDevHub Great, thanks!
