### ISSUE TITLE
The Cascade: Unclear statement in the specificity section

### ISSUE THREAD

**Issue by loddaa** [TheOdinProject/curriculum#26860]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The current explanation regarding specificity in the documentation has a potentially confusing sentence. The problematic statement is as follows:

> When no declaration has a selector with a higher specificity, a larger amount of a single selector will beat a smaller amount of that same selector. 

Suggested improvement :
> When there is no declaration with a selector of higher specificity, a rule with a greater number of selectors of the same type will take precedence over another rule with fewer selectors of the same type.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-the-cascade#the-cascade-of-css

### (Optional) Discord Name

loddaa

**Comment by JoshDevHub** [comment]
Yeah I agree the wording for how it is currently is awkward. Your suggested change seems like an excellent improvement :raised_hands: 

Since you've indicated you'd like to work on this issue, I've assigned it to you @loddaa 

This isn't a big deal at all, but in the future, when you notice a typo, grammatical error, or wording that could be more clear, feel free to skip straight to submitting a PR with your fix in it. You don't need to make an Issue for these cases.
