### ISSUE TITLE
Asynchronous Code: The promise article by david walsh doesn't seem as a explicit explaination.

### ISSUE THREAD

**Issue by KK-Karan** [TheOdinProject/curriculum#26875]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

 The article is not for a newbie and doesn't explain contents clearly, I would like to propose the article by javascript.info on promises which is a great , easy to understand article about promises.
https://javascript.info/promise-basics

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-asynchronous-code

**Comment by KevinMulhern** [comment]
@TheOdinProject/javascript thoughts?

**Comment by 01zulfi** [comment]
@KK-Karan, thanks for creating this issue.

I think we should keep the David Walsh article. I do agree with the javascript.info article. It could be added in as an assignment item. What do you think?

**Comment by KK-Karan** [comment]
Absolutely, But Still, I don't get any good vibes from David Walsh's article.

**Comment by 01zulfi** [comment]
I'm not sure what you mean by "good vibes". 


Anyways, I'm opening this up for contributions. Please comment below to be assigned.

Acceptance criteria:

- [ ] Add the aforementioned javascript.info article to the lesson's assignment section

**Comment by kamranzafar4343** [comment]
So the previous one needs to be changed with the new article of javascript.info?
This is what you mean?
And how do i do this? The whole article https://javascript.info/promise-basics  from start to end should be copied and pasted into https://www.theodinproject.com/lessons/node-path-javascript-asynchronous-code?
And there's a way or specific template which should be used to copy paste things in Odin project?  
I just have these doubts? 
And i would like to contribute? Can i be assigned!

**Comment by KK-Karan** [comment]
> I'm not sure what you mean by "good vibes". 
> 
> 
> Anyways, I'm opening this up for contributions. Please comment below to be assigned.
> 
> Acceptance criteria:
> 
> - [ ] Add the aforementioned javascript.info article to the lesson's assignment section

We can put the promises article as an alternative to the David Walsh article in the assignment.

**Comment by kamranzafar4343** [comment]
I want to contribute! Can you please assign me!

**Comment by thejoshyee** [comment]
Hi, this is my first time contributing and I would love to work on it. Please assign me if no one else is assigned. Thank you!

**Comment by wise-king-sullyman** [comment]
@01zulfi me and @thatblindgeye were talking over this issue and agree with keeping the David Walsh article, but we do feel like that's putting us over the line of how much content we want in the assignment.

We are thinking about moving the YDKJS promises chapter out of the assignment and to additional resources since it _is_ probably getting a bit more into the nitty gritty of things than people really _need_ to get into.

But then we would be > 5 additional resources so we would want to cut at least one out. In looking at the current resources we really feel like we should probably trim them back quite a bit. 

- The callback article isn't a great fit there since it's mostly covering concepts we cover earlier in the curriculum and we feel that the YDKJS callbacks chapter is already doing that to the extent that we need to.
- The MDN docs we probably don't need to explicitly link to since by this point in the curriculum people should know they can/should use them as a reference.
- The Digital Ocean article doesn't really seem to dig into new content beyond the differences between ES5/6/7, which feels a bit out of scope.
- We also wonder if we could cut the three videos currently being linked to down to one, three additional resource videos with a collective hour in length feels like a _lot_.

So with the above suggestions the acceptance criteria would be:

Acceptance criteria:

- [ ] Add the aforementioned javascript.info article to the lesson's assignment section
- [ ] Move the YDKJS promises chapter from the assignments section to the additional resources section
- [ ] Remove the current first, second, and fourth additional resources
- [ ] Narrow the videos listed in the current third additional resource down to one

WDYT?

**Comment by 01zulfi** [comment]
sounds good to me 👍

**Comment by kamranzafar4343** [comment]
It looks like all things are sorted and i was seeking to contribute. Can i be assigned?

**Comment by kamranzafar4343** [comment]
HI @01zulfi i want to contribute?

**Comment by kamranzafar4343** [comment]
@TheOdinProject/javascript can anyone take a look at here?

**Comment by thatblindgeye** [comment]
@kamranzafar4343 are you still interested in working on this, per the acceptance criteria noted a few posts up?

**Comment by Darknab** [comment]
I'd like to contribute, can you assign me please?

**Comment by kamranzafar4343** [comment]
Yes @thatblindgeye i would like to do that.

**Comment by thatblindgeye** [comment]
@kamranzafar4343 you got it!

**Comment by ParagPalkar** [comment]
I would like to contribute, please assign me as well. 
Thank You !

**Comment by kamranzafar4343** [comment]
@ParagPalkar there is no issue open for help, the last one was assigned to my and now it is ready for review. Head over to issues in curriculum repo and find issues that you can solve. I hope it helps you.

**Comment by thatblindgeye** [comment]
Closed by #27594
