### ISSUE TITLE
Foundations: Add note on the F12 key. Some laptops 

### ISSUE THREAD

**Issue by ojuliocode** [TheOdinProject/curriculum#27012]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Some modern laptops, like Acer ones, have overwritten functions in the function keys (like F12). E.G. mine is a Acer Aspier 5, and in order to open the Inspect, I have to press the key fn + F12. This is not a specific case, due to the fact that a lot of my classmates laptops have this option too (as well as Nitro 5 for example)

Would be an interesting side note to say that in some laptops we would have to do this in order to open inspect panel.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-inspecting-html-and-css

### (Optional) Discord Name

kyokutsuki (or seen as Júlio)

**Comment by 01zulfi** [comment]
@ojuliocode, thanks for creating an issue.

I think it's understood that function keys can alternate commands depending on F lock on various keyboards. The "press `F12`" in the lesson refers to using the `F12` command instead of the alternate command represented by that key. That could require the F lock in certain keyboards. 

[Reference link](https://support.microsoft.com/en-us/topic/how-do-i-use-the-fn-key-f-lock-key-alternate-command-keys-fccfaf23-38f0-88a8-9b44-a18f24523b79#:~:text=Keys%20with%20an%20Fn%20key,keys%20(such%20as%20Redo).)

I'm not sure if this change is required. What do you think?

**Comment by ojuliocode** [comment]
I think that's a good clarification. Might not be required, given what you said

**Comment by JoshDevHub** [comment]
Thank you for understanding @ojuliocode 

Will close this as not planned.
