### ISSUE TITLE
CSS Functions: on desktop version on sidebar lesson content section is missing some section after learning outcomes section 

### ISSUE THREAD

**Issue by kancherish** [TheOdinProject/curriculum#27061]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

in this lesson on sidebar "Lesson contents" section some sub-section are missing there to toggle in lesson which are : What is a function and how are they used in CSS?,calc(),min(),max(),clamp()
p.s.- sorry for bad english not a native speaker

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-css-functions

**Comment by 01zulfi** [comment]
@kancherish thanks for creating an issue.

They don't appear in the contents table because they aren't third level headings. I think they should be.

Please create a pull request to make them third level headings. All you have to do is use three hashes instead of four. https://github.com/TheOdinProject/curriculum/blob/main/intermediate_html_css/intermediate_css_concepts/css_functions.md?plain=1#L29
