### ISSUE TITLE
Importmaps: <Short description of your suggestion>

### ISSUE THREAD

**Issue by mohamed-ali-agourram** [TheOdinProject/curriculum#27074]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

im learning ruby on rails and im on the Importmaps section
i tried this command to pin react and it works fine 
 
 ```
 $./bin/importmap pin react react-dom 
```
 Pinning "react" to vendor/javascript/react.js via download from https://ga.jspm.io/npm:react@18.2.0/index.js
 
 but when i tried
  ```
$ ./bin/importmap pin react --download
```
Couldn't find any packages in ["react", "--download"] on jspm

i searched on the https://github.com/rails/importmap-rails and i didnt found that flag
i guess u dont need anymore to add it bcz it download the package directly via CDN so you need to update this 
 

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-importmaps

### (Optional) Discord Name

aliag_

**Comment by 01zulfi** [comment]
@TheOdinProject/rails-path can someone take a look please

**Comment by JoshDevHub** [comment]
Per [this PR](https://github.com/rails/importmap-rails/pull/217), it just always downloads and vendors the library now, with support for CDNs being pulled.

So you're correct this content will need to be updated.

Acceptance Criteria:
- [ ] Remove mention of CDN usage. This is no longer being supported. Instead the default is the download/vendor method that's shown.
- [ ] Remove the `--download` option from the command to pin packages. Because the default is to download, this is no longer used.

Opening this up for contribution. Anyone is welcome to comment below and be assigned.

**Comment by JoshDevHub** [comment]
Is there any particular reason you closed this as completed @mohamed-ali-agourram ?

The work hasn't been done, and someone still needs to submit a PR that addresses this issue.

**Comment by elhalvers** [comment]
I can work on this : )

**Comment by JoshDevHub** [comment]
Thank you for volunteering @elhalvers 

I've assigned you :+1:

**Comment by elhalvers** [comment]
Sorry for the delay! I will put some time on it this weekend and see what I am able to accomplish! Thanks! : )
