### ISSUE TITLE
Installing PostgreSQL: Unify description of installation sections for Linux/Ubuntu

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/curriculum#27083]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

While the curriculum specifically supports Ubuntu and its official flavours, our instruction sets for it are called `Linux` as can be seen in the [Installations lesson](https://www.theodinproject.com/lessons/foundations-installations#google-chrome-installation) or the [Installing Node.js lesson](https://www.theodinproject.com/lessons/foundations-installing-node-js#installing-nvm). The outlier is [Installing PostgreSQL lesson](https://www.theodinproject.com/lessons/ruby-on-rails-installing-postgresql) where it is called `Ubuntu`. I believe it'd make sense to unify the description of such sections, either by changing `Ubuntu` in the PostgreSQL lesson to `Linux` or changing all references to `Linux` instructions to `Ubuntu` or something of this kind. 

This hasn't been an issue at all ever seems like to me but might perhaps be untidy.

### Path

Foundations, Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-installing-postgresql

**Comment by JoshDevHub** [comment]
Yeah I agree this should change for the sake of consistency.

I think changing the Postgres lesson to say "Linux" makes the most sense. It's the simplest change to fit with the rest of the curriculum, and we support other Linux distributions besides "Ubuntu" (although of course, the ones we do support are ubuntu flavors).

Going to open this up for contributing. Comment below to be assigned. This should also make a good first issue for any first time contributors because it's just changing one word in one lesson.

**Comment by Larsyy16** [comment]
I can do this.
