### ISSUE TITLE
Intermediate HTML and CSS - Default Styles: Revise lesson

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#27126]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I would like to rewrite the Default Styles lesson significantly.  I think there is much room for improvement here, which will help learners better understand resets and their options.

Some thoughts supporting this:

1) I think links to the resets are additional resources, not assignments.  I feel assignments should be activities that actually teach the learner something rather than simply being a resource.
2) I believe, the listed resources are outdated; is Myer really the most popular?  It is out of date, heavy, and makes troubleshooting difficult.  The linked Normalize is no longer being maintained; we should link to the new one.
3) I think we should discuss the idea of teams/learners having their resets developed using these other ones as a foundation but customized for the team/developer.
4) Would it be too much to talk about opinionated vs. unopinionated?  I kinda feel this distinction may be important for evaluating resets and their contents.

I would like to research more up-to-date articles to include in the assignment section and then provide a handful of example sheets in the Additional resources.

I would also like to include a link to a tool I made for visualizing resets: https://fabulousgk.github.io/fabulous-styleboard/

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/intermediate-html-and-css-default-styles

**Comment by wise-king-sullyman** [comment]
@TheOdinProject/html-css thoughts here?

I think I'm on board with most of the suggestions here but would love some thoughts from others before I give a green light, especially those with more CSS knowledge.

**Comment by fabulousgk** [comment]
Small bump

**Comment by ManonLef** [comment]
Maybe @codyloyd can chime in?

**Comment by thatblindgeye** [comment]
I'd agree that a refresh could be nice for this lesson. To respond to some of your points:

- I'd agree with moving the actual resets out of assignments.
- Definitely worth investigating. I wouldn't be surprised if Myer is still the most popular despite the criticisms you mentioned, but still worth seeing if times have changed and there's a new "most popular" one
- 100% think that the lesson should less be "here's some resets to use" with links to them, and more "Here's what a reset is, how it can be used/useful, but don't just use them blindly". Conveying that resets should be a building block to achieve what a user/team needs - rather than a set it and forget it tool - I think would be a good update.
- Maybe depends how it's covered and whether it's really significant enough for the topic.

It'd be great if a lot of this content could be brought more in house rather than primarily linking to articles, too.

**Comment by fabulousgk** [comment]
As to Myer you are probably right, not sure how that makes me feel lol.  Your comment makes me realize the need to include some language about how the various resets and even wether or not to use them is a very subjective and opinonated decision, so learners realize this is a topic where one should absolutely make there own choices and not feel contstrained to something.  IE there is no particular best practice here.

So am I good to start working on something?  I can always do some stuff and then submit a PR for more collaborative editing.

**Comment by codyloyd** [comment]
@fabulousgk I moved this issue to 'in progress' assuming that you're going to begin work on it... if that is not the case, let me know and we can look for other contributors.

**Comment by fabulousgk** [comment]
Thank you, I will start working on it.
