### ISSUE TITLE
A Very Brief Intro to CS: <Change assignment video link to YouTube instead of TED>

### ISSUE THREAD

**Issue by RT44n** [TheOdinProject/curriculum#27232]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The first assignment links to a TED page which has a YouTube video about algorithms embedded in it. I suggest that this be changed to a direct YouTube link instead.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-a-very-brief-intro-to-cs

**Comment by JoshDevHub** [comment]
Makes sense to me.

Since you indicated you don't want to work on this issue, I'll open it up for other contributors. Seems like it'll be a good issue for a first time contributor as well.

### Acceptance Criteria
- [ ] In the JS course's [A Very Brief Intro to CS](https://www.theodinproject.com/lessons/javascript-a-very-brief-intro-to-cs) lesson, change the link href for the `Introduction to Algorithms by David Malan` video to point directly to the YouTube video: https://www.youtube.com/watch?v=6hfOvs8pY1k
- [ ] In the Ruby course's [A Very Brief Intro to CS](https://www.theodinproject.com/lessons/ruby-a-very-brief-intro-to-cs), make the exact same change

Comment below to be assigned this issue.

**Comment by aaronlmjohnson** [comment]
I'd be happy to fix this.

**Comment by JoshDevHub** [comment]
Thank you for volunteering @aaronlmjohnson :raised_hands: 

I've assigned you. Let me know if you need anything or have any questions.
