### ISSUE TITLE
Refs And Memoization: Typo in first assignment description

### ISSUE THREAD

**Issue by EmilyErickson** [TheOdinProject/curriculum#27305]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I believe that there is a typo in the first assignment. Currently it says - "The article [When to useMemo and useCallback](https://kentcdodds.com/blog/usememo-and-usecallback) by Kent C. Dodds further introduces more examples of when to use useMemo and useCallback and why you shouldn’t bother using it."

I think that it is supposed to be "when to use useMemo and useCallback and **when** you shouldn’t bother using it".
The article points out cases that you shouldn't use useMemo and useCallback, but also some cases when you should use them.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-refs-and-memoization

**Comment by MaoShizhong** [comment]
Good catch @EmilyErickson , I agree that `why` can be changed to `when`. 
In fact, `why you shouldn’t bother using it.` should probably be changed to `when you shouldn’t bother using them.` since it's referring to both `useCallback` and `useMemo`.

Since it's just changing 2 words of a sentence, this can be an easy first contribution for anyone. Do let me know if you'd like to be assigned to it at this point, Emily, since it has been 3 weeks since you opened this.

**Comment by EmilyErickson** [comment]
I agree that it would be a great first contribution. I don't necessarily need to be assigned to it since it is such a good first contribution.
Thanks!

**Comment by looonnng** [comment]
Hello @MaoShizhong , Could I get this assigned for my first contribution? Thank you in advance :)

**Comment by MaoShizhong** [comment]
@looonnng Go for it!
