### ISSUE TITLE
New lesson: Generator functions

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/curriculum#27304]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I feel like generators is the one major topic not covered by the JavaScript section. [I've included a draft to how I feel a lesson on generators could be added to the curriculum](https://www.theodinproject.com/lessons/preview?uuid=b0581eb8-fbe7-4bd9-be19-f15142b98200).

### Path

Node / JS

### Lesson Url

Right before or right after Weather App Project

### (Optional) Discord Name

Revenco

### (Optional) Additional Comments

The lesson only includes some basic  concepts about generators, it is possible that we may want to add extra content to the lesson itself such as the mentioned delegation or asynchronous generators. As this is a draft, I included the main idea to get the information across.

In terms of where I'd place it in the curriculum, it would be either before or after weather app. Since asynchronous generators are a big thing, it makes sense to place this lesson in the asynchronous JavaScript section. Generators should definitely come after the learner has been introduced to promises, async/await as the material introduced in the assignment section would heavily build off of existing knowledge of asynchronous JavaScript.

**Comment by MaoShizhong** [comment]
@nikitarevenco A lot of work surely went into this, impressive.

Could you share more about why you believe this topic is something that's valuable enough as a fundamental concept/skillset to warrant inclusion in the curriculum? That is, in regards to the curriculum's aim of teaching fundamental skills and concepts in order to help someone get their first entry level dev role? Additionally considering the types of problems the curriculum will make a learner face during this journey/process?

While certain tools can be powerful in specific scenarios, the value behind them as a whole can greatly change depending on exactly what those scenarios are, what alternatives there are to solving said problems, and how likely an entry level engineer is going to face such problems where awareness of these techniques and concepts are *crucial*.

There are many tools and concepts that are invaluable in their own situations, but TOP intentionally limits what they go into in order to put more focus on the more contextually valuable things and less away from the things which may not be as valuable to dedicate time towards in this context (but of course may well have significant value in other, separate scenarios).

Would be interesting to hear more about your thoughts on this and why you believe this topic is something that learners *should* spend time learning about in relation to TOP's goal.

**Comment by nikitarevenco** [comment]
> @nikitarevenco A lot of work surely went into this, impressive.
> 
> Could you share more about why you believe this topic is something that's valuable enough as a fundamental concept/skillset to warrant inclusion in the curriculum? That is, in regards to the curriculum's aim of teaching fundamental skills and concepts in order to help someone get their first entry level dev role? Additionally considering the types of problems the curriculum will make a learner face during this journey/process?
> 
> While certain tools can be powerful in specific scenarios, the value behind them as a whole can greatly change depending on exactly what those scenarios are, what alternatives there are to solving said problems, and how likely an entry level engineer is going to face such problems where awareness of these techniques and concepts are _crucial_.
> 
> There are many tools and concepts that are invaluable in their own situations, but TOP intentionally limits what they go into in order to put more focus on the more contextually valuable things and less away from the things which may not be as valuable to dedicate time towards in this context (but of course may well have significant value in other, separate scenarios).
> 
> Would be interesting to hear more about your thoughts on this and why you believe this topic is something that learners _should_ spend time learning about in relation to TOP's goal.

Sure, here's my reasoning. 
- Knowing about them can open up new perspective for solving different problems
- It's good to know about the built-in javascript features so you're able to read code if you come across code that uses it. If you don't know what a function with a star is or what yield is, it would certainly be impossible to read the code. And I have had those moments. 
- Shortest way to have the loop implementation and the loop communicate with each other
- Good for iterating over large data sets and memory efficient
- You can make custom iterable objects with them
- TOP already covers pretty much everything about javascript anyways, generators are the only thing it doesn't cover. Would be good for completeness' sake
- Cool syntax (in my opinion)

Feel free to decide against this as I decided to spend time on making this fleshed-out not knowing whether It'll be accepted as a learning exercise about generator functions out of interest, so please I just don't want anyone to feel like I've done unnecessary work.

**Comment by JoshDevHub** [comment]
I'm not necessarily the one most equipped to talk about this specific issue, but I did want to chime in and say that the work you put into the example lesson is really impressive.

In the future, it may be better to have propose a lesson with a more abstract outline or summary rather than a full draft. Would hate for you to feel as if you did a lot of work for nothing if the lesson isn't accepted.

**Comment by thatblindgeye** [comment]
Agreed on the above about generators being cool (idk if I'm rewriting history but I feel like it was one of the more interesting topics to me when reading You don't know JS).

That said, I don't really have much else to add in other than to say I agree with what's been laid out above. The usefulness of generators will be highly dependent on the codebase and what task you're trying to achieve. The answers you can get from "Do you find them useful" can range wildly from "I use them all the time" to "I've never once found them necessary."

If the lesson/project structure was done in such a way that generators would be highly used/required within projects after learning about them, I think then it'd be worth considering their addition to the curriculum. As it is now, though, it's really more of a cool thing I'm personally glad I learned about, but don't think is totally necessary to know within the context of the curriculum.

**Comment by MaoShizhong** [comment]
Since we won't be planning any kind of action based on the reasons shared above, I'll be closing this issue.
Nonetheless, sincerely impressive work for this and I'm sure you learnt a tonne exploring this concept and feature!
