### ISSUE TITLE
ES6 Modules: Unaddressed error experienced when following along with Webpack guides

### ISSUE THREAD

**Issue by djcrago** [TheOdinProject/curriculum#27320]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the "Getting Started" Webpack guide when I first ran "npx webpack" in my cli, I encountered the warning shown below. 

![es6-modules-issue-screenshot](https://github.com/TheOdinProject/curriculum/assets/141692399/f92d77e4-1190-49d6-94a5-2c848074f1cb)

"It's only a 'warning' so it shouldn't break anything. If I NEEDED to address it it would probably say 'error'." I thought, based on my experience with the console in Chrome and how warnings and errors are differentiated there. So I continued following along with the guides.

Eventually when I was supposed to open the 'index.html' file in the 'dist' folder in Chrome to see that everything had been bundled and 'transpiled' from the 'src' folder, I found that it hadn't worked correctly. After attempting to rectify the issue myself (and starting the guides over again to no avail) it eventually dawned on me that the warning I was getting may be the issue. Lo and behold it was.

The warning was telling me that I had not yet specified a 'mode' option, and because of that it was not compiling successfully. I eventually deduced that I needed to specify a 'mode' option in the 'webpack.config.js' file before it would compile successfully.

For the sake of easing any potential frustration or confusion of future users I feel it may be helpful to add a short note, before users follow along with the "Getting Started" Webpack guide, that they may experience this issue, and that the solution is to create a file called 'webpack.config.js' and add the following code shown below.

![es6-modules-solution-screenshot](https://github.com/TheOdinProject/curriculum/assets/141692399/27230eef-5fb7-430d-bb05-579abbe3bb8d)

Adding this file with the code shown above would enable the user to successfully follow along with the "Getting Started" and all subsequent Webpack guides. This in turn would enable the user to successfully follow along with the "ES6 Modules" and "Webpack" lessons. When later guides instruct them to create this same file and add code, users can simply add additional code to the file they have already created.

Thank you for reviewing this request and considering its implementation.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-es6-modules

**Comment by MaoShizhong** [comment]
Step 4 of the [Webpack lesson](https://www.theodinproject.com/lessons/node-path-javascript-webpack) does mention about modes and also provides a way to use one config file with development mode for development (e.g. if using `webpack-dev-server`, and another config file with production mode for when you build to deploy (e.g. when running a build command).

**Comment by djcrago** [comment]
Thanks for the reply! That's good to know that restructuring is being done. Hopefully my issue won't be relevant after that has been accomplished.

I did manage to work through the error until I found a solution (I have already finished the lessons). What I was mostly trying to convey through the issue was that I encountered an error message that wasn't addressed anywhere, and because of that error things weren't working how the lessons and Webpack guides said things should be working. In other words, I wasn't getting the depicted result even though I inputed everything in the same way (I even started over and copy and pasted everything to make sure). This caused me some frustration and I wouldn't want others to experience that same frustration if it could be avoided. I do recognize that not everyone may encounter the same error, but just thought it might be worthwhile to mention it as a note in the lesson in case anyone does happen to experience it. I also recognize however that it may be considered too verbose to include such a notice.

**Comment by MaoShizhong** [comment]
@djcrago Good job getting the issue sorted!

The warning you shared you received in the original post, wouldn't have stopped things from working, as it's only a warning (it automatically sets the mode to `production` but warns you that you didn't set one yourself, which typically would not be intentional). It's still not something that would prevent anything in the lessons from working, and as I said is addressed in the next lesson already.

If, however, you did encounter a different error that actually did prevent things from working as you'd expect, especially if you were 100% certain you had followed the instructions as given, in the future I'd recommend going to the TOP discord community and asking a question there.

That way, people can identify what the issue actually is.

If it was actually an issue on your end (always easy for us to be absolutely sure we did everything right but a tiny typo sets a different option entirely), people can identify that and help clear that issue with you there.

If it's actually some other error, then people can find out why. It could be because you're using a system that's not supported by TOP, in which case that's more reason why people should use supported systems so that the instructions do work as intended. Or if you are using everything supported and there's a genuine issue the curriculum should address, people can confirm that and you can get the right issue raised.

Hope that's helpful going forward?

**Comment by djcrago** [comment]
@MaoShizhong  Thanks for the reply!

That's what I thought! I ignored it because it was only a warning, I guess I mistakenly thought that this must have been the reason things wouldn't compile correctly. I'll close the issue with this comment so that it's not hanging around. Thanks!
