### ISSUE TITLE
Suggestion: Add Optional Reading on Coding Intelligent AI Logic for Battleship Game

### ISSUE THREAD

**Issue by headlessNode** [TheOdinProject/curriculum#27363]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Feature Request: brief description of feature request` format, e.g. `Feature Request: Add a dark mode to the website`
- [X] Would you like to work on this issue?

### Description of the Feature Request

I would like to suggest the addition of an optional reading resource on refining AI logic for the Battleship game. This resource could help people who want to make their AI Intelligent. implementation of AI strategies in the context of Battleship gameplay.

**Article:** https://towardsdatascience.com/coding-an-intelligent-battleship-agent-bf0064a4b319

### Acceptance criteria

- [ ] Ensure that the suggested article provides high-quality content with clear explanations and examples.
- [ ] Confirm that the article is directly related to refining AI logic for the Battleship game and covers relevant topics.

**Comment by JoshDevHub** [comment]
I transferred this from the repo for the main site to the curriculum repo.

This repo (the curriculum repo) is where all of our curriculum content is held in plain old markdown files. This makes it easy for people to contribute to the lesson content without having any specialized knowledge of how a Rails web app is set up. Because your suggestion is related to the curriculum content, I've moved it here.

**Comment by JoshDevHub** [comment]
As for your suggestion itself, I'll defer to our @TheOdinProject/javascript team.

**Comment by thatblindgeye** [comment]
So on the one hand, my thought is that at this point the main intent of the project is practicing unit testing and the article - while interesting - goes a fair bit out scope of that, especially since the article is pretty specific to Battleship (which a user should really move on from once finishing the project).

On the other hand, if we zoom out a bit in the article - focus less on it being specific to a game of Battleship - it could be helpful for gaining an understanding of implementing more intelligent strategy within code.

I feel like I personally lean slightly more towards not including it as a resource post-project, though. Maybe if we include verbiage like, "Coding an Intelligent Battleship Agent covers various ways to implement a smarter computer opponent in a game of Battleship. While you should not attempt to implement this logic in your own project (continue through the curriculum instead), it can be an interesting read if you can abstract the basic ideas to help you think through implementing algorithms and strategy in general."

Or something to that effect, but even then it's iffy for me.

**Comment by fabulousgk** [comment]
Just as a historical point, we recently removed any mention of AI in the tic-tac-toe lesson because it was too advanced for that point, and because far to many learners got stuck working on it.

It seems anytime we mention a possible upgrade, many many people will take that to be part of the assignment.  So we need to carefully weigh priorities in the lesson.

**Comment by headlessNode** [comment]
Your point about learners getting stuck on perceived upgrades is well-taken. 

I believe this AI implementation is more feasible than advanced techniques like minimax. To address this, we could offer clear guidance in the lesson, highlighting that the AI implementation is optional. We could also advise users to refrain from utilizing, the Probabilistic Strategy outlined in the article.

**Comment by 01zulfi** [comment]
@headlessNode Thanks for opening the issue.

I'm skimming through the linked article. I feel it's beyond the scope of our curriculum.

**Comment by thatblindgeye** [comment]
Based on the comment above plus my previous comment, I feel we should close this out as something we don't plan to implement at this time. Appreciate wanting to provide a resource for users on AI for Battleship (which _could_ be abstracted to just AI in general), but it is quite a bit out of scope even as an "extra credit" sort of concept. We can always reopen this if others feel differently or it does end up being more beneficial than it currently seems, but in the mean time if this is something a user is super passionate/serious about, it seems better for those users to research it themselves.
