### ISSUE TITLE
Recursion: Merge sort solution in linked Wikipedia

### ISSUE THREAD

**Issue by thomasmcinnis** [TheOdinProject/curriculum#27392]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Problem
There is a version of merge sort in pseudocode on the linked Wikipedia page that makes solving the assignment trivial.

### Context
There was recently a closed issue #27224 about the C-like version of merge sort on the linked Wikipedia page. But this issue and the change appears to be unaware there is also a [highly verbose pseudocode example](https://en.wikipedia.org/wiki/Merge_sort#Top-down_implementation_using_lists) of merge sort  further down the page which can be almost directly translate to JS.

In my own case reading through the wikipedia article and this pseudocode made writing a JS version trivial. I did not have to wrestle with the problem and figure out how to tackle it.

I am not sure if that matches the learning intent of the assignment, or perhaps this was added to the wikipedia page subsequent to this course module, or perhaps it is not the goal to have learners dig in to solve this assignment.

### Action
There are two courses of action **_if_** this is worth addressing:
1. Remove the link to wikipedia if the pseudocode version is judged to undermine the learning goal; or
2. Refer learners to ignore the C versions in favour of the pseudocode if it is considered supporting the learning goal.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-recursion

### (Optional) Discord Name

latch909

**Comment by JoshDevHub** [comment]
Yeah I didn't notice that pseudo code last time I looked at this.

At this point I think we can probably just pull the wikipedia link because it's been kind of troublesome. People find the C/C++ code confusing, and then if we tell people to not read that, they may read the friendlier to translate pseudocode.

There's no shortage of explanations on that page (I really like the CS50/David Malan one), so I think it's probably fine to just take down the link.

I'll assign this to you.
