### ISSUE TITLE
More On State: <Short description of your suggestion>

### ISSUE THREAD

**Issue by bwu95** [TheOdinProject/curriculum#27419]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Rather than setState being a general name for the state setter function, using appropriate names like setPerson/setValue etc. may provide more clarity and understanding. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-more-on-state

### (Optional) Discord Name

b.wu_

**Comment by mohammednumaan** [comment]
In my opinion, _setState_ is appropriate being a general name for the state setter function. Setting a 'general' name for the state function such as _setPerson_  doesn't make sense because it is specific to that **particular** state's name (i.e Person in this case).

It could be renamed to _set<stateName>_ though.

**Comment by wise-king-sullyman** [comment]
I'm not opposed to instances where we're talking about specific examples being updated to use the setter name used in that example, but I would like to keep `setState` as the name used when we're just talking about the setter function generally since that lines up with what most other resources (including the React docs) use for that purpose.

**Comment by MaoShizhong** [comment]
While the React docs use the term `setState` a lot to refer to that function, I think it might be beneficial to just remind the learner what `setState` refers to in the `More On State` lesson.

The previous lesson itself does not use the specific term `setState` function anywhere, and the `More On State` lesson starts using it directly without any clarification.
e.g. 
> According to React documentation, we should treat state as if it was immutable. In order for us to change state, we should always use the `setState` function.

Then the immediate example does not have `setState` anywhere but rather `setPerson`. Perhaps it wouldn't hurt to remind what `setState` e.g.
> According to React documentation, we should treat state as if it was immutable. In order for us to change state, we should always use the `setState` function which in the case of the below example, is the `setPerson` function.

**Comment by wise-king-sullyman** [comment]
Good callout, I'm definitely not against adding a reminder/clarification on it!

**Comment by cakegod** [comment]
I can work on this.
