### ISSUE TITLE
Function Basics: Link name needs to be updated

### ISSUE THREAD

**Issue by crasion528** [TheOdinProject/curriculum#27414]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The link name `Fundamentals Part 1`  at the top of the `Assignment` section may need to be changed to `Variables and Operators` to reflect the update to lesson titles and to prevent confusion.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-function-basics

### (Optional) Discord Name

crasion528

### (Optional) Additional Comments

If it's a simple HTML fix I would love an opportunity to wet my toes and have this be my first contribution!

**Comment by JoshDevHub** [comment]
Yeah this should definitely be fixed. Nice spot @crasion528 

> If it's a simple HTML fix ...

It is a simple fix, but our content is held in Markdown files rather than HTML. So in this repo, if you navigate to `foundations/javascript_basics/function_basics.md`, you'll see the file for this particular lesson. You'll need to update the link on [line 42](https://github.com/TheOdinProject/curriculum/blob/main/foundations/javascript_basics/function_basics.md?plain=1#L42).

I'll assign you to work on this. Let me know if you have any questions.

**Comment by crasion528** [comment]
@JoshDevHub I don't know what to do now that someone requested changes.

**Comment by JoshDevHub** [comment]
Looks like you got it figured out @crasion528 

Congratulations on your first contribution :tada:
