### ISSUE TITLE
Building Your Resume: Broken Link

### ISSUE THREAD

**Issue by LaythAlqadhi** [TheOdinProject/curriculum#27460]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The link to [This Career Tool Belt article lists 6 free resume builder websites](https://www.careertoolbelt.com/5-best-free-resume-builder-websites/) seems to be down.

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/node-path-getting-hired-building-your-resume

**Comment by jsspen** [comment]
The http version of the URL works and redirects to https://alisondoyle.com/, which appears to be a broken "parked" landing page. Looks like [Alison Doyle](https://muckrack.com/alison-doyle/articles) was the person behind careertoolbelt.com though they hadn't posted anything new there since October. They don't list the Career Toolbelt anywhere on their (active) [LinkedIn profile](https://www.linkedin.com/in/alisondoyle/) and seem to be publishing elsewhere now. I don't think it's coming back.

Instead of removing the link I've just replaced it with an archived copy from the Internet Archive and opened a PR [here](https://github.com/TheOdinProject/curriculum/pull/27463).
