### ISSUE TITLE
Calculator: Reword an exercise in the Extra credit section

### ISSUE THREAD

**Issue by T0nci** [TheOdinProject/curriculum#27485]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Remove everything after the first sentence for the last bullet point for Extra credit - "Add keyboard support".

After a discussion with Mao and Scheals on Discord 7 days ago, they said that everything after the "Add keyboard support!" sentence might be aimed at a problem for the Mozilla browser. As only Chrome is supported in the curriculum up to that point, I thought it would be appropriate to open an issue for this.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-calculator

### (Optional) Discord Name

T0nci

**Comment by MaoShizhong** [comment]
Can confirm that an event listener listening for `/` keypress in Chrome has no default behaviour to prevent, certainly not in the context of the calculator project. But in Firefox, hitting `/` will also bring up the quick find menu.
Since the curriculum recommends and only supports Chrome, the inclusion of this default behaviour prevention note will very likely cause more confusion when people aren't sure whether something was supposed to be "wrong", as was the case with this learner. So I agree it no longer makes sense to mention it.

@T0nci Assigning this to you as you checked that you wished to work on this :)

**Comment by T0nci** [comment]
@MaoShizhong 
Another problem arose while looking at this issue. 

In the Library Project in the Javascript section, it is mentioned that we should be familiar with event.preventDefault() because of the Calculator project's bonus section.

This problem is located both in the Full Stack Javascipt path and the Ruby on Rails path. Should I try to resolve those problems with this issue or open up more issues?

**Comment by MaoShizhong** [comment]
@T0nci Good shout. Yes, I think this would be sensible to include in the same PR as they are directly related. If you can reword that bit in the Library project file to not mention the calculator project and introduce `preventDefault` for the first time, that'd be great.

Both pathways use the same `.md` file for that lesson so you'll only need to change this in one place.

**Comment by T0nci** [comment]
I completed the changes and opened a PR. This is my first time contributing :D

I'm scared a bit if I have messed up some because I haven't reached the Intermediate Git section so I didn't know 99% of the git commands I was entering.
