### ISSUE TITLE
Fetching Data In React: Add resource to Assignment/Additional Resources section

### ISSUE THREAD

**Issue by dziubenzo** [TheOdinProject/curriculum#27505]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I would like to suggest adding the following article to the Assignment/Additional Resources section (preferably Assignment):

https://www.developerway.com/posts/fetching-in-react-lost-promises

It's a follow-up to the 2nd Assignment resource and deals with race conditions. It contains very digestible examples, and it was a very good read in my opinion.

However, it mentions useRef(), which is covered later in the curriculum, but that's just one way of solving race conditions, and there are others.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-fetching-data-in-react

### (Optional) Discord Name

dziubenzo

**Comment by JoshDevHub** [comment]
Thank you for making this issue/suggestion.

I'm not much of a react person, so I'm going to tag our @TheOdinProject/react team and get their thoughts on this.

**Comment by MaoShizhong** [comment]
@dziubenzo Thanks for opening this issue.

I don't think the article adds a *huge* amount more than how race conditions and AbortController are covered in the first assignment article, other than some admittedly very nice diagrams.
Since we only have a single additional resource, I don't think it'll be an issue to add the suggested resource there, along with a note to not worry about the `useRef` part since that will be covered later on. The latter two options (primarily AbortController) are more appropriate IMO anyway.
Perhaps this article coming from a different angle with some good diagrams might help some others poking around the AR section.

Assigning this to you @dziubenzo

**Comment by mathdebate09** [comment]
Hey @MaoShizhong, this issue seems to be stale. I would like to work on it. Could it be reassigned to me?
We could perhaps wait for some time after this comment, in case the previous assignee responds.

**Comment by MaoShizhong** [comment]
@dziubenzo checking in to see if this is still something you wish to work on.

**Comment by dziubenzo** [comment]
> @dziubenzo checking in to see if this is still something you wish to work on.

I'll be able to work on the issue in approx. two weeks once I'm done with the Odin-Book project. Sorry for keeping it on the back burner, but I'm really focused on finishing TOP and learning, and it is taking me much more time than I thought. If this matter is something urgent, I have nothing against assigning the issue to @mathdebate09.

**Comment by MaoShizhong** [comment]
No worries, thanks for getting back to us! Since this is just adding an additional resource and not an urgent matter, I'll leave you assigned @dziubenzo and you can get to it when you can. 

Let us know if you run into any issues along the way.
