### ISSUE TITLE
NodeJs Inventory App: Clarify that link is raw code

### ISSUE THREAD

**Issue by jwaddell10** [TheOdinProject/curriculum#27501]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### Describe your suggestion

In step 4 there is a link [Download the file here](https://raw.githubusercontent.com/hamishwillee/express-locallibrary-tutorial/master/populatedb.js) that opens a page that contains raw code. I think it'd be helpful to clarify that this is not a typical website and it's just raw code, that way learners are aware and don't think it's a bug they need to fix. 

`Download the file here (note: this is just raw code, not a full website)`

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-inventory-application

**Comment by cakegod** [comment]
As I have mentioned previously on Discord, I personally had no problems with this, and you are the first person I witnessed experiencing this issue. So I think we don't really *need* to add this mention.

**Comment by MaoShizhong** [comment]
I agree that I'm not sure I see the necessity behind this suggestion, and I have also not come across anyone previously who had similar confusions/uncertainties.

The link takes you to the exact same link that the MDN Local Library tutorial part 3 gives you (the raw code) and tells you to download (or otherwise create manually), and I feel the wording is sufficiently unconfusing in general.

Of course, if multiple people seem to have the same confusion, then this might be something to look at improving.

I'll leave the issue open a few days to see if anyone else (maintainer or not) has any opinions/insight on this.

**Comment by MaoShizhong** [comment]
Closing as no further responses and no action planned.
