### ISSUE TITLE
How This Course Will Work: Add section on tools that are not covered

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/curriculum#27522]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I see so many folks coming into chat and saying stuff like 'Why does TOP not cover typescript/tailwind/svelte/pikachu/whatever', and also many people getting distracted from progressing in the course as they get sidetracked into learning some technology.

I think it would be very useful to add a section to this lesson related to this. I'm making a bullet point list of things Id put into the section

### Do you cover X technology?
- Once you complete TOP you should be comfortable enough to learn any skill by reading the documentation
- It is most important to master fundamentals instead of learning how to do a bunch of technologies
- Often times people who have 20 technologies on their profile can't do basic things because they spread their time and effort instead of focusing on mastering the fundamentals 
- The skills you learn from this curriculum are transferable. Once you become really good at one language, learning other languages will be only a matter of learning the syntax.
- It doesn't matter which language you do - what matters most is that you stick with your choice, because jumping around is unproductive
- The course is designed to get you into a position where you can apply for a job as quickly as possible. It does not cover things you don't need to accomplish this goal

Of course, this is just a list and if I were to make a PR I'd properly put all those into sentences and paragraphs. Just wanted to ask everyone what they think about this.  

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-how-this-course-will-work

### (Optional) Discord Name

Revenco

**Comment by MaoShizhong** [comment]
I personally like this idea. While the main things like CSS frameworks/preprocessors and TypeScript are already addressed in the most relevant lessons, they do require someone to actually reach those lessons to find out TOP's stance and recommendation. So adding that to "How This Course Will Work" makes sense to me as an "expectation setter", with the above specifics kept in their lessons as reminders when more relevant.

I won't assign this yet, as I'd love to hear other opinions from the team first. @TheOdinProject/foundations 

A couple of opinions about the draft proposed text to note:
- I'm not a fan of using the word "master" for anything in the curriculum. Lots of people like to use that word/"aim" for it but it's not realistic and can definitely bring in unrealistic expectations. Many highly experienced people in any field are also reluctant to ever use the word "master" to describe their experience with those things too.
- I'd make a point not just about "getting good at one language and learning other languages" (in the 4th bullet you have) but applying it to any tools in general too (e.g. React vs Svelte vs Vue etc. - exact same principle applies).
- I'm hesitant about the phrasing `apply for a job as quickly as possible`. I don't think the goal is "as quickly as possible". That's a little *too* generic/extreme IMHO. It's more to focus on the stuff that's actually valuable for achieving that goal, whenever that is, and less or even no focus on the stuff that just won't be so valuable. e.g. The specific tool used doesn't matter, hence it doesn't teach multiple. It only teaches one because the valuable thing is exposure and experience with the fundamental concepts. While teaching only one will be quicker than teaching multiple, that's a byproduct and not the primary focus, which is the value for getting employed.

**Comment by thatblindgeye** [comment]
Just to clarify, this isn't so much adding content saying "TOP does not cover XYZ technologies for ABC reasons", correct? It's more about adding some verbiage that should help temper user expectations/questions about why TOP doesn't cover every single thing without actually listing the things TOP does not cover?

From what is laid out about it sounds like a good idea to me. One concern I guess is whether it fits in the "How this course will work" lesson. To be fair, this particular lesson is kind of trying to be an intro to both the Foundations course and the curriculum as a whole. The structure of the curriculum may be a little confusing as well. Technically we have the structure of **Curriculum** > **Path** (Full Stack JS) > **Course** (Intermediate HTML and CSS) > **Section** (Intermediate HTML Concepts) > **Lesson** (Emmet). Foundations is odd, though, in that it's sort of a path and course at the same time.

So some questions that come to mind:

- Do we need a "How this course will work" lesson that briefly explains what the course covers?
- Should the lesson instead be renamed "How this curriculum will work"? Or does linking to our About page make that sort of redundant?
- Should an additional lesson be added for "How this curriculum will work", then scope both of these lessons appropriately? Has the same question about redundancy as above.

I wouldn't be opposed to adding this info to the existing lesson to be clear, just thinking out loud to see if there's further discussion to be had. I wouldn't hold this work up over something that may be a lengthier, async discussion, especially since we can always yank the added content out and move it if needed.

**Comment by MaoShizhong** [comment]
Definitely agree on the latter points being a further discussion down the line as opposed to something this issue can address now. Also agree on the clarification that we don't want to be mentioning specific technologies and why we don't teach them for XYZ reasons in such content, but to rather temper expectations and explain the pedagogy/teaching philosophy.

**Comment by nikitarevenco** [comment]
> Just to clarify, this isn't so much adding content saying "TOP does not cover XYZ technologies for ABC reasons", correct? It's more about adding some verbiage that should help temper user expectations/questions about why TOP doesn't cover every single thing without actually listing the things TOP does not cover?
> 
> From what is laid out about it sounds like a good idea to me. One concern I guess is whether it fits in the "How this course will work" lesson. To be fair, this particular lesson is kind of trying to be an intro to both the Foundations course and the curriculum as a whole. The structure of the curriculum may be a little confusing as well. Technically we have the structure of **Curriculum** > **Path** (Full Stack JS) > **Course** (Intermediate HTML and CSS) > **Section** (Intermediate HTML Concepts) > **Lesson** (Emmet). Foundations is odd, though, in that it's sort of a path and course at the same time.
> 
> So some questions that come to mind:
> 
> - Do we need a "How this course will work" lesson that briefly explains what the course covers?
> - Should the lesson instead be renamed "How this curriculum will work"? Or does linking to our About page make that sort of redundant?
> - Should an additional lesson be added for "How this curriculum will work", then scope both of these lessons appropriately? Has the same question about redundancy as above.
> 
> I wouldn't be opposed to adding this info to the existing lesson to be clear, just thinking out loud to see if there's further discussion to be had. I wouldn't hold this work up over something that may be a lengthier, async discussion, especially since we can always yank the added content out and move it if needed.

I think that having separate lessons for how the Curriculum will work and how Foundations will work is a good idea. 

From a quick glance, every paragraph in the lesson is either related to TOP itself or Foundations. It would be trivial to split these into two lessons.

The about page gives a general overview of TOP, but doesn't really go into the details. So I'm not sure if linking to it would be enough. The introduction lesson has over a dozen paragraphs explaining exactly what Odin Project as a whole will be like and gives a really solid overview of the entire course.

The foundation part of the lesson and the curriculum are isolated enough that it would _make sense_ for them to be split up.

**Comment by CouchofTomato** [comment]
@MaoShizhong @thatblindgeye Is there any other input before we take a call on how to move this forwards?

**Comment by MaoShizhong** [comment]
@CouchofTomato From me, not much more than shared above. I do feel a lot of this coincides with how Carlos had previously shared about the curriculum philosoohy and goal on Discord. Let me know if you need me to ping you in the thread if you don't know what I'm referring to.

**Comment by thatblindgeye** [comment]
Not really from me either. @MaoShizhong what do you think the criteria for this should be based on the conversation thus far? Just a section ("Why we don't cover certain technologies" or something) and a blurb/list of explanations similar to what nikita posted above? Any particular you think should/shouldn't be included?

>

**Comment by MaoShizhong** [comment]
@thatblindgeye Are you feeling that this change should also rename or split out a "How This Curriculum Will Work" lesson from "How This Course Will Work"? Or are you feeling more for now just potentially amending the current lesson to include some of the proposed info?

**Comment by MaoShizhong** [comment]
Then I'd feel a "Why we don't do XYZ" kind of section would be sensible.
I feel such a section should
- emphasise what TOP aims to do, as well as what it isn't/doesn't try to do
- avoid absolute terminology regarding personal things, like "you will ..." but instead prefer terminology like "you likely will ..." since TOP offers no guarantees - it's down to the individual to use TOP
- avoid terminology like "master" that can offer unrealistic expectations
- avoid mentioning speed/timing, only quality of productivity if absolutely necessary for a point

**Comment by nikitarevenco** [comment]
> Then I'd feel a "Why we don't do XYZ" kind of section would be sensible. I feel such a section should
> 
> * emphasise what TOP aims to do, as well as what it isn't/doesn't try to do
> * avoid absolute terminology regarding personal things, like "you will ..." but instead prefer terminology like "you likely will ..." since TOP offers no guarantees - it's down to the individual to use TOP
> * avoid terminology like "master" that can offer unrealistic expectations
> * avoid mentioning speed/timing, only quality of productivity if absolutely necessary for a point

That sounds like a good idea. I'm happy to work on a first draft

**Comment by thatblindgeye** [comment]
Sounds good to me, @nikitarevenco assigned

**Comment by nikitarevenco** [comment]
Rough, rough draft there!
