### ISSUE TITLE
CV Application: Remove Netlify as a recommendation

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/curriculum#27533]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

So I just found out that netlify [sent a huge bill to a customer](https://codestitch.app/news/netlify-charged-user-100k). Personally, I did some research and from now on I won't consider using netlify for myself. Don't want to dive into the politics of all of this, just wanted to know other people's opinion if netlify should be removed as a recommendation from the project page.

There are many other options. Just putting this out there

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-cv-application

### (Optional) Discord Name

Revenco

**Comment by JoshDevHub** [comment]
@TheOdinProject/react thoughts on this one?

**Comment by MaoShizhong** [comment]
Removing it from the curriculum feels a little too close to a rash/impulse decision for me. I'm well aware that some people will personally prefer to not host via Netlify in the future due to this, but at the same time the circumstances that led to that person's issue were rather extraordinary and something that's highly unlikely to happen to someone else, certainly within the curriculum (that person's site hosted a fairly large file which was then also DDoSed in a way that bypassed Netlify's own DDoS protection systems).

Vercel's documentation also shows the exact same process of "100GB/month free tier bandwidth where we don't automatically shut down the site if this is hit", but you can configure a spend limit on your account.

If anything, this incident will only make Netlify add more protections. The bad rep was primarily from their response to the incident. Instead of forgiving it there and then, which likely would have resulted in minimal (if any) backlash, their response wasn't the most "sensible".

So I don't think it necessarily should be removed. And if you're to add your credit card to any hosting service, you 100% should read the T&Cs to understand exactly how it will work regardless. AFAIK, Netlify doesn't require a credit card upon signup anyway.

**Comment by MaoShizhong** [comment]
Closing as no action is planned for this.
