### ISSUE TITLE
Introduction To React Testing: Remove Section on synchronous userEvent.click method

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/curriculum#27561]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

So I'm currently on the Testing React lesson, and I was confused why this information is needed for the learners - specifically the fact that `userEvent` used to use synchronous `click` method. If the lesson introduces the right way to test for user event clicks - then I don't really see a reason to include that in the past the `userEvent.click()` *used* to be synchronous. It shouldn't matter - what should matter is how to do it correctly **now**, which is what the lesson goes into.

So, I think it may be worth to remove this segment from the lesson. 

---

It’s worth noting that some examples from other resources or tutorials might still use the synchronous userEvent.click() method
```javascript
// This is the old approach of using userEvent.
it("renders radical rhinos after button click", () => {
  render(<App />);
  const button = screen.getByRole("button", { name: "Click Me" });

  userEvent.click(button);

  expect(screen.getByRole("heading").textContent).toMatch(/radical rhinos/i);
});
```
The setup() is internally triggered here. This is still supported by React Testing Library to ease the transition from v13 to v14.

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-react-testing

### (Optional) Discord Name

Revenco

**Comment by MaoShizhong** [comment]
@nikitarevenco Thanks for opening this.

This was definitely a little more relevant when the revamped course was released but since some time has passed, I agree that we wouldn't need to write as much about the old way. I think since the change isn't a *very* recent one anymore, at this point I'd want to trust that learners would be able to check dates on SO answers/resources and compare against documentation/these lessons (or in some other way query the issue and discover things are no longer synchronous but asynchronous).
