### ISSUE TITLE
Misspelled 'panels' as 'panes'

### ISSUE THREAD

**Issue by RoaaK95** [TheOdinProject/curriculum#27570]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There is a typo in ' Inspecting HTML and CSS section - foundation course ' 
'panels' is written as 'panes'

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-inspecting-html-and-css

**Comment by JoshDevHub** [comment]
Thank you for making this issue.

I didn't think this would be something to fix, because "pane" is a word in English, and it can often be considered synonymous with "panel." But the chrome dev tools documentation consistently calls them "panels", so I think it's probably nice to stay consistent with their terminology.

Since you indicated you don't want to work on this, I'll open it up for other contributors. This should be one that's good for first time contributors :smiley:

### Acceptance Criteria
- [ ] In the [Inspecting HTML and CSS lesson](https://www.theodinproject.com/lessons/foundations-inspecting-html-and-css), change the 4 instances of the word "pane" to "panel".

Comment below to be assigned.

**Comment by carson-evans** [comment]
This sounds straightforward I would like to be assigned please.

**Comment by JoshDevHub** [comment]
Sure thing @carson-evans. I've assigned you.

**Comment by cakegod** [comment]
It's weirdly not that consistent. I've seen both terms used in the Chrome Dev Docs.
