### ISSUE TITLE
React Router: Overhaul lesson and split into 2 lessons

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/curriculum#27585]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I was trying to do this lesson and I encountered an issue. I was trying to find answers online but every single place I've looked was using the `createRoutesFromElements` function. After looking into it, I rewrote my entire routing using this new function and it ended up cleaner and working.

For some reason using this over using the object pattern taught in the lesson just conceptually makes more sense. Not only this, but learners will be able to find help online far easier if they were to use this function. I would rewrite the lesson so that it uses `createRoutesFromElements` in `router`. 

I also feel like the lesson will benefit from teaching about Loaders, which are a way to fetch data from a server without having to use `useEffect`. This just makes life easier rather than having to use a `useEffect` with an empty dependency array `[]`, and an async function *inside* that effect, we can just say: `const data = useLoaderData()`. 

The `<Outlet>` component is already super useful, and I think that also needs to be included.

If the ideas are accepted, perhaps it'll be better to split this lesson into two lessons, in its current form its already huge and with this extra content I think it will be too much

Let me know what you think about this! 

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-react-router

### (Optional) Discord Name

Revenco

**Comment by MaoShizhong** [comment]
My experience going through this section before was that the lesson material, the provided documentation for React Router, as well as all my searching/question asking in the server meant the current way taught using route objects in an array (which is the way that's demonstrated in the docs themselves) was perfectly sufficient. I personally had no troubles with researching and finding resources for my problems that demonstrated using route objects instead of Route components within `createBrowserRouter`. Similarly, I have not encountered much issue at all in the community regarding this matter, and the vast majority who have issues with router-related matters I've come across, have had issues understanding other aspects (i.e. not highlighting route objects vs Route components as a significant issue in their understanding/own research).

Some older resources may have used Route components because in older versions of React Router (which is why it's important to check the (and if necessary, search by) date of a resource/answer), `createBrowserRouter` did not exist and the method of creating a browser router in those older versions was to use a `<BrowserRouter>` component that did actually need `<Route>` components as children of it.

The React Router docs highlight `createBrowserRouter` as the current preferred way to create one due to API compatibilities with older methods. Since the docs themselves use an array of route objects, it makes sense to follow the documentation's examples. If someone was to personally come across and look into `createRoutesFromElements`, I'm 100% certain that the majority of these people (yourself included) would be capable of reading documentation to find out how it works and choose for themselves how they'd prefer to do things. How clean something looks is also very subjective - I personally find the array/object look significantly easier to read, but clearly it's the opposite for you.

I don't think the lesson needs overhauling nor splitting. Some lessons will naturally be larger than others and in this case, all the content flows in one direction and is closely related to each other so in my mind, splitting for the sake of shorter lessons will only spread a "problem" over a wider area.

Loaders are something I might like to have touched upon in the following data fetching lesson though. I agree they are very useful and I think not just useful/neat but a genuinely very good part of React Router to be aware of (because many aren't aware until someone suggests it in the help channels).

@TheOdinProject/react thoughts?

**Comment by 01zulfi** [comment]
I concur with everything said above. To me, it doesn't really matter how learners create routes as long as they can. And yeah, some lessons are longer than others, no need to split them.

Loaders are definitely interesting. When we were discussing these lessons, I opted against them because I wanted learners to stay vanilla React for data fetching. There's a lot of learning value in learners figuring out `useEffect` for data fetching and errors/loading states. 

But if we want to add Loaders in the curriculum, I'd want to see it as an additional resource in the fetching data lesson instead of react router lesson.

**Comment by MaoShizhong** [comment]
I do think loaders are an interesting and rather useful thing to be aware of. I agree, an additional resource sounds appropriate for this.

@nikitarevenco if you're happy to find and add an additional resource on loaders for the React data fetching lesson then I can "assign" this to you.
I will close this particular issue because the majority of its contents are not planned for action and are unrelated, so I don't think it'll be appropriate to assign to this issue and have a loaders additional resource PR close this one.

If you're happy to do this, feel free to PR whenever you're ready to, and you can put `Related to #27585` as opposed to `Closes`.

**Comment by nikitarevenco** [comment]
> I do think loaders are an interesting and rather useful thing to be aware of. I agree, an additional resource sounds appropriate for this.
> 
> @nikitarevenco if you're happy to find and add an additional resource on loaders for the React data fetching lesson then I can "assign" this to you. I will close this particular issue because the majority of its contents are not planned for action and are unrelated, so I don't think it'll be appropriate to assign to this issue and have a loaders additional resource PR close this one.
> 
> If you're happy to do this, feel free to PR whenever you're ready to, and you can put `Related to #27585` as opposed to `Closes`.

Sure!
