### ISSUE TITLE
DOM Manipulation and Events: Section 7 of the assigned page is too complex

### ISSUE THREAD

**Issue by damon314159** [TheOdinProject/curriculum#27601]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The assignments say to do sections 1,2, and 7 of this page <https://www.javascripttutorial.net/javascript-dom/>
Sections 1 and 2 are fine, as is most of section 7, but the last few points, dispatchEvent, custom events, and MutationObserver, are in my opinion a little much for this introductory lesson

I suggest that the instruction could be changed to not include those three, and instead say something like "It is also possible to create and dispatch your own custom events, but for the most part the builtins are enough - don't be afraid to research into that if you need it later". Obviously worded more in line with the rest of the curriculum

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-dom-manipulation-and-events

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript can someone take a look please

**Comment by thatblindgeye** [comment]
@damon314159 Do you feel like that second assignment item (that instructs to read sections 1, 2, and 7 of the linked resource) offers anything new that the 1st resource/the lesson itself doesn't (and is more in scope of the lesson)?

Wondering if we should even have that second resource. If we do keep it, maybe instead of saying "Read sections XYZ...", we say "Read the following sections from [....the website name]", then have a nested list that links to the actual content users should read.

**Comment by thatblindgeye** [comment]
I'll assign you @damon314159
