### ISSUE TITLE
“Missing in props validation” no matching information

### ISSUE THREAD

**Issue by Ninja-Jutsu** [TheOdinProject/curriculum#27612]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The “Missing in props validation” paragraph is talking about some lines and giving an example of (under color and fontSize inside the Button component below) that cannot be found anywhere in the page.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-rendering-techniques

### (Optional) Additional Comments

Great work guys, wonderful course. I will genuinely donate at the end of the course. Thank you

**Comment by MaoShizhong** [comment]
@Ninja-Jutsu Thanks for opening this issue.

Looks like this is due to the lesson-note being moved from a later lesson in #27432 but the lesson-note contents was not changed to suit the its new context.

The note's verbiage will need changing to match where it current is in the lesson.

Opening this up for work since you did check the assignment request box.

**Comment by cakegod** [comment]
I'll fix this. Assign me, please.
