### ISSUE TITLE
 Project: Binary Search Trees - Instructions could be revised

### ISSUE THREAD

**Issue by MLGabe** [TheOdinProject/curriculum#27620]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Exercises: File type incorrect for all test files`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
The instructions are a little misleading, as it first tells the learner to create a Tree class with an array, but then the array itself is used in a func. This can cause confusing as the approach is different if going for functional or for object oriented, as the tree only needs the root.

**Comment by MaoShizhong** [comment]
Issue transferred to appropriate repo

**Comment by thatblindgeye** [comment]
@CouchofTomato do you think this is worth keeping open for others to work on, or could it be closed out?

**Comment by CouchofTomato** [comment]
@thatblindgeye I've added a help wanted label. I think if nobody has picked it up by the next time it's marked as stale we can close it

**Comment by kyak15** [comment]
@thatblindgeye @CouchofTomato Hello! Is there any possibility I can work on this issue?

**Comment by thatblindgeye** [comment]
@kyak15 yep, you're assigned

**Comment by MaoShizhong** [comment]
Closing this issue (was not originally linked in the PR above).
I'm not convinced there's an issue with providing the array for constructing the Tree, regardless of factory func/class approach.

The array provides a list of values, and that array is used to generate the balanced tree, for which the root node is returned, to be stored however appropriate. If you don't construct the tree with that array, then any "root" node will not be connected to anything.

It makes sense to allow instantiation of a Tree with initial values provided, just like you can declare an array or object with initial values, rather than being forced to construct an empty array/object, then manually push each and every value you wanted to it afterwards.

I've definitely not noticed this being an issue in the community, certainly not a repeated pain point. There are other repeated and justified pain points, but they're covered in existing open issues.
