### ISSUE TITLE
Admin Dashboard: Google Font usage contradiction with earlier Text Styles lesson

### ISSUE THREAD

**Issue by jscodin** [TheOdinProject/curriculum#27632]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I believe there may need to be an update/clarification to Step 4, Point 4 on the Admin Dashboard project

It is mentioned that the example uses the Roboto font which is a google font, but in the Text Styles lesson earlier we are told not to use google fonts as they violate GDPR

Think this may be confusing for others coming across this in the curriculum

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-admin-dashboard

### (Optional) Discord Name

jscodin

**Comment by MaoShizhong** [comment]
This might be something addressable as part of https://github.com/fabulousgk/top-curriculum/pull/1? Although @fabulousgk would need to fix the PR being made to the correct repo first.

I'm not keen on the current "strongly advise against" wording regarding Google fonts (as others have already expressed), and this is something that should be addressed in the linked PR.
With that wording change, it may then be sensible to add a note to the Admin dashboard for that Roboto font step saying that it's a google font, link back to the more text styles lesson, then saying you can download and self-host the font if needs be (since that's taught in that lesson).

**Comment by fabulousgk** [comment]
I fixed my PR, and am happy to take this issue as well.

**Comment by MaoShizhong** [comment]
@fabulousgk Assigning this to you as I think it's a very related change to your original PR idea. The details of wording and all that can of course then be discussed in your PR.
