### ISSUE TITLE
JavaScript - Webpack: Is complie the right word?

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/curriculum#27652]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

This is a small thing, in this text
>We’ve already introduced webpack in a previous lesson. It is the go-to tool across the web for bundling and compiling JavaScript code
Is the word compile correct?  I feel it should be transpile, compiling generally means turning code into machine language, but perhaps there is a usage in the JS community I am unfamiliar with.

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-webpack

### (Optional) Discord Name

fabulousgeek

**Comment by cakegod** [comment]
It seems they are often used interchangeably. Although Webpack docs use "compile" most of the time.

**Comment by MaoShizhong** [comment]
Some people stick strongly by `compile` referring to compiling to a lower level language, with `transpile` referring to translating to another language on the same sort of abstraction level.
At the same time, a lot do use `compile` interchangeably as an umbrella term.

Since the webpack documentation itself uses `compile` instead of `transpile`, I don't think this will be an issue that needs addressing.

**Comment by fabulousgk** [comment]
No problem, makes sense!
