### ISSUE TITLE
Installing PostgreSQL: Fix formatting

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/curriculum#27680]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In Step 2 of the Linux installation instructions, formatting for the note is incorrect:
![image](https://github.com/TheOdinProject/curriculum/assets/95084627/2afdd544-8b12-422b-afc6-d50345666ddf)

Seems like the header portion should not be there since it is a note.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-installing-postgresql

**Comment by MaoShizhong** [comment]
Looks like the cause is the div missing the attribute `markdown="1"`.
[installing_psql.md](https://github.com/TheOdinProject/curriculum/blob/bc14d71fd48a9c3dbc928556538d5de53305c11d/ruby_on_rails/advanced_forms_and_activerecord/installing_psql.md?plain=1#L83)

Lines 83-86
```md
<div class="lesson-note lesson-note--warning">
#### Systemctl and WSL2
Systemctl is not supported on WSL2, and the above command won't work. Instead run sudo service postgresql start.
</div>
```
will need to be changed to
````md
<div class="lesson-note lesson-note--warning" markdown="1">

#### Systemctl and WSL2

Systemctl is not supported on WSL2, and the above command won't work. Instead run

```bash
sudo service postgresql start
```

</div>
````
Blank lines required due to linting, and the bash command extracted to a code block for clarity.

Since you've not checked the assignment box, I'll open this up for contribution. Do let me know if you'd like to work on this though!

**Comment by Asartea** [comment]
This is probably my fault, oops. Would be willing to take this, but it might also make a good first contribution?

**Comment by MaoShizhong** [comment]
> This is probably my fault, oops. Would be willing to take this, but it might also make a good first contribution?

Since I've specified the exact fix required above (so would just be a copy+paste replacement job), it would be a good beginner contribution.

Just to advertise it a bit more, I'll leave it open with those labels for a day or two as it's not an urgent issue. If no takers then I'll throw it your way 😄

**Comment by MaoShizhong** [comment]
Go ahead!
