### ISSUE TITLE
Javascript course: How This Course Will Work: typo

### ISSUE THREAD

**Issue by DominicNugent** [TheOdinProject/curriculum#27732]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the third paragraph of the Javascript Track section, the following text appears: "...demonstrate to perspective employers...". Perspective is not the correct word. It should be "prospective."

You can see the definitions of each compared here: https://www.dictionary.com/e/prospective-vs-perspective/.

"Prospective is used in the context of looking ahead to what might happen in the future. Perspective is used in the context of viewpoints or the position from which something is viewed."

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-how-this-course-will-work

### (Optional) Additional Comments

Since practice is the best way to get familiar with how and when to use certain coding techniques, I'd love to see you add more Flexbox/Grid assignments to the Intermediate HTML and CSS course like the Dashboard project. Have us recreate, say, 10 html layouts from static images that cover a range of challenges, including some commonly used web layouts. And have us make them responsive so they work for desktop and mobile. Yes, we could do this on our own, but many won't unless you assign the projects to them. Make us run a few laps.

**Comment by MaoShizhong** [comment]
Thanks @DominicNugent, good catch on the typo.
Since you didn't check the assignment checkbox, I'll open this up for contribution if someone wants to comment to be assigned this.
Do let me know if you'd like to be assigned yourself.

As for the additional comment, that'd be something more suitable in its own issue for discussion. May or may not be something we get to discussing for a while, as there are lots of other things going on, but a separate issue would be most appropriate for that.

**Comment by kamranzafar4343** [comment]
I would love to contribute to it.

**Comment by MaoShizhong** [comment]
Go ahead! Assigned to you, @kamranzafar4343.
