### ISSUE TITLE
Basic Informational Site: Make the word plural

### ISSUE THREAD

**Issue by Crn0** [TheOdinProject/curriculum#27753]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

this sentence here **If you get stuck at anytime, feel free to go back to the tutorial from the previous lesson.** i think it will make more sense if we change the **lesson** to **lessons**. By changing 'lesson' to 'lessons,' we are now referring to multiple lessons, as opposed to just one.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-basic-informational-site

### (Optional) Discord Name

.crno.

**Comment by MaoShizhong** [comment]
Thanks for opening this issue, @Crn0.

That line should actually point to the [Getting Started lesson](https://www.theodinproject.com/lessons/nodejs-getting-started), where there's a W3 Schools tutorial that goes through some examples of creating a basic HTTP server and use the file system to send simple responses to requests.

The best 80:20 work for now (since this section will be revamped in due course) would be to change that line you pointed out in the basic informational site project to:
```
If you get stuck at anytime, feel free to go back to the [Getting Started lesson](https://www.theodinproject.com/lessons/nodejs-getting-started), especially the W3 schools tutorial at the end.
```

Then also in the Getting Started lesson file, removing the "Optional Extra Credit!" bullet, then unindenting the sub-bullet so it becomes its own top-level bullet (shouldn't be an optional thing IMO).

Let me know if you're happy to make these changes.

**Comment by Crn0** [comment]
Hello, Mao! It will be my pleasure to make the changes. Thank you for the suggestions. However, I will do it tomorrow as I'm done for the day.

**Comment by MaoShizhong** [comment]
Never a rush :)
