### ISSUE TITLE
Proposal for addition of video material for a clearer explanation of CSS resets / normalise

### ISSUE THREAD

**Issue by Sprou-t** [TheOdinProject/curriculum#27779]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Hi so i recently went through the CSS default styles lesson and came across this youtube tutorial video [https://www.youtube.com/watch?v=Nn2_ISgTG1I](url) that I felt was extremely helpful for myself. Additionally this video [https://www.youtube.com/watch?v=msBOZEwWaNE](url) offers a compelling argument about why CSS resets are not as important compared to years ago and it also questions the need of using CSS reset.

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-default-styles

**Comment by fabulousgk** [comment]
Thank you for these suggestions.  I am in the middle of a rewrite of this lesson and these will make a nice addition.

**Comment by MaoShizhong** [comment]
Thanks for suggesting these @Sprou-t. They're definitely nice resources and would be good for the current lesson, but in the linked rework for that lesson, we've decided not to include those resources since many of their key points are already covered by the rewritten material and new resources.
Still, thank you for suggesting them! I'll close this issue since we won't be planning to add them, due to the other planned work.
