### ISSUE TITLE
How To Deal With Side Effects: should be used the word "counter" instead of "count"

### ISSUE THREAD

**Issue by francpg** [TheOdinProject/curriculum#27771]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the code parts of the lesson it uses the variable "count" but ther is no declaration of this. I think it should be the variable "counter".

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-how-to-deal-with-side-effects

**Comment by CouchofTomato** [comment]
@TheOdinProject/react Can someone take a look please

**Comment by MaoShizhong** [comment]
Thanks for opening this issue @francpg.

`count` is the correct variable here. The setState argument used in those examples using the state updater function pattern, where a callback is provided instead of a direct value. 
So the callback is `count => count + 1`, where `count` is declared as that callback function's parameter.

State updater functions are discussed in the [More on State](https://www.theodinproject.com/lessons/node-path-react-new-more-on-state#state-updater-functions) lesson.

I'll close this issue as the current code is correct - hope that clears up some confusion!
