### ISSUE TITLE
Clean Code: sumArray section missing example code

### ISSUE THREAD

**Issue by txfgh** [TheOdinProject/curriculum#27787]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The section under Naming Functions and Variables, located [here](https://www.theodinproject.com/lessons/foundations-clean-code#naming-functions-and-variables), has a subsection titled "A good name is descriptive" that references an array variable titled "sumArray". However, despite other sections on this page having code blocks outlining good and bad examples of clean code, there is no code block showing anything related to the arrays mentioned in this section.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-clean-code

**Comment by MaoShizhong** [comment]
Thanks for raising this @txfgh.
This is an oversight from when the original array-based example was changed to a string concatenation example in #27361, but the text following it wasn't amended accordingly.

Opening this up for assignment if someone wishes to comment below.
The verbiage in the two paragraphs in question need to be amended so that:
- the variable/function names match the current string concatenation example
- the "what is an array" sentence is omitted since we no longer have an array example
- the second paragraph does not reference a `q` variable, as the current example does not have one.

**Comment by MaoShizhong** [comment]
Assigned, @kudamndau

**Comment by kudamndau** [comment]
I just realised something the PR I made is for my forked curriculum repository, is there a way to fix this or do I need to open another PR? @MaoShizhong
