### ISSUE TITLE
Objects and Object Constructors: Format and Text Alignment Inconsistency.

### ISSUE THREAD

**Issue by mohammednumaan** [TheOdinProject/curriculum#27831]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

 **Link**: https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors#the-prototype

**ISSUE 1**

There seems to be a styling/format inconsistency in the **3rd** point. The word wraps and 'de-structures' the overall sentence.

Rendered Output:
![image](https://github.com/TheOdinProject/curriculum/assets/138296610/2cd7c1ac-029c-481b-a762-7da6d405e404)

Possible Fix:

I adjusted the markdown to include **HTML** instead of the default markdown syntax and it fixes the problem!
![image](https://github.com/TheOdinProject/curriculum/assets/138296610/57407a3d-1571-440d-9a5d-95c648471c0e)

**ISSUE 2**

At the end of the lesson, i.e the **Assignment Section**, point number *2* to be precise, mentions the article uses __proto__ . The __proto__ is not formatted properly. (image attached below)

![image](https://github.com/TheOdinProject/curriculum/assets/138296610/9d741a18-5402-4198-a971-cbd331db8ceb)

whereas, it should be:
![image](https://github.com/TheOdinProject/curriculum/assets/138296610/3cda6592-9c6a-402e-8478-42b8f578d149)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors

### (Optional) Discord Name

void.jsx

### (Optional) Additional Comments

Is this a browser or an issue on my end?
I will be happy to work on this issue!

**Comment by MaoShizhong** [comment]
Thanks for opening this issue @mohammednumaan.
For point 2 about `` `**proto**` `, that does need to be fixed to be `` `__proto__` ``. It looks like at some point, someone mistook it for our old bold markdown syntax and "fixed" it to asterisks, which is what we use now. But didn't realise this was an intentional use of double underscores.

For point 1, I'm unable to recreate this. On my end, everything renders properly on Chrome, Brave and Firefox (including on Android mobile) at all viewport sizes. What browser/device are you using that ends up with this issue? Does it occur on any other device/browser? What does the DOM look like in whatever browser you use that renders it broken? We would not be looking to fix the markdown by using inline HTML (we only use HTML for specific cases), and we have linting rules to prevent this otherwise. But this might be an edge case that needs investigating with the web app's markdown converter.

**Comment by MaoShizhong** [comment]
Hang on, just recreated it when accessing a link fragment. I'll investigate the cause for this.

**Comment by MaoShizhong** [comment]
@mohammednumaan Was looking at the wrong part of the lesson (the ordered list, not the level 4 headings).

Assigning you to this - the following two changes need to be made:
1. Remove the `*` from `inherits` in the offending level 4 heading. It doesn't need the italics anyway.
2. Replace the `**` in the `` `**proto**` `` bit with `__`

**Comment by mohammednumaan** [comment]
@MaoShizhong Thanks for looking into the issue! I'll send a PR with the fixes! 👍

**Comment by mohammednumaan** [comment]
@MaoShizhong Oh yes! I viewed the page in `dev-tools` and there seemed to be `flex` properties applied. Changing it to `block` would fix it. :+1:

**Comment by MaoShizhong** [comment]
@mohammednumaan Yeah, those flex properties were a carryover from how the site used to be structured, but now only applies to those heading anchors. So we can remove flex and position the `::before` without flex.

The heading still doesn't need the `* *` anyway, but at least removing the flex properties will prevent future issues.
