### ISSUE TITLE
Getting Started NodeJS Course - New 2024 TraversyMedia crash course video suggestion.

### ISSUE THREAD

**Issue by h4m24-a** [TheOdinProject/curriculum#27865]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the additional resources the linked TraversyMedia crash course was uploaded 5 years ago and  a new 2024 Node Crash course was uploaded a few days ago by TraversyMedia. 

I know this may not be necessary so its just a suggestion.

You could add both videos.

https://www.youtube.com/watch?v=32M1al-Y6Ag

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-getting-started#additional-resources

**Comment by Siriuszx** [comment]
I would like to be assigned to this issue 🙂

**Comment by wise-king-sullyman** [comment]
Thanks for creating this issue!

@Siriuszx thank you for volunteering! I'm happy to assign you, but I don't think we would want to have both, and we'd probably need to make the call on which we'd rather have. The older one being older doesn't necessarily mean that it doesn't fit our use case better.

The scope here would really have to be investigating the new video and watching the old video if you haven't already, documenting the differences (particularly what, if anything, was in the old one but is not in the new one), and providing that information to the maintainers.

Before you do anything though, @TheOdinProject/javascript what do we think about the additional resources on this lesson in general? Have any of you already watched it all? It's quite lengthy, the first video is over an hour and a half and the second resource is a 12 part series. I wonder if we want to include them in the first place.

**Comment by MaoShizhong** [comment]
@wise-king-sullyman Just watched the old and new videos over last night and today.
I don't think the new version offers anything significant that warrants a replacement for the old version, i.e. the old version is still perfectly suitable for our needs and the context of our current curriculum. In fact, it's kinda slightly more suitable given the old one uses CJS, and the new one uses ESM. Our current curriculum's resources all use CJS by default as far as I'm aware.

So I don't think any replacement needs to be done in this case.

Since we are revamping the Node course, this may well be a source to consult when we get to the Node intro section (we're still working on the Express section). Since by that point, we'll have a lot more control over what material we write, we may not even include the new course as an AR link but use it to write our own in-house material which we have more control over maintenance for.

**Comment by wise-king-sullyman** [comment]
@Siriuszx thanks for the offer! 💪 

@MaoShizhong thanks for digging into it. Having watched it do you think it's something that is worth keeping as an AR at all for now?

**Comment by MaoShizhong** [comment]
@wise-king-sullyman I think we should just keep the current AR as it is, and make no changes.

**Comment by wise-king-sullyman** [comment]
I'll leave this open for a bit in case other maintainers would like to add any thoughts, but if nothing else happens it seems we should probably close this issue after a week or two.

Thanks again though @h4m24-a and @Siriuszx !

**Comment by thatblindgeye** [comment]
Closing per the above discussion.
