### ISSUE TITLE
Foundations Command Line Basics: External UNIX Shell course uses Nano

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/curriculum#27872]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

[Command Line Basics](https://www.theodinproject.com/lessons/foundations-command-line-basics#assignment) includes an assignment to swcarpentry's UNIX Shell course. In particular, the [Working with Files and Directories section](https://swcarpentry.github.io/shell-novice/03-create.html) includes some instruction on creating text files in Nano. It also includes a note box within it talking about "Which Editor?", with some language that some people in Discord have thought might [make the thought of using editors other than VSCode appealing](https://discord.com/channels/505093832157691914/505093832157691916/1233782863397388378).

Either way, I find it odd that an assignment we have includes a short snippet that makes people use Nano, which we'll never touch again afterwards. And that's before people are probably clued fully clued in one what to do and not do. [Example of recent confusion from a learner about which text editors](https://discord.com/channels/505093832157691914/505093832157691916/1233779036149518337).

The previous lesson is on text editors where we make the VSCode recommendation.
I'm in a mind that an 80:20 resolution for this would be to add a note underneath
![image](https://github.com/TheOdinProject/curriculum/assets/122839503/060c4364-6cdb-4d43-b5ab-78ede36410b1)
that provides the `code draft.txt` command instructions instead, and instructions for saving that file in VSCode, as opposed to using Nano.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-command-line-basics#assignment

**Comment by MaoShizhong** [comment]
@TheOdinProject/foundations Any thoughts on this?

**Comment by scheals** [comment]
I was not asked but knowing how to use `nano` is a good thing - if learners don't configure git correctly, their default text editor will be `nano`. Many answers on SO or AskUbuntu suggest using `nano` and people don't realise they could use a different text editor. Same would apply for `sudoedit` if no editor is provided.

My recollection isn't that great but I do believe using `nano` never was a pain point ever for learners while going through this content. The note is quite clear that many programmers are fans of particular editors and that VSCode belongs to a different group (graphical) than vim and emacs.

Furthermore, this resource has historically caused problems for WSL2 users (https://github.com/TheOdinProject/curriculum/issues/27338) so stacking even more exceptions would put inclusion of this great resource in jeopardy. I call it a great resource because ever since the lesson has been revamped to use it, the volume of questions relating to using CLI has dropped significantly.

**Comment by MaoShizhong** [comment]
Not an issue exclusive to maintainer feedback - your insight and opinion is also absolutely kore than valid, thank you! Just thought since I'm personally less familiar with this part and potential community pain points, I'd open the discussion in case there are things that are deemed appropriate to do!

**Comment by thatblindgeye** [comment]
Agreed on not stacking exceptions. It may also be more confusing or easy to forget any note about using some other command rather than what the linked resource says, since the `nano` command isn't mentioned until the 5th or 6th heading.

If this isn't a prevalent issue raised on Discord I'm not sure we need to really address it. If we want to, *maybe* just a note about how nano is used for this resource and may be something they use again (pretty sure at some point I've had to use nano when dealing with commit messages within the VS code terminal...)

**Comment by MaoShizhong** [comment]
That's fair enough! Since it doesn't look like it's been a notable source of confusion, let's close this and only address if it actually becomes one.
