### ISSUE TITLE
Binary Search Trees project: levelOrder requiremement is not clear

### ISSUE THREAD

**Issue by nguyenlekhtn** [TheOdinProject/curriculum#27880]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

![image](https://github.com/TheOdinProject/curriculum/assets/25528200/42a9b45e-198e-434c-9a6d-e223c7f6fca0)

The requirement asks to return an array of values if no callback is provided. But what should the function return if a callback is provided? Should it return an array of values too? Or it should return nothing if callback is provided?

My suggestion is that the function should always return an array of values no matter callback is provided or not.

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-binary-search-trees

### (Optional) Discord Name

haru => {haru:}

**Comment by MaoShizhong** [comment]
Thanks for opening this issue, @nguyenlekhtn. I've noticed this step is a common source of confusion amongst learners.
The instruction's intention is to return an array of values only if no callback is provided. If a callback is provided, it should just be called on each Node as you traverse the tree. Basically like `Array.prototype.forEach` but with a default behaviour in the case of no callback.

However, this does feel a bit strange as the default behaviour is *very* different in nature to when a callback is provided. Since this (and the next step with the different traversal orders) is effectively like `Array.prototype.forEach` (only with a specific traversal order), I'm wondering if the instructions for this and the following step should be adjusted so that *instead* of returning an array of values in the case of no callback, it throws an error saying it expects a callback?

I believe this would make it more intuitive and also be more in line with how you'd expect such a method to work anyway. @TheOdinProject/ds-a thoughts?

**Comment by MaoShizhong** [comment]
Just adding on to the above, my suggestion regarding throwing an error if no callback is passed in (for `levelOrder`, `inOrder`, `preOrder` and `postOrder` i.e. steps 6 and 7) definitely makes sense for the JS version of this project, since it's much closer to `Array.prototype.forEach`.

Given that Ruby works a bit differently with things like returning Enumerators if no block's provided instead of throwing an error, I'm wondering then how best to approach the Ruby version. @TheOdinProject/ruby thoughts on this? Not familiar enough if something like always returning an array, block or not, would be the most ideal.

I know that for the JS version, it would make most sense to never return something from it and just throw if no callback provided.

**Comment by MaoShizhong** [comment]
## Update

I'd like to have `levelOrder`'s instruction changed so that instead of returning an array of values if no callback is provided, it throws an error saying "undefined is not a function", just like what would happen if you did not pass a callback to `Array.prototype.forEach`.

The original "return an array of values" seemed to be a translation from Ruby's `#each` method (and any related methods) which returned an enumerator if no block was provided. Since this doesn't translate very well to JS, the above will hopefully be more intuitive and familiar behaviour for people on the JS track, which has proven to be one of the most common pitfalls I've seen.

Not making this a `map` equivalent as in the real world, you'd implement a purely traversing method as well as a "transformative" one that returns something, just like `Array.prototype.forEach` and `Array.prototype.map` are separate. Since this task is really all about traversing and doing so in the correct order, there isn't a huge reason why we'd *need* to make it something like `map` IMHO.

So something like the below (wording suggestion only) seems appropriate:
> The method should [throw an error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw) that says `'undefined is not a function'` if no callback is given as an argument, just like if you forgot to pass a callback to `Array.prototype.forEach`.

@nguyenlekhtn Let me know if you're still happy to make this change or not, then I can assign you or open this for assignment otherwise.

## Acceptance criteria

- [ ] Change `levelOrder` instruction to throw an error if no callback, instead of returning an array of values.
- [ ] Change next step (`inOrder`/`preOrder`/`postOrder`) to reflect this change.
