### ISSUE TITLE
Introduction To React Testing: add "Testing Implementation Details" by Kent C. Dodds

### ISSUE THREAD

**Issue by Siriuszx** [TheOdinProject/curriculum#27885]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The last time testing was mentioned was in the JavaScript "Testing Basics" section of the JavaScript course. That's a pretty substantial gap considering that people don't return to testing until the end of the React course.

This article is well-written, light-weight and covers the main talking points of the [Rails Conf 2013 The Magic Tricks of Testing by Sandi Metz](https://www.youtube.com/watch?v=URSWYvyc42M&t=681s&pp=ygURcmFpbHNjb25mIHRlc3Rpbmc%3D) but in the context of UI frameworks.

I think it could be a reasonably good read for the "Additional Resources" since it introduces an opportunity for some spaced repetition to take place and encourages people to write tests that will **NOT** cause frustrations long-term, which in my humble opinion is the key.

- ["Testing Implementation Details" article by Kent C. Dodds](https://kentcdodds.com/blog/testing-implementation-details)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-react-testing

**Comment by MaoShizhong** [comment]
@Siriuszx I think this is an awesome article and does cover a little gap that I also think is worthy of an assigned reading (especially since it's not that long of an article).

I'll assign this to you. Could you pop it in as a new 3rd assignment list item? It should ideally also have a small mention that while it starts with examples from the Enzyme testing library, the concepts are the most important focus.
