### ISSUE TITLE
Foundation - Axes: shows code before code

### ISSUE THREAD

**Issue by NexusHiveMind** [TheOdinProject/curriculum#27901]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### Describe your suggestion

There is some code showing before the 
".flex-container {
  flex-direction: column;
}"
part, it shows:
`</span>`
![Screenshot_2024-04-30_14-58-31](https://github.com/TheOdinProject/curriculum/assets/50855957/5ce4396f-a56d-4ea4-bf91-61fc106dd26c)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-axes

**Comment by MaoShizhong** [comment]
Thanks for opening this issue @NexusHiveMind.
Looks like this is caused by some previously strange formatting of a `span` that was used for an `id` for link scrolling purposes, which then the lint auto-fixer "fixed" but in context, was an incorrect fix (caused by the previous odd formatting).

The solution here would be to remove the `<span id='flex-vertical'>` and `</span>` on lines 15 and 17 of `foundations/html_css/flexbox/flexbox-axes.md` entirely, then change the link fragment on line 54 from `#flex-vertical` to `#axes`.

Opening this up for contribution, if anyone wishes to comment to be assigned.

**Comment by NexusHiveMind** [comment]
I would like to try.

**Comment by MaoShizhong** [comment]
Go for it @NexusHiveMind
