### ISSUE TITLE
Mini Message Board: express-generator is deprecated

### ISSUE THREAD

**Issue by ashifthekkupuram** [TheOdinProject/curriculum#27923]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)

added 7 packages, and audited 111 packages in 3s

16 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (1 moderate, 2 high, 2 critical)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-mini-message-board

**Comment by MaoShizhong** [comment]
Thanks for opening this issue @ashifthekkupuram.

`express-generator` is admittedly a rather dated tool and has not had its dependencies updated for a long time. That being said, at least for course purposes, it still serves its purpose. And if someone does not want to use it to scaffold an Express app when starting, they can definitely just create their own from scratch which won't need much.

That being said, we are already planning to rework any content in the Node course that uses `express-generator` so we no longer need it as part of our longer-term Node revamp project. Given this, I'll close this issue as unplanned because it does not really *need* to be removed yet, and we already have plans being worked on that will replace it.
