### ISSUE TITLE
Frameworks and Preprocessors: <Link in the Knowledge Check section leads to an unprecedented webpage>

### ISSUE THREAD

**Issue by emmahare** [TheOdinProject/curriculum#28021]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The link in the second question of the "Knowledge Check" section; "What are some disadvantages of using a CSS framework", leads to a webpage that has 1. not been mentioned in the lesson up to that point and 2. doesn't exactly tell us anything about what disadvantages of CSS frameworks are, thus probably leading to confusion, seeing the links in that section usually lead to a section or page that has already been gone through during the lesson. I'd suggest changing the link into leading the user up to the "Disadvantages of frameworks" section of the lesson itself, and adding the original, unrelated, link into the "Additional resources" section. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-frameworks-and-preprocessors

### (Optional) Discord Name

BakedBeansOnToast

**Comment by MaoShizhong** [comment]
Thanks for opening this issue @emmahare. The link that KC question has used to be in the main lesson contents, but a recent change trimmed it out (along with a couple of other links which were not the most relevant anymore), and we just forgot to amend the KC questions accordingly.

Instead of adding the link back in, would you be happy to amend the KC section so that instead of the current 4 questions, it instead has the following 2 questions only?

```md
- [What are CSS frameworks?](#frameworks-overview)
- [What are CSS preprocessors?](#preprocessors-overview)
```

To me, those feel like more appropriate KC questions to be reflecting on, given the purpose and overview points of the lesson.

**Comment by emmahare** [comment]
Yeah that sounds like a good change I'd definitely do that. I haven't done such thing before, but from what I can see, I need to be assigned to it, to then submit a pull request, right?

**Comment by MaoShizhong** [comment]
Spot on @emmahare. You can follow the [contributing guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md) for guidance, and feel free to ask any questions should you run into issues.
