### ISSUE TITLE
DOM Manipulation and Events: More clearly describe the relationship between nodes and elements.

### ISSUE THREAD

**Issue by Hachibroku** [TheOdinProject/curriculum#28030]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

From the lesson overview:

Explain the difference between a “node” and an “element”.

I don't think this lesson does a particularly good job of explaining this difference, or rather the way these two concepts to relate to each other. It uses the terms interchangeably, for example:

[Append elements]
- parentNode.appendChild(childNode) - appends childNode as the last child of parentNode.

Perhaps the intent is to have the learner pick it up naturally, but to me it just seems confusing without a more overt explanation. Especially considering it's listed as one of the learning objectives in the overview. I think something as simple as mentioning that an element is the type of node we're working with primarily in this lesson would be sufficient clarification. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-dom-manipulation-and-events

### (Optional) Discord Name

murphxmurph

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript Can someone please review.

**Comment by thatblindgeye** [comment]
@Hachibroku do you feel even the assigned resource - [MDN's DOM Manipulation](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents#active_learning_a_dynamic_shopping_list) - doesn't exactly satisfy going over the difference between the two?

If not, then adding a short blurb may not be a bad idea. We should try to keep it succinct, though, just due to how much content the lesson is already covering. Depending on your thoughts to the above question, we can move forward from there.

**Comment by Hachibroku** [comment]
@thatblindgeye After re-reading the materials and improving my own understanding of the content, I think that one should be able to understand how 'element' and 'node' relate to each other, but it is somewhat obscured by the lesson. Of the resources linked in the lesson, [Digital Ocean - Understanding the DOM Tree and Nodes](https://www.digitalocean.com/community/tutorials/understanding-the-dom-tree-and-nodes#identifying-node-type) contained the explanation I was looking for. 

I think directly addressing node types and how we're using them would improve the clarity of the lesson overall. For example, an appendage to the paragraph under the **Document Object Model** heading so it now reads;

> The DOM (or Document Object Model) is a tree-like representation of the contents of a webpage - a tree of “nodes” with different relationships depending on how they’re arranged in the HTML document. There are many types of node, most of which are not commonly used. In this lesson we will be focusing on "element" nodes which are primarily used for manipulating the DOM. 

or the same information in a separate, clarifying blurb may work better than trying to integrate into the existing content. 

I think it may also help to change the final sentence in the paragraph under the **DOM Methods** heading to say 
>those that help you target elements. 

instead of 
>those that help you target nodes. 

since query selectors specifically work with elements, and it reinforces the node type.

**Comment by thatblindgeye** [comment]
I think your tweak to the first paragraph sounds good. I'd also be fine with your other suggestion, though we could also just remove that sentence entirely since it doesn't really feel all that necessary to say "First we'll cover [thing]. (heading for [thing] on the very next line)".

Assigned you to the issue, though!

**Comment by Hachibroku** [comment]
@thatblindgeye just plugging this for visibility!
