### ISSUE TITLE
Intermediate HTML and CSS Course: Link to previous lesson is under the Ruby path instead of Javascript path

### ISSUE THREAD

**Issue by JackBogart** [TheOdinProject/curriculum#28070]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the project description, the lesson suggests users should choose their own fonts and suggests reviewing the previous lesson that covered fonts for how to include external ones. However the linked lesson is for the ruby path lesson rather than the javascript path lesson. This is a minor mistake but it would be better to stay consistent and keep users on the javascript path. 

Here's the current link it redirects to: https://www.theodinproject.com/lessons/intermediate-html-and-css-more-text-styles

Here's the link it should redirect to: https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-more-text-styles

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-admin-dashboard

### (Optional) Discord Name

colonelchicken

### (Optional) Additional Comments

I haven't worked on an issue before but I'd like to contribute more eventually. I figured this change would be trivial enough to get me familiar with the process.

**Comment by MaoShizhong** [comment]
Thanks for opening this issue @JackBogart 
All of the Intermediate Html/css lessons are shared between the teo pathways i.e. one lesson file for both. Therefore, a link to a previous lesson will always be "the wrong link" for the other pathway.

Since such links are only for people to reference a single lesson, and doubling up on each link that references a past lesson in every shared file would be unnecessary bloat, we'll leave the link as is and close this issue. Hope that makes sense!
