### ISSUE TITLE
Variables and Operators:  Wrong suggestion about declaration with an assignment about returning undefined value.

### ISSUE THREAD

**Issue by bibekchand** [TheOdinProject/curriculum#28103]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the javascript basics section, in  variable and operator chapter at the last line: "however for now it is good to remember that a declaration with an assignment (such as let b = 7 * a) returns undefined and so you cannot declare and assign a value to a variable and read its value in the same line."

This is not true now. The javascript allows you to do that right now.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-variables-and-operators

### (Optional) Discord Name
crap_momo.

**Comment by bibekchand** [comment]
![java](https://github.com/TheOdinProject/curriculum/assets/95962268/0c429f1a-501b-44a5-9864-16cea78ddde6)
![java2](https://github.com/TheOdinProject/curriculum/assets/95962268/3d9564e2-1bb3-42f2-9437-746e4d96eb3e)

**Comment by MaoShizhong** [comment]
Thanks for creating this issue @bibekchand. There's a misunderstanding here with what that line means. The key part is "cannot declare and assign and read its value on the same line".

In your example, you declared and assigned a variable on one line, then on a separate line, read the value of it using `console.log`. That's perfectly fine to do.

If you go into the browser console and enter just `a = 1`, you'll see the next line shows `<- 1` meaning it assigned the variable and read its value, returning its value all at the same time.
But if you did `let a = 1` instead (i.e. declaring the variable with `let`), you'll see `<- undefined` because it can't read the value in one go at the same time as declaring and assigning.

![image](https://github.com/TheOdinProject/curriculum/assets/122839503/f587e349-2908-451d-a1ed-923e5e8ac584)

You can do whatever you want in separate statements perfectly fine.

**Comment by MaoShizhong** [comment]
Closing as the current instructions are correct and no further action is required.
