### ISSUE TITLE
Deployment Lessons Rails/Node Course: Fly.io free allowance are not applicable during free trial

### ISSUE THREAD

**Issue by AhmedTheGreatest** [TheOdinProject/curriculum#28145]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### Describe your suggestion

Fly.io's new free trial does not include a free allowance. Free allowance is only applicable when you're already on a paid plan.

![image](https://github.com/TheOdinProject/curriculum/assets/67534373/be3b8ebb-36b4-47e3-b64a-f27592f07524)

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-deployment

### (Optional) Discord Name

tornado_77

### (Optional) Additional Comments

Discussion about this issue on Discord: https://discord.com/channels/505093832157691914/505093832157691916/1248959137631703081

**Comment by MaoShizhong** [comment]
This also affects the Node pathway.

Our lesson was updated with the new free trial info in #27895, which at the time, the docs actually said that free trial credit is only consumed after exceeding the free resource allowance. [Last week they updated their docs changing it](https://github.com/superfly/docs/pull/1552), so that the free resource allowance is not allowed for free trial credit.

**Comment by wise-king-sullyman** [comment]
Thanks @MaoShizhong!

Sounds like we should update the description of fly.io in both paths, have at it @AhmedTheGreatest!
