### ISSUE TITLE
Linting and RuboCop: Unclear what "the" Gem is.

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/curriculum#28269]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There is an example of locally installing a plugin for RuboCop in [You are the code dictator](https://www.theodinproject.com/lessons/ruby-linting-and-rubocop#you-are-the-code-dictator) section that confuses learners due to the wording:
> Since RuboCop is extensible, there exist other departments that you can use - like Performance or RSpec. You could even write your own Cop! The process of adding an extension is easy: you install **the Gem** locally and modify `.rubocop.yml`.

I'm ESL and when I wrote this my train of thought was "the Gem you are interested in, Performance, RSpec, your own Cop". Perhaps it should be "a Gem" or "the Gem(s) you chose".

[Example confusion seen on discord](https://discord.com/channels/505093832157691914/543074220691947531/1254846727207391334)

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-linting-and-rubocop

**Comment by SumonGFC** [comment]
Hi @scheals 
I do think this section is a bit confusing mainly because of the "metaphor" of cops/departments. 

"Since RuboCop is extensible, there exist other departments that you can use - like Performance or RSpec."

I think this line might be less ambiguous if were phrased like:

"There are many gems you can install that will [extend RuboCop](https://docs.rubocop.org/rubocop/extensions.html) like [rubocop-rspec](https://github.com/rubocop/rubocop-rspec) or [rubocop-performance](https://github.com/rubocop/rubocop-performance). 

Also, on [line 180](https://github.com/TheOdinProject/curriculum/blob/main/ruby/object_oriented_programming_basics/linting_and_rubocop.md?plain=1#L180) I think it would be helpful to specify that the line in the proceeding codeblock should be added to the GemFile (and not the `.rubocop.yml` file)

**Comment by SumonGFC** [comment]
@scheals Okay, I think I have a good idea of how to help make this section a bit more clear and that would address the issues we've discussed so far. I can submit a PR for you to review. If you like the changes we can merge it, or if you think it could be better we can discuss further. Sound good?

**Comment by scheals** [comment]
@SumonGFC 
I have no power here :) But I believe when maints see that you're up to fixing this, they'll assign you the issue and then give you the green light for working on a PR, then review it with you.

**Comment by SumonGFC** [comment]
@scheals right okay haha. I value your input however, as you are the one who wrote this lesson.

**Comment by CouchofTomato** [comment]
Feel free to submit a PR @SumonGFC

**Comment by SumonGFC** [comment]
PR submitted. Please let me know if you have any thoughts/criticisms/suggestions to improve it.
