### ISSUE TITLE
<Ruby>: <Found a  better resource for hangman lesson to explain the rules of the game>

### ISSUE THREAD

**Issue by NewDev2005** [TheOdinProject/curriculum#28292]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

This https://youtu.be/leW9ZotUVYo?si=DGfBo5MgLtuKT9eA resource is an improvement over the previous resource. I mean there isn't anything particularly wrong about the previous wikipedia page however it is just a plain wikipedia page and this video has some great visual representation which will help the learners to understand game quickly. 

Kindly take a look at the video and let me know how you people about this.
Thanks! 

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-hangman

### (Optional) Discord Name

Htmx

```[tasklist]
### Tasks
```

**Comment by mathdebate09** [comment]
Hey @CouchofTomato I could take this issue up, a suggestion we should consider? Maybe add [wikihow blog on Hangman](https://www.wikihow.com/Play-Hangman) instead of the video? Though I'm leaning towards the video cause it's short and concise and auto-gen subtitles are accurate.

**Comment by NewDev2005** [comment]
@CouchofTomato I think you should assign this to @mathdebate09  he is interested i guess

**Comment by AhmedTheGreatest** [comment]
Hello, I can work on this issue.

**Comment by MaoShizhong** [comment]
Assigned you @mathdebate09.

As part of #28290, the one planned change for the Hangman project was to delete the following line:
> If you're unfamiliar with how Hangman works, see [Wikipedia](http://en.wikipedia.org/wiki/Hangman_(game)).

Since the exact same link is already linked with a more appropriate href on line 3.
If you can go ahead and delete the sentence I just mentioned (which would be on line 6), then change the href for the link on line 3 to `https://www.wikihow.com/Play-Hangman`, that'd be amazing.

I'd personally favour the written resource, which has the video at the bottom of it should people wish to watch that.
