### ISSUE TITLE
Transitions: <Change link that leads to potential phishing page>

### ISSUE THREAD

**Issue by DDJCS50** [TheOdinProject/curriculum#28336]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

When starting task 3 on the page I clicked the link that says "how to create performant CSS animations" and was immediately warned by my antivirus that there was a phishing attempt on the page.
![blocked-link](https://github.com/TheOdinProject/curriculum/assets/130430285/be7bfcf4-88b1-49e0-8daf-da468da12923)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-transitions

**Comment by MaoShizhong** [comment]
This seems to me like your antivirus was just being a little extra cautious and that's a false positive. I suspect it flagged that link at least in part because it's an embed within an iframe, which people can use those things for phishing purposes, but doesn't mean that iframes are all phishing dangers. The link it flagged is just for the slide-in animation demonstration.

You should be able to add to exceptions and report the link as a false positive to whatever antivirus software you're using.

**Comment by DDJCS50** [comment]
Will do, thank you very much.
