### ISSUE TITLE
Setting up Git: Need to add a command to perform '$ git init'

### ISSUE THREAD

**Issue by CrocsAreComfy** [TheOdinProject/curriculum#28344]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Setting up Git: Need to add a command to perform '$ git init' before the config commands. If you don't, you get the fatal: not a git directory.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-setting-up-git

**Comment by mathdebate09** [comment]
The lesson `Setting up Git` is about configuring git globally, i.e. for your machine, in all directories.
Doing `git init` translates to **make the current directory a git repository** which in the case isn't needed, can you describe more on which command caused you the error `fatal: not a git directory`.

**Comment by CrocsAreComfy** [comment]
I would be happy to give you the command that caused the error!

In the instructions it directs you to enter the following command to setup
git:

git config --global user.name "Your Name"

Once I entered the command (with my own username), I received that error. I
was confused because running "git version" returned 2.45.2 as the version
so I thought I should be fine.

When googling I saw people saying that it was because my directory was not
initiated as a git repo and to run "git init". Once I ran that command the
fatal error went away and I was able to continue.

More info, I am on a Mac with Apple Silicon, running Sonoma 14.5. Not sure
if that makes a difference. I was also in my home directory. Maybe I was
supposed to be in a different directory?

Stephen

**Comment by mathdebate09** [comment]
You're supposed to be in your computer's root directory, which your terminal defaults when opened.
Initiating as a git repo for configuring user name/user email shouldn't be necessary at all and yes, mac shouldn't be an issue either, chromeOS acts up sometimes but not mac.
Try using your default directory which shows up when you open terminal, but ideally using the global flag should ignore everything, you can drop this question in our dedicated [git-help](https://discord.com/channels/505093832157691914/690639791380758558) discord channel, I'm sure more people would help you there

**Comment by MaoShizhong** [comment]
Can confirm that you do not need to be in your home directory (`~`) to do global git config commands.

You will get the `fatal: not in a git directory` (or similar) error if you do not add the `--global` flag, since that tries to edit the current directory's git config, hence it must be a git repo. But since our commands have the `--global` flag, then they edit the global config file, which does not require you to be in a git repo. So I can only presume that when you did your commands, you did not have the `--global` flag or perhaps typed it incorrectly. Without a screenshot of your terminal demonstrating this, we won't be able to tell exactly what happened on your end.

Proof from my terminal (`~/repos` is *not* initialised as a git repo):

![image](https://github.com/TheOdinProject/curriculum/assets/122839503/66facdc1-4575-4848-a6dd-969c0cee25db)

**Comment by JoshDevHub** [comment]
Going to close this as it seems to be user error around the `--global` flag. If you're still having issues getting `git` setup, I recommend stopping by our discord server where someone will be able to offer support.
