### ISSUE TITLE
Foundations: Difference between primitives and objects variables

### ISSUE THREAD

**Issue by Sokolan** [TheOdinProject/curriculum#28391]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Currently the course doesn't mention the difference between primitives and objects at all (at least I couldn't find any mention for that).
This causes many learners to stumble problems like not understanding why their code behaves not the way they expected.
This leads to many issues later on, for example, in the factory functions pattern, where they return a primitive in the returned object and don't understand why it doesn't update, when they update the local variable in the function (or why we need setters/getters for certain things).

[This PR](https://github.com/TheOdinProject/curriculum/pull/27671) tried to address the issue, but it wasn't merged for reasons thatblindgeye mentioned.

So as thatblindgeye suggested, providing information regarding the differences can be added to [Objects basics lesson](https://www.theodinproject.com/lessons/foundations-object-basics#objects).
I've tried to find a source, to provide the learners to read, (article) that will address the issue and taking into account the problems that been raised in the mentioned PR. Unfortunately all articles I've seen either go into stuff that the [article](https://javascript.info/object-copy) that was provided in the previews PR goes into, or the article talks about the stack/heap which may be even more confusing for learners.
The possible solutions I see:
1. Provide the article which was provided in the previews PR.
2. Write new content that is specific for TOP learners at this point of the course.
3. Something I haven't though about, which may be better than 1 & 2.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-object-basics#objects

### (Optional) Discord Name

Sokolan

**Comment by JoshDevHub** [comment]
Thank you for making this issue @Sokolan 

Going to ping our javascript team to get their opinions on your suggestion @TheOdinProject/javascript

**Comment by MaoShizhong** [comment]
I actually find the current "Object Basics" lesson a little strange that it has such a tiny section on actual "objects" (albeit with links), and the rump of the lesson is on specific array methods.

They can of course stay, but I'm wondering if it would be a good idea to add a new section between "Objects" and "Intermediate/advanced array magic" that *briefly* introduces the value/reference thing between primitives and object-types (so also mentioning that it's not just `{}` objects but any non-primitive, since arrays are also a type of object). We could use the javascript.info article as a guide if necessary, but ensure we don't go into more than is appropriate for that lesson (i.e. only the idea of primitives passed by value, and object types dealing with references) - no need to dive into cloning or shallow/deep stuff etc. Just value/reference.

Not married to that. I also wouldn't mind a note box that briefly introduces it and links to that article but instructs to stop at the cloning and merging bit (we only need the introductory part then the comparison section).

Thoughts?

**Comment by Victor-M-Giraldo** [comment]
Having stumbled across these problems I think it's a good idea to do something along those lines.

**Comment by Sokolan** [comment]
@MaoShizhong I agree on that part:
> I actually find the current "Object Basics" lesson a little strange that it has such a tiny section on actual "objects" (albeit with links), and the rump of the lesson is on specific array methods.

When I took a look at the lesson and all it had about Objects was those 2 bullet points, it indeed seemed a bit odd, especially when the majority of the lesson is about array methods.

And by the rest of your comment I understand you're in favor of writing "in-house" content (rather than linking to another source).
I think it can work, and will medicate the potential drifting to non relevant topics for learners at this point of the journey.

**Comment by MaoShizhong** [comment]
@Sokolan I'm typically in favour of in-house content if I can trust the person writing it is capable of doing so well, and I trust you on that :smile: We can always review specifics when you PR.

I think it'll give more flesh to the lesson's name than just linking to an external article, which would also require us to rely on "read only XYZ parts" etc. We can definitely still include a link to that article with that note as a way to supplement the new content, but I'd personally favour our own content being the focus rather than shipping it all off to an article.

I'll assign this to you
