### ISSUE TITLE
Class Based Components: Remove Additional Resources

### ISSUE THREAD

**Issue by T0nci** [TheOdinProject/curriculum#28397]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The link provided in the Additional resources, [Thinking in React](https://reactjs.org/docs/thinking-in-react.html), is no longer using class based components, so it makes sense to remove it.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-class-based-components

**Comment by JoshDevHub** [comment]
Thank you for making this issue @T0nci 

Going to ping our @TheOdinProject/react team to get their opinions on this.

**Comment by T0nci** [comment]
A slight modification to my suggestion, instead of removing Additional resources, just remove the bullet point.

My reasoning is that other lessons that don't have any links for Additional resources still have the section.

**Comment by MaoShizhong** [comment]
Looks like the link was intended to point to https://legacy.reactjs.org/docs/thinking-in-react.html instead of the current docs, which never had class component examples, so we just need to replace the href.

We wouldn't get rid of the AR section anyway. All lesson files (non-project) require an AR section that has a default bullet if no actual items to link.

Assigning you, @T0nci, since you specified you wish to work on this.
