### ISSUE TITLE
A Deeper Look at Git: <Typo in code block>

### ISSUE THREAD

**Issue by 0x5b62656e5d** [TheOdinProject/curriculum#28404]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### Describe your suggestion

I think there is a typo in the code block under the section "Changing multiple commits."

```git
git commit --amend
```
to 
```git
git commit --amend -m "Create second file"
```

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-a-deeper-look-at-git

### (Optional) Discord Name

pepper4340

**Comment by MaoShizhong** [comment]
Thanks for opening this issue.

`git commit --amend` does things like `git commit`, by opening the default commit editor where you can write the commit message and body. `-m "message"` just appends the message as part of the command in one go without opening the commit editor, so there's no typo here. Using the commit editor is probably preferable since you can edit the existing message more easily than having to overwrite it in full in the command itself.

If someone followed the git setup instructions from Foundations, they'd already have VSCode set as their default commit editor.
