### ISSUE TITLE
"Replit" is paid now

### ISSUE THREAD

**Issue by harisalimughal** [TheOdinProject/curriculum#28412]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Replit allows to fork only 3 times, so to complete all the exercises we need to buy their paid plan. So working in vs code can be the best alternate solution from the start

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-data-types-and-conditionals

**Comment by MaoShizhong** [comment]
Thanks for opening this issue @harisalimughal.

Fortunately, it's not actually "fork 3 times and that's it", but rather you can only have a max of 3 public repls at one time, so if you delete one/some of your forks, you can make room again for a new fork. It seems to be a very recent change. It's not as convenient as before, but it's still perfectly sufficient.

It'd be better for us to add a [note box](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#note-boxes) to the assignment that Replit now only allows a maximum of 3 public repls, so if it doesn't allow you to fork anymore because of that, you can delete existing forks to make room. This is preferable since running in VSCode would require installing Node, which doesn't come until later in the section, and moving that lesson backwards will cause a lot of issues for people in certain lessons who may end up missing extremely important things.

If you're happy to add this note box to the lesson, let me know and I can assign this issue to you.

**Comment by harisalimughal** [comment]
Yeah sure, I will add the note box to the lesson. Please assign the issue to me.
