### ISSUE TITLE
Webpack lesson: Tutorial bug fix

### ISSUE THREAD

**Issue by dawrentz** [TheOdinProject/curriculum#28414]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Hello! I've been working through your curriculum and came across an issue that may be worth nothing on the [Webpack lesson](https://www.theodinproject.com/lessons/node-path-javascript-webpack). 

While following [Webpack’s “Development” tutorial](https://webpack.js.org/guides/development/), I found that after running `npm install --save-dev webpack-dev-server` and then `npm start`, my dist/index.html would be deleted whenever I edited src/print.js while running `npm run watch`. 

I was able to fix the issue by adding `cache: false` to my html-webpack-plugin the options in my webpack.config.js, like so: 

![image](https://github.com/user-attachments/assets/a14d12db-3db3-4489-9bbe-ded830dcc0c4)

I believe this had something to do with `clean: true` and the src/index.html not having any edits on the rebuild. I found that solution here: [](https://github.com/webpack/webpack/issues/10761)

Anywho, thanks for the great curriculum and take care!

-Joshua

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-webpack

### (Optional) Discord Name

joshua.g.martin.email@gmail.com

**Comment by MaoShizhong** [comment]
This wouldn't be a bug. From the sounds of it, your `watch` npm script runs `webpack --watch`, i.e. upon every change to the dependency graph or other files in the bundle, re-run the bundling. When that happens, the `clean: true` option under `output` will clear your `dist` directory before it outputs the resulting bundle into it.

This doesn't have anything to do with `webpack-dev-server`. If you're using the dev server, you won't need to also run `webpack --watch`. The dev server is standalone, then once you're ready to bundle and deploy, you bundle then deploy `dist`.

If you want to use webpack's watch mode, then you won't use `webpack-dev-server`.

What's happening is that because you haven't set a template for HtmlWebpackPlugin, it's going to delete everything in `dist` (including any changes you made to `dist/index.html`) before it bundles. What you're supposed to do as per the lessons and Restaurant Page project, is have an HTML file in `src`, then set that as the template for HtmlWebpackPlugin. You don't do any development work in `dist` at all - that's reserved purely for what Webpack outputs when you bundle things.

If you're still having problems with understanding any part of the Webpack lessons, feel most free to pop in our community Discord and write up a detailed and specific question, and I'm sure someone will be able to help you with whatever issue you're running into!

**Comment by dawrentz** [comment]
Thanks, Mao. I'll take a look at it again and make sure I'm getting it.
