### ISSUE TITLE
Advanced HTML and CSS course: Add another source that discusses how transforms are applied

### ISSUE THREAD

**Issue by Victor-M-Giraldo** [TheOdinProject/curriculum#28415]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Currently when discussing the chaining of transform operations the curriculum links to this link on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/transform#values). It states "“The transform functions are multiplied in order from left to right, meaning that composite transforms are effectively applied in order from right to left.”

I struggled quite a bit with this concept since to me it was more intuitive to read them left to right and MDN doesn't really explain the difference too well.

I asked in the Discord yesterday for some clarification, and somebody provided [this](https://codepen.io/bali_balo/post/chaining-transforms) an an additional source which cleared things up for me a lot.

I think it might be beneficial to add it as an additional resource if others are struggling with something similar.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-transforms

**Comment by MaoShizhong** [comment]
Thanks for opening this issue @Victor-M-Giraldo.
That article you linked used to be in the lesson but was removed in #27096 because it's actually incorrect. Transform order **does** matter, and it's read from right to left. You can see very clearly in the TOP lesson's example where it has the exact same transforms but flipped in order, and the outcome is completely different.

The error that the linked article makes is that is demonstrates rotating first then translateX, assuming that the rotation changes the direction of the axes (hence making translateX go diagonally). It doesn't, it still goes horizontally despite rotating first.

In the second example in that article (right-to-left), it translates first but because the `transform-origin` remains where it originally was, rotating second rotates around that, so the whole thing "swings" and ends up in a completely different position from before. You can test this out yourself and play around with transform orders - it *does* matter, which is why you removed that article that says it doesn't matter.

Agreed though, the MDN bit is a bit funky with its wording. When it refers to "multiplied from left to right", it's talking more about the way the maths is done behind the scenes. The important part is that the functions are effectively read right-to-left.

What do you think of replacing the following wording:

> If you guessed correctly, congratulations! But this is a tricky concept. There is a bit of debate on how to read a chain of transform functions. According to [MDN’s transform docs](https://developer.mozilla.org/en-US/docs/Web/CSS/transform#values): “The transform functions are multiplied in order from left to right, meaning that composite transforms are effectively applied in order from right to left.”

to

> If you guessed correctly, congratulations! But this is a tricky concept. MDN’s transform docs state that ["composite transforms are effectively applied in order from right to left"](https://developer.mozilla.org/en-US/docs/Web/CSS/transform#values).
> 
> The blue box rotates 45 degrees on the spot, then translates on the X axis by 200%, moving it directly to the right. The red box translates by 200% first, so moves to the right, but the transform origin is still where it used to be. Therefore, it rotates 45 degrees around that original point, making the red box "swing down" to end up diagonally from where it started.

Does that make the process clearer? If you're happy with that wording, I can assign this issue to you to make that change.

**Comment by Victor-M-Giraldo** [comment]
Yes it definitely does make the process clearer. I would be happy to be assigned to this issue.
