### ISSUE TITLE
Factory Functions and the Module Pattern: <Amend links in Knowledge Check>

### ISSUE THREAD

**Issue by Meltasy** [TheOdinProject/curriculum#28419]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the Knowledge check, the link in the first 2 questions refer to articles not covered / referred to during the lesson. It seems strange to me as this hasn't happened in previous lessons. However, I would suggest different ways of amending the two questions:
Q1: Currently the link takes us here: https://wesbos.com/javascript-scoping. I would suggest changing the link to take us back to the section in the lesson **Scoopfuls of scopes** (https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern#scoopfuls-of-scopes).
Q2: Currently the link takes us here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures#closure. I would suggest changing the link to take us back to the section in the lesson **Closures aren't scary** (https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern#closures-arent-scary). Then I would also amend the final sentence in the final paragraph of that section to read something along the lines of: 'If you're still confused, read this article on closures [add link: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures#closure] up to "Emulating private methods with closures" as that will be discussed later in this lesson.'

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern

### (Optional) Discord Name

Meltasy

### (Optional) Additional Comments

I'd be happy to make any necessary changes if needed, but please note that this would be my first time.

**Comment by MaoShizhong** [comment]
Looks like those two KC questions' hrefs were an oversight from when previous changes happened, but forgot to also change those hrefs. Good spot and thanks for raising the issue. I like your suggestions - I'll assign this to you.

While we're at it, all of the KC questions there aren't actually questions but statements. Could you also reword each of them to be phrased as questions instead?

The acceptance criteria is as below.

## Acceptance criteria

- [ ] First KC question href is changed to link to the "Scoopfuls of scopes" section
- [ ] Second KC question href is changed to link to the "Closures aren't scary" section
- [ ] "Closures aren't scary" section ends with a short sentence linking to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures#closure. The link text must be sufficiently descriptive by itself.
- [ ] All KC questions' text are rephrased to be questions instead of normal sentences.
