### ISSUE TITLE
Introduction To React Testing: <Mistake in the assignment the articles use Jest>

### ISSUE THREAD

**Issue by BodiAli** [TheOdinProject/curriculum#28469]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

in the assignment section exactly the last point it should be the articles use Enzyme not Jest because the curriculum already uses Jest

### Path

Ruby / Rails, Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-react-testing

**Comment by MaoShizhong** [comment]
Thanks. The Jest bit is actually correct because the React course uses Vitest for testing, not Jest. However, both the first assignment article and last one use Jest+Enzyme together.

I'd suggest extracting the individual notes about Jest/Enzyme from the first and last assignment steps, and putting them in a single [note box](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md#note-boxes) at the top of the assignment div.

Assigning this to you
