### ISSUE TITLE
Git foundations - Cheatsheet: That's how the terminal in general operates, not just git

### ISSUE THREAD

**Issue by sosafacun** [TheOdinProject/curriculum#28552]
### Checks

- [x] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

[In git/foundations_git/git_basics/git/foundations/cheatsheet](https://github.com/TheOdinProject/curriculum/blob/main/git/foundations_git/git_basics.md#cheatsheet) there's a slight error when explaining how git from the terminal works.

> The basic Git syntax is program | action | destination.

Shouldn't it be:

> The basic **terminal** syntax is program | action | destination **/ parameters**.

And then provide other examples other than git (apt install program -y)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-git-basics#cheatsheet

### (Optional) Discord Name

mr_kiwi_

### (Optional) Additional Comments

Loving the project so far

**Comment by MaoShizhong** [comment]
I wouldn't consider it an error. That *is* the basic syntax for Git commands, and that lesson needn't go into anything more complicated than that since it's just the basics of Git.

Not all terminal commands follow that exact syntax. Some do, but that's just because they were made that way and that way would've been intuitive for them. But commands like `ls` don't necessarily follow that strict structure, nor a bunch of other built-in commands or future programs you'd run in the terminal.

**Comment by sosafacun** [comment]
I'm sorry, my original comment might've been a little to harsh on this. It's not an error, but it is misleading.

My understanding of the built-in commands is that they still follow that principle but explicitly since they are unrepeatable and constant. Using Ubuntu as an example you can think of them as "[bash] | action | destination / parameter"

bash mkdir new_folder
bash cd new_path
bash rm old_folder

**Comment by MaoShizhong** [comment]
You'll find that `bash cd <path>` and similar won't work, because it's not just that `cd <path>` silently applies `bash` at the start. `bash` is its own command, where you could run something like `bash -c "ls"` to do the same thing as `ls`, but `bash` isn't part of the `ls` bit - it just runs the script you give it, so you could do `bash -c "git status"` for example.

But that's just me being pedantic anyway. The main thing is that I wouldn't call the lesson "misleading". Besides not all terminal commands (built-in or not) following that basic structure, the lesson is about Git and the cheatsheet is about git commands, so it's perfectly reasonable for it to say that the basic Git syntax is as demonstrated, and not suddenly talk about "terminal commands" in general. Since there isn't an error in the lesson itself and the current wording is reasonable for the subject matter, I don't think any change is necessary so I'll close this issue. Still, thank you for raising the point for discussion!
