### ISSUE TITLE
Installing Ruby: <Short description of your suggestion>

### ISSUE THREAD

**Issue by vishravd** [TheOdinProject/curriculum#28570]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Installed homebrew but kept getting brew: command not found. Finally I realised that I had to add brew to my PATH. Heads up would be nice. 

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-installing-ruby

**Comment by JoshDevHub** [comment]
These instructions frankly shouldn't exist in the Ruby installation section. Learners should have already installed homebrew in the [setting up git lesson](https://www.theodinproject.com/lessons/foundations-setting-up-git#step-10-install-homebrew) back in the Foundations course. These installation instructions do tell users on silicon macs that they need to add homebrew to their PATH. I'll also say, if you haven't done the foundations course @vishravd , I *strongly* recommend that you do so before proceeding with the Ruby course.

As for this specific problem, I think we can change this step to tell people to check that previous lesson if for whatever reason they don't homebrew installed on their machine. Since you indicated you don't want to make the PR for this, I'll open it up for anyone to contribute to.

### Acceptance Critera
- [ ] For step 1.3 of the MacOS installation instructions in the [installing ruby lesson](https://www.theodinproject.com/lessons/ruby-installing-ruby), tell users that they need to have homebrew installed. They can run the command `which brew` to check if it's installed. If the command outputs a path, they're good to proceed to the next step in the installation. But if their terminal says `brew not found`, they should reference the [MacOS instructions in the setting up git lesson](https://www.theodinproject.com/lessons/foundations-setting-up-git) to get homebrew installed.

Comment below to be assigned.

**Comment by vishravd** [comment]
Okay thanks. I'll look at the foundations course again. Just wanted to skip ahead and see what Ruby is actually like.

**Comment by mathdebate09** [comment]
I'd love to work this fix up :)

**Comment by CouchofTomato** [comment]
@mathdebate09 All yours
