### ISSUE TITLE
Form Validation with JavaScript: wrong form validations link

### ISSUE THREAD

**Issue by lcarlo23** [TheOdinProject/curriculum#28630]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The current link points to https://www.theodinproject.com/lessons/intermediate-html-and-css-form-validation.
It should point to https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-form-validation.

I noticed the error because when visiting the link, it wasn't marked completed, and the course was at 0% completion.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-form-validation-with-javascript

**Comment by MaoShizhong** [comment]
Thanks for opening the issue.

The current link goes to the version of the lesson in the Ruby on Rails pathway.
Since the Intermediate HTML/CSS course is shared between the two, that lesson uses the same lesson file regardless of pathway, but each pathway has its own link. Whatever we choose, people in the other pathway will be sent to the "wrong" page. Since that link is just a reference link back to a previous lesson and not necessarily one that's a direct and bigger part of the current lesson assigned content, it's not particularly important which pathway link is used so no change is necessary here. We don't really need all of our links referencing past lessons to be double with "Full Stack JavaScript version" and "Full Stack Ruby" version etc.
