### ISSUE TITLE
Ruby: Basic Enumerable Methods: <Href not linking back>

### ISSUE THREAD

**Issue by DTEXETD** [TheOdinProject/curriculum#28689]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The `What does the #each_with_index method do?` on `Knowledge Check` links to the beginning of the page

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-basic-enumerable-methods

**Comment by JoshDevHub** [comment]
Thank you for making this issue @DTEXETD ! This is definitely a problem.

Since you indicated that you don't want to work on this yourself, I'll open it up to other contributors

### Acceptance Criteria
- [ ] In the [Basic Enumerable Methods lesson](https://www.theodinproject.com/lessons/ruby-basic-enumerable-methods), change the href on the `each_with_index` knowledge check to `#the-eachwithindex-method` (so strip out the underscores)

Comment below to be assigned.

**Comment by mathdebate09** [comment]
Hey josh, I can work these up!

**Comment by JoshDevHub** [comment]
Awesome @mathdebate09 thank you for volunteering. I'll assign you.
