### ISSUE TITLE
ReactJS: Update boilerplate code generated by vite in main.jsx

### ISSUE THREAD

**Issue by Legalunicorn** [TheOdinProject/curriculum#28680]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Currently, `main.jsx`  in the lesson is as such
```jsx
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.jsx";
import "./index.css";

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```
In the latest vite version, I've observed that it has been changed to 

```jsx
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './index.css'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
```

Changes in the explanation to the boiler plate code below should be updated as well. 
For example: 
> We import React itself and its fellow ReactDOM package.

Vite no longer import React itself.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-setting-up-a-react-environment

### (Optional) Discord Name

legalunicorn

### (Optional) Additional Comments

I'm not sure if I'm doing this right or if this is even an issue. Its my first time dealing with a shared repository in general, any guidance would be greatly appreciated. I'm not too sure the difference between `ReactDOM.createRoot` and `createRoot` myself so I decided not to work on this issue, especially with the explaining part in the lesson

**Comment by MaoShizhong** [comment]
Opening a repo issue is 100% the right thing to do :+1: 

Sounds reasonable to me - can confirm the latest v5.5.2 of their create-config tool has this updated boilerplate.

There's no difference between the two. `React` and `ReactDOM` were default imports that'd import a whole object containing many properties, like `React.StrictMode`. Those packages also named export the individual properties, so we can import them separately. The current Vite React template has changed to named import what it needs, instead of default importing the whole objects, that's all. Same as how we can `import { useState } from 'React';` and call `useState()` on its own, but also do `import React from 'React';` then call `React.useState()`.

Opening this up for assignment since you specified you didn't want to work on this.

## Acceptance criteria

- [ ] [Setting Up a React Environment](https://www.theodinproject.com/lessons/node-path-react-new-setting-up-a-react-environment) has its `main.jsx` boilerplate amended to the current boilerplate generated by our Vite create command.
- [ ] Default imports for `React` and `ReactDOM` should be changed to their appropriate named imports in similar examples in:
  - [ ] [React Components](https://www.theodinproject.com/lessons/node-path-react-new-react-components)
  - [ ] [React Router](https://www.theodinproject.com/lessons/node-path-react-new-react-router)

**Comment by mathdebate09** [comment]
Hey mao, I could work this issue up :D

**Comment by MaoShizhong** [comment]
Assigning you @mathdebate09.

Use double quotes and use semicolons to be consistent with the rest of our lessons (most of them anyway). We can't exactly lint this with markdownlint but I'm probably going to make sure our layout style guide has code style rules for each major language we use a lot (html/js/rb).

**Comment by Legalunicorn** [comment]
Hi, I think the explanation steps below the boilerplate code should be updated as well, apologies if it wasn't clear.

These are referencing the old template.
> 1.We import React itself and its fellow ReactDOM package.

I suggest removing this, or stating we import StrictMode, which will be explained later .

> 4.We create a root object by invoking ReactDOM.createRoot with an element from our index.html.

It's no longer `ReactDOM.createRoot` so now its just `createRoot`

![_test](https://github.com/user-attachments/assets/8fff5461-56b9-4ff1-9e14-2f043ce34891)

**Comment by MaoShizhong** [comment]
@Legalunicorn ah, you're right, that's my bad for missing that. Would you like to PR the fix for that?

**Comment by mathdebate09** [comment]
If it's okay maybe I can update that PR / open a newer one

**Comment by Legalunicorn** [comment]
I wouldn't mind trying. Could I have your input if the following is fine or should be changed?
1. We import `StrictMode` and `createRoot` from the `react` and `react-dom` packages respectively.

**Comment by MaoShizhong** [comment]
@mathdebate09 let's let @Legalunicorn have a crack at this one :D

@Legalunicorn - looks good to me. Also removing the `ReactDOM.` bit from step 4
