### ISSUE TITLE
Intro to CSS: <Image for type selector shows p coloured white as well when the description says only the selected div elements should be coloured white.

### ISSUE THREAD

**Issue by Darkest-Chocolate** [TheOdinProject/curriculum#28695]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

It is just an issue of the image being wrong if i am right. Just need a new image for the description to make sense

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-intro-to-css

### (Optional) Discord Name

Darkest Choc

**Comment by MaoShizhong** [comment]
![Screenshot_2024-08-24-11-37-01-05_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/a11dd258-c9d0-4080-9329-bb5e45901f95)

If you're referring to this, the "white text" in the HTML isn't white because of the CSS. The CSS affects what you see when you open the HTML in a browser, i.e. your website.

The CSS won't change the colour of your HTML code at all - that's just the theme our syntax highlighter uses. You'll notice in other examples, the inner text in HTML is always white.

**Comment by Darkest-Chocolate** [comment]
You are absolutely right, I kinda forgot it was default white 😅. Thanks for the clarification
