### ISSUE TITLE
npm: QUIZ for every user

### ISSUE THREAD

**Issue by Mararovsek99** [TheOdinProject/curriculum#28725]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

It will be fantastic to have some quiz for every user of odin.

Like 5min quiz for everything that user learned in the past.
The user must solve one quiz every day.

Because, now i am using chatGPT to make me some random questions about all thing i learned.
It is too much information , and its cool to remember some teoretical things.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons

### (Optional) Discord Name

/

**Comment by GuenounouAlem** [comment]
There is already 'Knowledge Check'  isn't that a quizz ?

**Comment by Mararovsek99** [comment]
yea, but this is just for current new stuff that you learn. and not for all
the stuff you learned in the past.(from the start).


[image: photo]
Andrej Marovšek
CNC programer / Serviser / Konstrukter, Ostri d.o.o.

+386 51 218 722 <+386+51+218+722>  |  www.ostri.si  |  ***@***.***

Celjska Cesta 2b <https://maps.google.com/?q=Celjska+Cesta+2b>


V V sob., 31. avg. 2024 ob 21:22 je oseba Guenounou Alem <
***@***.***> napisala:

**Comment by sukairaida** [comment]
@Mararovsek99 You are not expected to memorize everything in the curriculum. You will learn new things as you progress and forget old ones, but since you have been exposed to them now, you will be able to look them up in case you need them.

Exactly because "it is too much information" is that no one is expected to recall everything by memory, please read this: https://dev.to/theodinproject/memorization-and-learning-to-code-1b6h

**Comment by Mararovsek99** [comment]
Thanks.
[image: photo]
Andrej Marovšek
CNC programer / Serviser / Konstrukter, Ostri d.o.o.

+386 51 218 722 <+386+51+218+722>  |  www.ostri.si  |  ***@***.***

Celjska Cesta 2b <https://maps.google.com/?q=Celjska+Cesta+2b>


V V ned., 1. sep. 2024 ob 18:20 je oseba Jean ***@***.***>
napisala:

**Comment by wise-king-sullyman** [comment]
I agree that the idea of comprehensive quizzes doesn't really match with our approach to teaching. For us the "quizzes" are the projects.

That being said I'll leave the floor on this open for any additional thoughts, cc @TheOdinProject/maintainers

**Comment by MaoShizhong** [comment]
Agreed that comprehensive quizzes don't really align with how we wish to teach things, especially since we heavily promote *not* focusing on memorisation.

We already have the knowledge check sections which are explicitly not a quiz but just a recap of the main points of the lessons, and yes, the projects are the main parts for practice.

**Comment by JustWaveThings** [comment]
@Mararovsek99, I'm not sure if you are aware but your email signature is being appended to your messages here. I only bring that up because it seems like you are linking to your physical location, which could be a security concern for you or your family. Just wanted to make you aware.

**Comment by 01zulfi** [comment]
@Mararovsek99 thanks for the suggestion.

I agree with what has been said above. Quizes are not in the spirit of TOP. I'm closing the issue; do share any other thoughts below.
