### ISSUE TITLE
A Deeper Look at Git: <Short description of your suggestion>

### ISSUE THREAD

**Issue by ofgaard** [TheOdinProject/curriculum#28732]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

This text has an example of an issue which I think generally applies to the entire otherwise good tutorial.

Look at this and see if you notice something missing (hint: this is the first time squash is ever mentioned in TOP):

_Using squash for our commits is a very handy way of keeping our Git history tidy. It’s important to know how to squash, because this process may be the standard on some development teams. Squashing makes it easier for others to understand the history of your project. What often happens when a feature is merged, is we end up with some visually complex logs of all the changes a feature branch had on a main branch. These commits are important while the feature is in development, but aren’t really necessary when looking through the entire history of your main branch.

Let’s say we want to squash the second commit into the first commit on the list, which is Create first file. First let’s rebase all the way back to our root commit by typing git rebase -i --root. Now what we’ll do is pick that first commit, as the one which the second commit is being squashed into_

You see it?

Yeah, nowhere in there does it actually explain what 'squashing' is. It vaguely, sort of kind of describes its overall benefits, but it doesn't say precisely what it is or does. It could simply say, for example, 'Squashing a commit in Git means that you are taking the changes from one commit and adding them to the Parent Commit.'

Leaving this out does not fall under the category of helping people help themselves/not holding peoples hands etc. It's just an error, plain and simple. And I see a lot of them throughout the tutorial. And if they happen to show up at a point where people are already struggling, it can be the straw that breaks the camels back, so to speak, and have people trail off or give up studying for the day.

I don't mean to be ungrateful, and I know it's easy for me to criticise an enormous body of work that I myself can't be bothered to contribute to, but this is just advice that I think could make the tutorial better with minimal effort. Take it or leave it

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-a-deeper-look-at-git

**Comment by sukairaida** [comment]
In my opinion, the meaning of the word "squash" already implies what it does, and in the example you gave the sentence "Let’s say we want to squash the second commit into the first commit on the list" makes it even more clear.

Keep in mind that The Odin Project is a free resource that is mantained by volunteers. You could have gone directly to the point with your suggestion instead of putting an excerpt of the lesson to make them try to guess what you think is wrong with it. You also come as condescending, demanding and the whole "breaks the camels back" paragraph just reads as a guilt trip. I am sorry if it is out of place for me to say these things but this is not the way to make a suggestion or to ask for things.

**Comment by ofgaard** [comment]
"Keep in mind that The Odin Project is a free resource that is mantained by volunteers."

I am very aware of that, which is why I've waited until this point in the tutorial to give this feedback which is, as I said, relevant for the whole course - or from beginning up until now, at least.

"You could have gone directly to the point with your suggestion instead of putting an excerpt of the lesson to make them try to guess what you think is wrong with it. [...] his is not the way to make a suggestion."

This is exactly the way to make a suggestion. The excerpt was not added to make people 'try to guess what I think is wrong' (I point it out directly underneath) but to back up what I'm saying with an actual example  so it hopefully comes across as clear rather than just something I think or feel but can't back up.

"You also come as condescending, demanding and the whole "breaks the camels back" paragraph just reads as a guilt trip."

Sorry you feel that way, but the point is there merely to underline how clear communications is important in a course like this. At the end of the day, I assume the creators of Odin would like to offer the best possible course.

I respect that you think my way of giving this feedback was condescending. As you can see in the last few lines of my first post, I am aware of the relationship between me and Odin (they are offering a product made by volunteers and I'm using it for completely free) so I know it can come off as ungrateful. I hope it'll be taken in the right spirit though: As a piece of advice that can easily be implemented and improve the curriculum. I work with communication on the daily (which I hate hence why I'm trying to learn coding, but I digress), so usually I would be charging for advice like this. I think going through this course would be 30-40 % easier if the writing was clearer.

**Comment by SumonGFC** [comment]
I noticed this too when I went through this lesson. The command was not (explicitly) explained, so I just went to the git book to see what squash did and I figured it out there. That said, I think the lesson should indeed explain what the command does within the interactive rebase tool, perhaps in just a sentence that comes before the "Using `squash` for our commits..." sentence. Although the name "`squash`" is somewhat self-explanatory, it might be nice to have an actual explanation of the command.

@ofgaard Since this is your first issue, and since you are already on the Intermediate Git course, I think this would be a good opportunity for you to work on this issue yourself. At the end of the Intermediate Git lessons (i.e. "Using Git in the Real World"), the curriculum takes you through how to contribute to this repo (and how to contribute to open source projects in general).

So if you would like, you can check the "Would you like to work on this issue?" box, propose a change that would fix this issue (by editing the original issue and appending your proposed change), wait for a maintainer to review the issue and your proposed change, and then make the change and try to get your PR accepted.

If not, no worries. If maintainers think it's a good idea to have the `squash` option explained explicitly, then I wouldn't mind working on this.

**Comment by bycdiaz** [comment]
@ofgaard I agree there is merit to your suggestion but also agree with @sukairaida about how you chose to express that.

Going forward, be mindful about how you choose to raise issues on our repo. Thank you.

**Comment by MaoShizhong** [comment]
Echoing the above, wouldn't be opposed to adding a little extra to the first squash sentence:

> Using `squash` for our commits is a very handy way of keeping our Git history a little tidier by combining multiple commits into one.

**Comment by ofgaard** [comment]
> @ofgaard I agree there is merit to your suggestion but also agree with @sukairaida about how you chose to express that.
> 
> Going forward, be mindful about how you choose to raise issues on our repo. Thank you.

@bycdiaz I don't agree with @sukairaida  – I believe they completely misread my question. There's absolutely no malice in my original post, rather I'm just being clear in my communication and even provide an example to help. 

Since you think I should 'be mindful about how I choose to raise issues', do point out exactly what part of my suggestion is out of order. So I know.

**Comment by bycdiaz** [comment]
@ofgaard I share the concern that was pointed out in @sukairaida's 2nd paragraph.

We are grateful that you are willing to help create a better tutorial. And you're right that you can easily just not make suggestions. If you believe that there is nothing wrong with the way you've chosen to raise this issue, I agree with you that it would be best to just not make suggestions.

Thanks

**Comment by ofgaard** [comment]
@bycdiaz 

which concern exactly? this: "You also come as condescending, demanding and the whole "breaks the camels back" paragraph just reads as a guilt trip."?

**Comment by bycdiaz** [comment]
@ofgaard I share all the concerns expressed there.

**Comment by ofgaard** [comment]
@bycdiaz Got it, so which part of my post is condescending and demanding in your view?

**Comment by bycdiaz** [comment]
@ofgaard Please reread the comment where the concerns were initially raised. I agree with each part.

I think indicating exactly what the issue is instead of asking the reader to read everything and ask them if they see the issue isn't productive.

Expressing that you are critiquing a body of work that you can't be bothered to contribute to does not put you in a good light. The phrase "take it or leave it" also does not inspire me.

Given your background in communication, I am confident you can imagine how these remarks would land.

Thank you for raising the original issue.

**Comment by MaoShizhong** [comment]
I agree with what has already been said about the way it was put forward. Ideally, the issue is explained simply and clearly, and any proposed changes also laid out clearly. No need for any "see what the problem is here?" as that can definitely be seen as unnecessary and in some tones, condescending. Also echoing what Carlos has said above.

The issue has now been completed, so thank you for raising the original issue though. We need not continue the conversation as I think enough has been said already.
