### ISSUE TITLE
Restaurant Page: <Removing dist from .gitignore?>

### ISSUE THREAD

**Issue by Suqbs** [TheOdinProject/curriculum#28745]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the .gitignore section, it says ignoring dist file is a good thing. In the assignment section article 8, it gives us this link [gist about deploying your dist subdirectory to GitHub pages](https://gist.github.com/cobyism/4730490) and wants us to follow through and we need to remove dist from .gitignore in order to accomplish what said in that link. So, it confused me because i thought pushing dist is an unwanted thing. Thank you for reading.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-restaurant-page

### (Optional) Additional Comments

<3

**Comment by MaoShizhong** [comment]
You don't need to push the `dist` folder to your main or any feature branches because it's a folder that can be generated by just running your build command (e.g. `npx webpack`).

For the deployment step, it is actually necessary because we're deploying. We're not pushing the `dist` folder to our main branch. We're pushing *the contents* of the `dist` folder to a deployment-specific branch for GitHub to deploy the site from.

Later in the curriculum when we use other host providers for our websites, you won't even need to do this because the host providers will build and serve from `dist` automatically. Hope that makes sense?

**Comment by Suqbs** [comment]
Thank you for your response first. I know github pages is just a temporary step to publish our work. Thank you for pointing that out because it is easy to fall into a rabbit hole. 

I have one question though. You said "_We're pushing the contents of the dist folder to a deployment-specific branch for GitHub to deploy the site from_."  In that link that i mentioned in the post, we first commit it to the branch and we use git subtree push command to push the contents of the dist directory and eventually we push our work to master branch too and now git recognizes and pushes dist to our master branch. That was what i wanted to said. 

I know this is not that important because we are not using in it real life but, sometimes curiosity kicks in.

**Comment by MaoShizhong** [comment]
At first, `dist` should be ignored. If you forget and it ends up in the main branch, no big deal - it's just not needed at all because people should be able to clone the repo, run the build command, then get their own `dist`.

When you've finished and are ready to deploy, you can unignored `dist` so you can commit it then use that subtree command, which unpacks the folder and pushes its contents to a separate `gh-pages` branch (it doesn't push the `dist` folder itself, only its contents).

I'll close this issue since there's no action currently required, but if you have further questions then you can always ask in our Discord community and I'm sure someone will be able to help you out :+1:
