### ISSUE TITLE
NodeJS: Environment Variables: Dotenv Package is no Longer Necessary

### ISSUE THREAD

**Issue by columk1** [TheOdinProject/curriculum#28742]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Issue
Since Node 20.6 was released (which is in LTS) there is no need to use the dotenv package to load environmental variables. Variables can be loaded natively with the --env-file flag. Here's an example: `node --env-file=.env app.js`

### Suggestion
There are three lessons that instruct students to install and use dotenv in the NodeJS curriculum. We can remove all of these references to dotenv. We could optionally include a note in the Environmental Variables lesson mentioning that it used to be required, in case anyone comes across it in the wild.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-environment-variables

### (Optional) Discord Name

columk

**Comment by MaoShizhong** [comment]
Thanks Colum. Mentioning dotenv was an intentional decision because Node CLI's `--env-file` option is only experimental in LTS (still experimental in v22.X as well). So for now, I'll close this issue since no action is required yet.

Once it has stable support in LTS, the env lesson can be amended to use `--env-file` with a passing mention of dotenv (the same went for Node's `--watch` mode and Nodemon originally, though that entered stable support in LTS before we released the milestone).

**Comment by columk1** [comment]
Ah okay, that makes sense thanks. I see the stability index now.
