### ISSUE TITLE
Form Validation: broken link - HTML5Pattern 

### ISSUE THREAD

**Issue by smith109** [TheOdinProject/curriculum#28749]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The link for HTML5 patterns in the additional resource section is broken.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-form-validation

### (Optional) Discord Name

retro

**Comment by JoshDevHub** [comment]
Yep, looks like that link isn't functioning correctly. Since you indicated you don't want to work on this, I'll open it up for others to work on.

### Acceptance Criteria
- [ ] Remove the "HTML5 Patterns" link in the Additional Resources section of the [Intermediate HTML and CSS Form Validation lesson](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-form-validation)
    - optional: if you can find a replacement resource, feel free to change to that. I would advise not spending much time/effort looking for one though.
    
Please comment below to be assigned.

**Comment by SeanAverS** [comment]
Hello,

I would like to be assigned if this is still available. Thanks.

**Comment by ShehzadaSalman** [comment]
Hey, I'm available to work on this

**Comment by Rajaravi99** [comment]
Hi, I am also available, if you guys need any help

**Comment by JoshDevHub** [comment]
@SeanAverS I'll assign you to work on this. Let me know if you have any questions.
