### ISSUE TITLE
React Course:  Passing Data Between Components, ".defaultProps ={}"  will be losing support.

### ISSUE THREAD

**Issue by amauget** [TheOdinProject/curriculum#28752]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I'm working through the react module "Passing Data Between Components" that introduces default props. My browser threw an error saying this method will be losing support, and the google search seems to have confirmed. Just a heads up. Thanks for all you do! Source: https://medium.com/@matanbobi/react-defaultprops-is-dying-whos-the-contender-443c19d9e7f1

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-passing-data-between-components

### (Optional) Additional Comments

Thank you for all that you do!

**Comment by MaoShizhong** [comment]
Thanks for opening this issue @amauget.

While newer versions of React will be dropping support for `.defaultProps` in function components, they will still be usable in class components. Current and older versions of React will not lose support either, meaning it's possible that when you work in other codebases in the future, you'll come across React's `.defaultProps` in some way instead of JS default parameters.

The current lesson just mentions the `.defaultProps` approach for awareness after introducing the standard way of JS default params. This change was made in #28406 to address #27882.

There shouldn't need to be anything that needs changing in our lessons right now, so I'll close this issue.
