### ISSUE TITLE
Deployment: Remove Adaptable.io from recommended Paas list

### ISSUE THREAD

**Issue by black-RAM** [TheOdinProject/curriculum#28784]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Adaptable.io has stopped offering a free tier, so it shouldn't be on the list anymore, or at least the information should be updated.
[Source of Screenshot](https://adaptable.io/pricing#)
![Screenshot_2024-09-12_19-15-35](https://github.com/user-attachments/assets/25e764ce-248a-4675-afde-1624e07d6416)
They explain their decision [here](https://adaptable.io/docs/free-app-hosting#).

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-nodejs-deployment

### (Optional) Discord Name

black.RAM_

**Comment by DrantDumani** [comment]
Maybe Adaptable doesn't need to be removed as a PaaS option and the information can be updated instead. The Ruby path deployment lesson still lists Heroku as an option even though they don't have a free tier (though I don't know if that's an oversight). Adaptable's build plan is also cheaper than Heroku's.

I know that the idea behind using PaaS sites during the curriculum is that we shouldn't be looking to pay for anything we make while following ToP though. So maybe we can keep Adaptable around until other free tier options can be added?

(Initially posted this under the wrong issue. >_<)

**Comment by MaoShizhong** [comment]
Frustrating, given that besides the credit card verification step, it has the most generous free tier of the options.

Personally, I feel it's time for adaptable to go since our lesson lists its recommended PaaS options, and I can't in good faith recommend a paid-only service as part of a free curriculum. In #28491, Fly.io was recently removed for the same reason.

We still have Render, Railway and Koyeb for servers/dbs and Neon for dbs, which is still sufficient so far for the curriculum. We will likely need to reconsider how this part for deployment is approached, but that's a bigger and separate discussion.

**Comment by MaoShizhong** [comment]
@black-RAM Assigned you to remove Adaptable.io from the Node deployment lesson

**Comment by black-RAM** [comment]
> @black-RAM Assigned you to remove Adaptable.io from the Node deployment lesson

Thank you! I have made the edit and opened a (pull request)[https://github.com/TheOdinProject/curriculum/pull/28826]. 

It's my first time contributing, so I'm especially happy :grin: .
