### ISSUE TITLE
Using Git in the Real World (Ruby Course): Link in assignment part directs user to the wrong lesson

### ISSUE THREAD

**Issue by otherdcn** [TheOdinProject/curriculum#28799]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In Ruby's *Using Git in the Real World*, a link in the assignment instructions is directing the user to the *Working with Remotes* lesson in the JavaScript course instead of Ruby's equivalent course.

Issue can be found on the  **Assignment** section, **Ongoing workflow** sub-section, step 5: 
> 5. You may have merge conflicts… resolve those using the skills you learned in [the Working with Remotes lesson](https://www.theodinproject.com/lessons/javascript-working-with-remotes)!

The link in step 5 will send the user to JavaScript
![Screenshot 2024-09-16 at 20 14 15](https://github.com/user-attachments/assets/31d1fec9-3964-49c3-be75-6860d30f68e8)

Instead of Ruby
![Screenshot 2024-09-16 at 20 13 51](https://github.com/user-attachments/assets/f3e089cc-c466-4205-818a-04d87ad410c0)

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-using-git-in-the-real-world#ongoing-workflow

### (Optional) Discord Name

otherdcn

### (Optional) Additional Comments

This is my fist issue submission to **The Odin Project**. Perhaps the issue may seem trivial, but I thought I'd give it a go either way.

Wanna contribute however I can to this great learning platform!

**Comment by MaoShizhong** [comment]
Thanks for opening the issue.

Many of our lessons are shared between both pathways, i.e. we have a single lesson file in markdown, and both pathway's versions of that lesson will pull from the same contents. Because of this, we can't easily and neatly write links for each pathway individually. If we provide only one link, it'll be "wrong" for the other pathway. Two links is messy and given it's only a link to reference a past lesson, it's not too big of an issue that we *must* have two links for every time such a link comes up (happens a lot).

Since there isn't any action that's strictly necessary here, I will close this issue.
