### ISSUE TITLE
Restaurant Page: <Short description of your suggestion>

### ISSUE THREAD

**Issue by hi-its-jack** [TheOdinProject/curriculum#28819]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Hi, I've done this project and I'm up to the last stage on the assignment where it's telling me to deploy it to github pages but I must doing something wrong because when i follow the guide it doesnt work. 

When i type this in the  cli:
     'git subtree push --prefix dist origin gh-pages'

It says i need to be at the top of the working tree or something like that. 

Do you know why this might happen? Should i have created a github repo for the project before i upload it? 

It doesnt say to do that anywhere at the start of the assignment so im a bit confused. 

 Thanks!  

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-restaurant-page

**Comment by CouchofTomato** [comment]
@TheOdinProject/javascript 

Can someone familiar with this project review please.

**Comment by MaoShizhong** [comment]
Thanks for the issue @hi-its-jack 
This is something that will be better suited as a question in [our Discord server](https://discord.com/invite/fbFCkYabZB). GitHub issues are more for bugs/identified problems with lesson material, or suggestions for improvement etc. For now, it may well just be a user error so if you ask your question in our Discord server with as much context as is relevant, people can help you figure out what's going on. It may well be that it results in needing to open a GitHub issue afterwards, or best case scenario it's just a user error that the community can help you resolve :)

I'll close this issue for now since there's no GitHub action to take just yet.
