### ISSUE TITLE
Advanced Selectors:  links to all css-tricks.com pages gives a 404 error page

### ISSUE THREAD

**Issue by Strange-can** [TheOdinProject/curriculum#28876]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Edit: pages seem to have been moved to pseudo-selectors instead of selectors (credits to print("Please reboot Asarta.py") on discord for telling me). E.g.: the :active link at [Dynamic and user action pseudo-classes](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-advanced-selectors#dynamic-and-user-action-pseudo-classes) leads to 
 https://css-tricks.com/almanac/selectors/a/active/ that gives a 404 error page while the new link leads to the desired page: https://css-tricks.com/almanac/pseudo-selectors/a/active/
### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-advanced-selectors

### (Optional) Discord Name

Strange_Can

### (Optional) Additional Comments

![Screenshot (26)](https://github.com/user-attachments/assets/4882e8f6-a815-4397-b0aa-e4f425de8918)
![Screenshot (29)](https://github.com/user-attachments/assets/76d754da-64b7-4315-9b4a-baf382ce2642)

**Comment by MaoShizhong** [comment]
Thanks for reporting the broken links @Strange-can 

It looks like all of the CSS Tricks links for those selectors in the `Pseudo-classes` and `Pseudo-elements` sections need their links updated so they add the `pseudo-` bit to the `selectors` part of their URLs. The `::before and ::after` link also needs the letter in the URL changed from `a` to `b` (so that link should become https://css-tricks.com/almanac/pseudo-selectors/b/after-and-before/).

Since you specified you wish to work on this, I'll assign this to you. Let us know if you have any questions.

**Comment by Strange-can** [comment]
Hi, I would love to help! I'm only unsure on how the fixing process
goes(e.g.how do I get the html file to make edits? do I send a pull request
after editing the file?), right now, I only know how to look for the anchor
tags and change the links.

**Comment by Strange-can** [comment]
Apologies, I completely forgot about the contributing guide. I'll get it
fixed by today.
