### ISSUE TITLE
Revisiting Webpack: Fix grammar from "will" to "may"

### ISSUE THREAD

**Issue by Shumaila-sayed** [TheOdinProject/curriculum#28878]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I noticed that under revisiting webpack lesson of the Node JS path, line 2 of sub-topic "npm scripts" has wrong grammar.
It should be "you **may** have encountered " and not "you **will** have encountered "

![Screenshot (32)](https://github.com/user-attachments/assets/5e20890b-c80d-4be2-9285-93e99ab084d2)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-revisiting-webpack

### (Optional) Discord Name

shumaiilla

**Comment by MaoShizhong** [comment]
Thanks for opening the issue.

We write our curriculum linearly and under the assumption that all prior lessons have been completed. Since that command is part of the Restaurant Page instructions and not an optional part either, I think it makes sense to say that you will have encountered that command and not "may have encountered" that command.
