### ISSUE TITLE
Objects and Object Constructors: no revisitation of the Book constructor mentioned under "Exercise"

### ISSUE THREAD

**Issue by jonorl** [TheOdinProject/curriculum#28890]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Under the Exercise title it says:

> Write a constructor for making “Book” objects. We will revisit this in the project at the end of this lesson.[...]
> 

I got to the end of this lesson and I don't think this is revisited...? Or is it on a different lesson? Or at the end of the course?

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors

### (Optional) Discord Name

jonorl

**Comment by JoshDevHub** [comment]
The very next lesson is the "Library project", where the book constructor will be used as part of making the project.

I agree this language could probably be more clear. Since you indicated you don't want to work on it, I'll open it up to other contributors.

### Acceptance Criteria
- [ ] In the [Objects and Object Constructors lesson](https://www.theodinproject.com/lessons/node-path-javascript-objects-and-object-constructors), change the sentence `We will revisit this in the project at the end of this lesson.` to `We will revisit this in the next project.`

Comment below to be assigned.

**Comment by sarthakvermaa** [comment]
@JoshDevHub Can you assign me this issue?

**Comment by JoshDevHub** [comment]
@sarthakvermaa Certainly! Let me know if you have any questions.
