### ISSUE TITLE
JavaScript: Update binary search example explanation

### ISSUE THREAD

**Issue by Maddily** [TheOdinProject/curriculum#28901]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I noticed a small inaccuracy in the **O(log N) - Logarithmic complexity** section of the **Time Complexity** lesson. The explanation currently incorrectly identifies the middle element for the array in the Binary Search example. Could you take a look at this and let me know if it makes sense?

1. The middle element is incorrectly identified as `6` in the first step:

> One such algorithm that does this is Binary Search. It only works on sorted arrays, but if you have an array of 10 items in sorted order

> `arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];`

> and wanted to know if it had the number `7`, Binary Search would guess the middle item of the array and see what is there. Because the array is sorted, if the number at the middle index was `6`, then we know anything to the left of that index cannot be the number `7`, as those items must be lower than `6` in a sorted array.

In this array, the correct middle element would be `5`, located at index `4`.

2. It incorrectly states that the middle index in the second step would be `8`, but the actual middle index is `7`:

> `arr = [-, -, -, -, -, 6, 7, 8, 9, 10]`

> In this case, the middle index would be `8`...

Additionally, the explanation incorrectly retains the previous middle element `8` while it should be discarded along with the right half:

> ..., and we know that 7 is less than 8 so we can eliminate anything to the right of the number 8.

> `arr = [6, 7, 8, -, -]`

The correct reduced array should be: `[6, 7]`.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-time-complexity

### (Optional) Discord Name

Maddie

**Comment by JoshDevHub** [comment]
Nice find. I think you can also probably be a bit more specific about how the middle element is typically calculated in this context, as sometimes it would be colloquially ambiguous (ie when the array is of even number length). So throwing in a quick formula like `Math.floor((startIndex + endIndex) / 2)` would clearly convey how the middle is calculated for this problem.

I'll assign you to work on this. Thank you for making this issue.

As an aside, this issue is also present in the [Ruby course's version of this lesson](https://www.theodinproject.com/lessons/ruby-time-complexity#olog-n-logarithmic-complexity). In the same PR you fix this issue in, would you also be comfortable doing it there as well? The only things you have to know about Ruby that's different for what you'll be working on:
1. variables are `snake_cased` in Ruby
2. division with integer operands is automatically floored in Ruby, so the formula for getting the middle index can be simplified to `(start_index + end_index) / 2`

Let me know if you're not comfortable making those changes and I can do them myself. Glad to answer any further questions!

**Comment by Maddily** [comment]
I'll work on it and include the formula to calculate the middle index. I'll also make the necessary changes in the Ruby version as suggested. Thank you.
