### ISSUE TITLE
Block and Inline: <Short description of your suggestion>

### ISSUE THREAD

**Issue by HideOnTheBushh** [TheOdinProject/curriculum#29026]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the Introduction section: , and we can modify the box calculation by changing the DISPLAY property. Shouldn't it be box-sizing property?

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-block-and-inline

### (Optional) Additional Comments

The Odin Project is really great and I love it. Don't mean to offend you.

**Comment by MaoShizhong** [comment]
`box-sizing` is a completely different thing to what the lesson is talking about. `box-sizing` refers to what part(s) of the box model `width` and `height` will take into account. The lesson is talking about how the `block` and `inline` display types affect how the entire box model is treated.

No action is required here, so I'll close this issue. Feel free to come to our Discord server and ask any further questions if you need concepts etc. clarified or otherwise need help with something in the curriculum.

**Comment by caminosurfer** [comment]
If I may add my two cents, even though this issue has been closed 3 days ago: I also find this opening-sentence is a bit misleading. I’ve reopened this topic with a new issue for further clarification, with reference [#29043](https://github.com/TheOdinProject/curriculum/issues/29043)
I'd love to hear more about your perspective on this, MaoShizhong, if you'd like to discuss it further. If not, that's perfectly fine too! Thanks again for the opportunity to engage on this topic.

**Comment by MaoShizhong** [comment]
@HideOnTheBushh see https://github.com/TheOdinProject/curriculum/issues/29043#issuecomment-2453238852. I overlooked some context between the two lessons and focused only on the correctness of the sentence which technically is correct (as is `box-sizing`), just the incorrect correct sentence intended. This will be fixed.

**Comment by HideOnTheBushh** [comment]
Thanks a lot! I should have been more specific, I know. My report message didnt make much sense. But thanks again for dealing with it.
