### ISSUE TITLE
Class Based Components: 'Additional resources' points to article which do not contain information on Class Based Components

### ISSUE THREAD

**Issue by 1Amal** [TheOdinProject/curriculum#29048]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Class Based Components lesson, Additional resources points to old Thinking in React document which does not contain information about Class Based Components eventhough lesson indicates:

>  "In general, the React documentation on [thinking in react](https://legacy.reactjs.org/docs/thinking-in-react.html) is a really good place to look into, if you want more practice with class-based components, from scratch."

More appropriate Doc would be [State and Lifecycle](https://legacy.reactjs.org/docs/state-and-lifecycle.html) from the Old React Docs. 
Also replace the text to indicate they are legacy documents for clarity:

> "In general, the legacy React documentation on [State and Lifecycle](https://legacy.reactjs.org/docs/state-and-lifecycle.html) is a really good place to look into, if you want more practice with class-based components, from scratch." 

Also it seems the new [Thinking in React](https://react.dev/learn/thinking-in-react) do not contain information about Class based components. Please review the suggested article and if not appropriate please suggest a different doc/article. 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-class-based-components

### (Optional) Additional Comments

Love "The Odin Project" and  Open Source and really happy to make any contribution I can make !
Kind regards,
Amal

**Comment by CouchofTomato** [comment]
@TheOdinProject/react Can someone take a look please.

**Comment by MaoShizhong** [comment]
Thanks @1Amal. The currently linked doc is their legacy docs and it looks like they've gotten rid of the codesandboxes that used to showcase class components in context. Of course, the legacy docs were what we wanted for this lesson precisely because we're exposing class components instead of function components, which is what the current version of the docs page would use.

In all honesty, instead of finding a replacement resource, I'm happy for this additional resource to be removed entirely, and the default "no additional resources" placeholder put back instead. The state/lifecycle resource you linked won't be necessary since the current version of that (which does use class components) is assigned in the Lifecycle Methods lesson after.

I'll assign this to you to remove.

**Comment by 1Amal** [comment]
Hi @MaoShizhong & @CouchofTomato,
Thanks for assigning this to me and I will work on this as suggested !
Kind regards,
Amal

**Comment by 1Amal** [comment]
Appologies as clicked the "Completed" button by mistake. Will reopen this and work on this !
Kind regards,
Amal

**Comment by 1Amal** [comment]
Hi guys,
Appologies as clicked the "Completed" button by mistake. Will reopen this and work on this !
Kind regards,
Amal
