### ISSUE TITLE
Block and Inline: First line of "Introduction": "we can modify the box calculation by changing the display property" - I think is not true. 

### ISSUE THREAD

**Issue by caminosurfer** [TheOdinProject/curriculum#29043]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

As far as I understand,  the `display` property does not change the box calculation method. The box calculation method — i.e. how an element’s width and height are calculated — is controlled by the `box-sizing` property, no? So I think the introduction paragraph could be rephrased as follows: 

"In the previous lesson, we discovered that different `display` types influence how elements are arranged on the page, while the `box-sizing` property controls the box calculation method. CSS provides two main display types: `block` and `inline`, which determine element behavior and interaction in layouts. The `display` property governs how HTML elements are presented on the webpage. We will explore its various options further in this lesson."

I did see the closed issue [29026](https://github.com/TheOdinProject/curriculum/issues/29026) from [HideOnTheBushh](https://github.com/HideOnTheBushh) and I appreciate the explanation from [MaoShizhong](https://github.com/MaoShizhong), but I believe there might still be a point of confusion around how box calculations work (most probably on my side, that is!)

This is what I took away from the lesson ["The box model"](https://www.theodinproject.com/lessons/foundations-the-box-model) which the introduction is referring to: 

While `display` controls how elements behave and interact (e.g., `block` vs. `inline`), the actual calculation of width and height, including how padding and borders are treated, is determined by `box-sizing`. When the lesson mentions modifying the box calculation, it implies changing the element’s box model behavior, which is specific to `box-sizing`, not `display`.

I’d love to hear more about your perspective on this, [MaoShizhong](https://github.com/MaoShizhong),  if you'd like to discuss further! If not, also ok for me! Thanks again for the chance to engage on this. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-block-and-inline

### (Optional) Discord Name

caminosurfer

### (Optional) Additional Comments

This is my first suggestion here - so I read through everything and sincerely hope that I followed all guidelines, did not miss the issue being addressed again in the open issue list mentioned above and last but nor least: I hope I simply did understand everything correctly and that my interpretation of the particular matter actually is correct. 

And: I greatly appreciate what you guys put together here and how much work everyone of you puts into TOP. I hope one day I might be able to help out as well!

**Comment by MaoShizhong** [comment]
Thanks for the detailed issue. As you can see in this [codepen demonstrating box calculations with different `display` values](https://codepen.io/MaoShizhong/pen/bGXKZeO) (`p`s are blocks and `span`s are inlines), height and width are treated differently depending on the display type, so box calculation *is* affected by the `display` property.

That being said, looking through the context of the two lessons a little more closely, while the Block and Inline lesson's intro is technically correct, I do think it's actually a typo and the intention was to say `box-sizing` instead. Since that's what was introduced in the previous lesson and *this* lesson is about block vs inline displays.

Given that second look, I'm happy to assign you to fix that sentence to reference `box-sizing` instead of `display`, so thanks for bringing this back up :+1: With the original issue, I didn't look deeply enough into the lesson order context and only on the technical correctness (a happy accident I think), so that was an oversight.
