### ISSUE TITLE
Prisma ORM: Change URL for Prisma ORM quickstart documentation

### ISSUE THREAD

**Issue by Preslav977** [TheOdinProject/curriculum#29053]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

Good morning. They changed the Prisma URL for quick start for some reason.

Previously it was prisma/getting-started/quickstart. 

Now is prisma/getting-started/quickstart-sqlite.

If I am not mistaken, I think the page was redirecting to this example.

I am letting you know, because right now it redirects you to a 404 page.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-prisma-orm

### (Optional) Discord Name

Preslaw

**Comment by MaoShizhong** [comment]
Thanks for opening the issue. Which link in the lesson are you referring to? I can't find any with the href you mentioned and all the links in that lesson work fine for me and lead to the right place.

**Comment by Preslav977** [comment]
This one. https://www.prisma.io/orm and if you click quickstart button, it will redirect you to a 404 page.

It wasn't like that yesterday. Sorry, I forgot to specify which link.

**Comment by MaoShizhong** [comment]
I see. That's not something for us to handle since it's not something we link to. Prisma will sort that out in due course, I'm sure.

We only link to the main ORM page just like someone might link to a wiki page or homepage for any other tool or keyword, and the link we use takes you to the right place. Anything within that is an issue on Prisma's side and something individuals explore on their own.

I'll close this issue since it's not one that requires action from us.
