### ISSUE TITLE
Etch-a-Sketch: Clarifying whether project needs to work flawlessly for any number of squares

### ISSUE THREAD

**Issue by kermit-the-hermit** [TheOdinProject/curriculum#29069]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I have one suggestion about point 4 in the task.
I think it should be stated whether in all cases the squares needs to fit inside sketch container.
Some number of squares in my project (and in projects of other learners from what I have seen) cause the squares to overflow. 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-etch-a-sketch

**Comment by MaoShizhong** [comment]
Step 4 already states that any new grid must fit in the "same total space as before", meaning if you input 73x73 for example and some cells overflow, they don't fit in the same total space as before and the requirement has not been met.

It's advisable to avoid using submitted solutions as guides for project requirements (use the actual requirements for that), since people can submit solutions no matter whether they've actually met the requirements or not. Or perhaps the requirements had changed since they submitted, or they went out of their way to do way more than is instructed.

**Comment by rlmoser99** [comment]
Closing this issue, because as previously noted, this point is already addressed in the 4th step.

> Add a button on the top of the screen that will send the user a popup asking for the number of squares per side for the new grid. Once entered, the existing grid should be removed, and a new grid should be generated in the same total space as before (e.g., 960px wide) so that you’ve got a new sketch pad.
