### ISSUE TITLE
No video explaining grid and flexbox

### ISSUE THREAD

**Issue by Punosie** [TheOdinProject/curriculum#29064]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

I would like to add the two video links that explain the concepts of grid and flex with appropriate animations in brief. (15mins)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-advanced-grid-properties

### (Optional) Discord Name

Punosie

**Comment by rlmoser99** [comment]
@Punosie Thank you for taking the time to make a suggestion. However this issue needs to have more context, such as the links to the videos that you want to add, where you want to add them to the lesson, what is useful in the videos that are currently not present in the lesson, and why they are different than the videos currently in the Additional Resources section.

As a heads up, we are pretty hesitant to fill our lessons with videos, because we believe the best way to understand something is hand on practice.

**Comment by Punosie** [comment]
Thanks for the quick response, will keep your suggestion in mind
