### ISSUE TITLE
Rails - Advanced Forms and Active Record: Update section numbers indicated in the Assignment

### ISSUE THREAD

**Issue by bellitabellota** [TheOdinProject/curriculum#29073]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

![image](https://github.com/user-attachments/assets/b5b6c257-8f9b-4798-9d38-c6a2d83b72ba)

1) **In "Querying basics“ bullet point 3 needs to be updated**

      Currently:
      Section 7 is about Grouping
      Section 8 is about Overriding Conditions
      Section 21 is about Calculations
      
      So rather than Section 8, I guess it is another section we should read in this context.

2) **In "Querying basics“ bullet point 4 needs to be updated**

      According to this bullet point, we should read 3 sections about "overriding conditions". 
      
      Currently:
      Section 9 is about Null Relation
      Section 10 is about Readonly Objects
      Section 11 is about Locking Records for Update
      Section 12 is about Joining Tables

3) **In "Advanced querying“ bullet point 2 may need to be updated**

      Section 19 is about Finding by SQL
      
      Is this section indeed the one that we are meant to read to learn about „using SQL directly to query"?
_____________________________

As it seems that the order and numbering of the sections at https://guides.rubyonrails.org/active_record_querying.html has changed, I am a bit worried that we might miss any important new information in this lesson. 

In case I can help resolving this issue I'd be happy to contribute but I am not sure how those sections numbers should be updated.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-on-rails-active-record-queries

**Comment by JoshDevHub** [comment]
Thank you for making this issue @bellitabellota and sorry for the delay on our end for looking at it.

Here is how the items should be updated:
- **Querying Basics 3**: Read sections 7 and 21 to learn about grouping and aggregate functions.
- **Querying Basics 4**: Skim section 8 to learn about overriding conditions.

Your last point is the correct section for learners to read for finding by SQL. If you would like to suggest a rewording to make this more clear, I would be glad to take a look.

Since you indicated you'd like to work on this, I'll assign you. Let me know if you have any questions.

**Comment by bellitabellota** [comment]
Perfect, I will create a pull request for these changes.
Thank @JoshDevHub you for taking the time and helping with updating the assignment instructions.
