### ISSUE TITLE
Installing Node.js: <Short description of your suggestion>

### ISSUE THREAD

**Issue by rzapaja** [TheOdinProject/curriculum#29109]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Information on installing `npm` seems to be missing? 
It's required for the javascript exercises in the next lesson (Arrays and Loops), and the `npm` section in the README for the exercises tells us to come back to this lesson if it's not installed.

Or if it is there somewhere, it's not very clear.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-installing-node-js

**Comment by JoshDevHub** [comment]
`npm` is included with the installation of node. If you've followed the instructions in that lesson for setting up nvm and installing nodejs, you'll have `npm`.

If you have gone through those instructions but are still missing `npm`, then I recommend getting support on that problem using [The Odin Project discord server](https://discord.gg/fbFCkYabZB). Since this isn't a problem with the curriculum content itself, I will be closing this issue. But feel free to ask if you have any more questions on this matter.
