### ISSUE TITLE
Additional Resources' link doesn't work

### ISSUE THREAD

**Issue by akshaybharwani** [TheOdinProject/curriculum#3141]
The link titled 'How to Design a Rails App from CodeLearn' doesn't seem to work and every link directing to CodeLearn domain doesn't work.

**Comment by KevinMulhern** [comment]
Hey @akshaybharwani, thanks for letting us know about this. We will wait a few days to see if it isn't server issues with code learn. If they aren't back up in a few days it would be good to look for an alternative.

**Comment by akshaybharwani** [comment]
Sounds great!

**Comment by KevinMulhern** [comment]
Ok, after a bit of digging it seems codelearn has been in trouble since last year https://twitter.com/codelearn/status/569761954278952960

They might put the site up again, but in the mean time it would be good to be proactive about finding a replacement, if indeed a replacement is needed. Thankfully codelearn was only linked in additional resources.

If we want another interactive course, codecademy has a couple of learn rails courses. I am sure there are other great resources out there that I am not aware of though.

@eriktrautman, @muzfuz what do you guys think about this?

**Comment by akshaybharwani** [comment]
Perhaps we can add http://railsforzombies.org/. It is a good, short and interactive introduction to Rails.

**Comment by KevinMulhern** [comment]
Rails for zombies is already one of the assignments in the rails section of web development 101 http://www.theodinproject.com/web-development-101/ruby-on-rails-basics

**Comment by akshaybharwani** [comment]
Oh, I didn't know that. I directly skipped to the Ruby On rails part as I knew web development. I will be looking for other resources.

**Comment by eriktrautman** [comment]
Unfortunately I haven't found a good interactive Rails tutorial since CodeLearn so we may be out of luck on this one...

**Comment by KevinMulhern** [comment]
I removed all of the codelearn links.
