### ISSUE TITLE
A 'last updated' for every page

### ISSUE THREAD

**Issue by akshaybharwani** [TheOdinProject/curriculum#3381]
Maybe we can add 'last updated' timestamp to every page to reflect when was the last time the page was updated and going further ahead we can also add the changes made to that particular page the last time it was updated. This will help the users to have the information about how up-to-date the site is.

**Comment by KevinMulhern** [comment]
Hey @akshaybharwani, thanks for opening a issue. Are there any lessons that you would deem out of date?

**Comment by akshaybharwani** [comment]
As for the question, not particularly.

And I just had this thought as I've seen many people mentioning that TOP doesn't update its content so often as opposed to other sites. I think having a timestamp will help prevent that. But I may be wrong. And you also got a point, we don't want to send that kinda message.

Maybe a timestamp for the entire course? Anything that conveys that we try to keep the content up-to-date.

**Comment by KevinMulhern** [comment]
Yeah I have been getting the same sort of feedback, I completely agree with you that we need to figure out a way of letting people know that it's still being worked on. I just don't think timestamps are the way to convey it. 

I personally think that people are thinking its out of date because of a few different things. Number 1 being the design of the site, the default bootstrap theme makes it look outdated imo. Also the lack of activity on the Odin Twitter, Facebook and blog would give someone the impression that the project isn't being worked on anymore. I think that making those social channels more active with announcements of what we are working on and about any important changes that are implemented would be the way to go to solve this problem.

**Comment by akshaybharwani** [comment]
I've been meaning to raise an issue concerned with the design of the website but I thought that is already been worked on. And you are right, the inactivity on the social accounts and blog is also a major issue here. I think TOP needs a major overhaul. Maybe ask people on the website to help with that?

**Comment by KevinMulhern** [comment]
Yeah its in the beginning stages at the moment, I was planning on asking for design and front end development help through the different TOP communities. Theres a lot of improvements to be made for sure. The fixes you have contributed all add up to improving the project in a big way though so thank you for that :smile:

**Comment by akshaybharwani** [comment]
You're welcome. And I'm just giving what I'm getting. I believe TOP is one of the best resources to learn Web Development and more people should know about it. And I'd be happy to help anyway. :)

**Comment by KevinMulhern** [comment]
I'm going to close this issue because of the alternative methods we identified for improving this area, thanks for opening it @akshaybharwani. Also if your on our slack, don't hesitate to go to the contributing channel to join in on the conversation about improvements.

**Comment by akshaybharwani** [comment]
Sure thing Kevin!

**Comment by akshaybharwani** [comment]
Sure thing Kevin!
