### ISSUE TITLE
Sublime Text is free to use

### ISSUE THREAD

**Issue by csrail** [TheOdinProject/curriculum#4604]
The sublime pop up keeps tripping users up. They think the prompt means you have to pay to keep using Sublime.

* This obviously isn't the case but since this keeps being a frequent issue it would be a good idea to place a message for new users to see.

* It may be a good idea to also suggest atom as a text editor to use.

Any ideas where to put this notification?

**Comment by codyloyd** [comment]
I agree.. Sublime is the default because that is what the installfest suggests, so maybe putting in a note very near the installfest would be good.   I suspect that many people skim the section right before the actual installing because it is quite lengthy, so I'm not sure where the best place for that note would be.

I also like the idea of mentioning Atom, but it _is_ quite a bit heavier on the resources, so it might be worth mentioning that users on older machines or VMs will likely be happier with sublime.

**Comment by saqib1707** [comment]
That note can be added on the top-right side as a pop up menu when the pop menu of sublime  comes...

**Comment by KevinMulhern** [comment]
@saqib1707 I don't see how that would be possible?

**Comment by codyloyd** [comment]
I think I covered this in my latest PR.. check it out and we can close the issue
