### ISSUE TITLE
Ruby Course: Debugging

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#5508]
This is the lesson details for the proposed "Debugging" lesson in our new Ruby course. If you want to work on this lesson please leave a comment to let us know.

### Description
This lesson will teach the student about arrays and what you can do to them

### Learning Outcomes for Lesson
* The student understands how to read the stack trace
* The student knows how to use puts and print to debug whats happening at certain points in thier programs
* The student is aware of pry and how it works
* The student knows what rubber duck debugging is

### Progress
- [x] Break down lesson into sub headings
- [ ] Introduction -summary of what the lesson is about and why its important
- [ ] Learning outcome list - same as the above learning outcomes
- [ ] Reading the stack trace section
- [ ] Puts debugging section
- [ ] Using PRY section
- [ ] exercises - 5 small basic exercises related to the topics covered in this lesson
- [ ] Extra Resources - add one or two extra resources

### Template for this lesson
[Can be found here](https://github.com/TheOdinProject/curriculum/blob/master/ruby/basics/debugging.md)

**Comment by KevinMulhern** [comment]
**Potential Resources**
http://www.blackbytes.info/2015/07/ruby-debugging/

**Comment by iansowinski** [comment]
**Potenetial Resources**
[MIT SC 6.00 lec 7 on debugging](https://www.youtube.com/watch?v=5gt2WDBl8-0) - in this lecture John Guttag covers the topics of floating point and, mostly on debugging. Lecture is conducted in Python, but I think that at this point it shouldn't be problem for anyone.

**Comment by parhaml** [comment]
**Potential Resources**

**Comment by WendyBeth** [comment]
Hi - I would love to help with this. I was just searching through Confreaks.TV for videos on debugging in Ruby:

One from 2010 - http://confreaks.tv/videos/lsrc2010-debugging-ruby
One from 2013 - http://confreaks.tv/videos/rubyconf2013-effective-debugging
One from RailsConf 2017 - http://confreaks.tv/videos/railsconf2017-practical-debugging

It got me thinking it might be really cool to curate 'lists' of technical talks like this to share as well. I haven't delved very much into the Odin Project Curriculum since back in 2014, so I don't know how much talks are a part of it anymore, but I thought I'd bring that up as well.

**Comment by KevinMulhern** [comment]
Thanks @WendyBeth 😄 those are great finds.
