### ISSUE TITLE
Ruby Course: Project Caesar Cipher 

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#5521]
This is the project details for the proposed "Caesar Cipher" project in our new Ruby course. If you want to work on this project please leave a comment to let us know.

### Description
This project will be the same as the caesar cipher project that we already have in the ruby course.

### Progress
- [x] problem description -  description of what the student will be expected to build for the project
- [x] Tips/helpful external resources - list of tips or external resources the student may find useful.

### Template for this project
[Can be found here](https://github.com/TheOdinProject/curriculum/blob/master/ruby/basic_projects/project_sub_strings.md)

**Comment by KevinMulhern** [comment]
We should look into creating a standard format for these types of projects

**Comment by CouchofTomato** [comment]
Sounds like a design pattern to me ;-)

On 2 Jan 2017 11:22, "Kevin Mulhern" <notifications@github.com> wrote:

We should look into creating a standard format for these types of projects

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TheOdinProject/curriculum/issues/5521#issuecomment-269960258>,
or mute the thread
