### ISSUE TITLE
installation of git not mentioned as a pre-requisite of doing the git project

### ISSUE THREAD

**Issue by tansaku** [TheOdinProject/curriculum#7684]
installation of git not mentioned as a pre-requisite of doing the git project
https://www.theodinproject.com/courses/web-development-101/lessons/practicing-git-basics?ref=lnav

I know it's part of the overall rails bridge install, but I wonder if we might add a sentence at the start of the project - something like 

> given that you have git installed (as we did in the installation fest) ...

**Comment by KevinMulhern** [comment]
Hey @tansaku, well spotted. We could add an extra assignment to [this lesson]( https://www.theodinproject.com/courses/web-development-101/lessons/introduction-to-git) for installing git if the student hasn't already.

That lesson will always come before the project so it seems like the right place to do it.

**Comment by mrmowji** [comment]
I couldn't find anything about Git in [Web Development 101: Prerequisites](https://www.theodinproject.com/courses/web-development-101/lessons/prerequisites) which is referenced in [assignments of Introduction to Git](https://www.theodinproject.com/courses/web-development-101/lessons/introduction-to-git?ref=lnav#assignment). I know this issue is closed but the problem is not solved to me :)
