### ISSUE TITLE
Two "Developer Tool" lessons

### ISSUE THREAD

**Issue by mindovermiles262** [TheOdinProject/curriculum#8323]
SEE: https://github.com/TheOdinProject/javascript_curriculum/pull/883

In the WD101 course The section "JavaScript Basics" has the lesson "3. Developer Tools." Then a few lessons down from there (in the "Javascript Basics" section) there is a lesson "Developer Tools 2" which is pretty much saying the same thing as the first lesson.

We should combine these two lessons into one.

**Comment by AREEBAISHTIAQ** [comment]
Yeah, these two lessons are much similar and they should be in one lesson.

**Comment by KevinMulhern** [comment]
If I'm remembering right we needed to have two dev tools lessons. One that just working with html and css because it was confusing to introduce the JS specific parts of dev tools before students had done any JS.

The intention of the second Dev tools lesson was to cover the rest of the essential parts of dev tools after the student had learnt a little JS.

Looking at the lessons, I don't think we should combine them into one but there is quite a bit of overlap that we should address.

**Comment by codyloyd** [comment]
Kevin is right.. the first devtools lesson is introduced before the student knows any JavaScript, so the second one should be more JS specific.

I also agree that any extreme overlap should be cleaned up.

**Comment by codyloyd** [comment]
FIXED
