### ISSUE TITLE
Ruby Monk resources insecure error, then 502

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#8460]
https://www.theodinproject.com/courses/web-development-101/lessons/ruby-basics?ref=lnav

This lesson links to Ruby Monk which seems to be down, I have had a report of this before a while back and it is still down. Here is the page it links to: https://rubymonk.com/learning/books/1-ruby-primer

Possible solution: Find another resource to replace it?

**Comment by dvik1950** [comment]
"RubyMonk site is down because of certificate issues.

But you can access its archived contents at [RubyMonk - Interactive ruby tutorials to learn Ruby](https://web.archive.org/web/20170704044407/https://rubymonk.com/learning/books)"

That's a Quora comment.

This could fix the broken link : 

https://web.archive.org/web/20170712025715/http://rubymonk.com:80/learning/books/1-ruby-primer

**Comment by I3uckwheat** [comment]
@dvik1950 Thanks for finding that, would you like to implement this?

**Comment by dvik1950** [comment]
@I3uckwheat  Thank you, I did! https://github.com/TheOdinProject/curriculum/pull/8466

**Comment by mindovermiles262** [comment]
See https://github.com/TheOdinProject/curriculum/pull/8466

**Comment by Everdrought** [comment]
Ruby monk website is no longer broken. It looks like it has restored its full functionality.

**Comment by leosoaivan** [comment]
Closing, since RubyMonk is back up.
