### ISSUE TITLE
Project: Ruby out of date

### ISSUE THREAD

**Issue by kendraforrest** [TheOdinProject/curriculum#860]
The Test-First Ruby is not updated to RSpec 3.xx so it no longer works. If we should continue using the outdated project, please add instructions for how to downgrade to RSpec 2.xx.

**Comment by hgducharme** [comment]
Thank you for this, we will try to find a fix as soon as possible

**Comment by onebree** [comment]
@kendraforrest If you still want to downgrade to RSpec 2.x, for a general project at least... Go into your Gemfile, and enter the following:
```ruby
gem 'rspec-rails', '~> 2.14'
```
Then run `bundle install`, and the "new" gem version will override your current one.

**Comment by nhquiroz** [comment]
Maybe you need to remove all the rspec-related gems and reinstall a previous version, I had the same issue and solved it this way

https://stackoverflow.com/questions/24212198/rake-testfirst-error-rspec-config-failed-learn-ruby/29401451#29401451

**Comment by nhquiroz** [comment]
I added a warning message in the Test-First Ruby project, I think there is nothing more we can do except contact the developers but this is a recurrent issue (check on StarOverflow or other forums) that comes frm long time ago, it seems it won't be fixed.

**Comment by onebree** [comment]
I think for TheOdinProject to thrive, it needs to update to at least RSpec 3 and Rails 4.

**Comment by lhjordanlh** [comment]
Hi, after uninstalling and reinstalling, I still can't quite get the rspec to work. I also tried mess around with the Gemfiles, but either way I always get something like this:

jordanyk@jordanyk-Lenovo:~/00_hello$ rspec hello_rspec.rb
/home/jordanyk/.rvm/gems/ruby-2.2.1/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load': cannot load such file -- /home/jordanyk/00_hello/hello_rspec.rb (LoadError)
	from /home/jordanyk/.rvm/gems/ruby-2.2.1/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `block in load_spec_files'
	from /home/jordanyk/.rvm/gems/ruby-2.2.1/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `each'
	from /home/jordanyk/.rvm/gems/ruby-2.2.1/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load_spec_files'
	from /home/jordanyk/.rvm/gems/ruby-2.2.1/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:22:in `run'
	from /home/jordanyk/.rvm/gems/ruby-2.2.1/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80:in `run'
	from /home/jordanyk/.rvm/gems/ruby-2.2.1/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:17:in `block in autorun'

Could someone helps? Any help would be very appreciated! Thanks!

**Comment by onebree** [comment]
@hgducharme any update on this issue? With Rails **FIVE** being released later this year, I think the move to RSpec 3 and Rails 4 (along with Ruby 2.2) has to be done _now more than ever_.

**Comment by KevinMulhern** [comment]
@onebree, the Test first project is external from the odin project as many of the resources we use in the curriculum are. It seems that the test first project has unfortunately been abandoned by its creators, so a update is unlikely. We need to find a good alternative project to replace it.

**Comment by hgducharme** [comment]
Hmmmm. I'm on my mobile right now, but I can shock it out here soon and see
if I might be able to offer some help. Yeah it definitely might be an issue
of compatibility.

**Comment by novneetnov** [comment]
Without using "rake" as suggested in the tutorial, we can go about doing the exercise with rspec 3.3.2 as mentioned in the codeschool tutorial.

1. Just go into the folder 00_hello and do rspec --init. 
2. Copy the hello_spec.rb to spec/lib/ folder.
3. Then create the file /lib/hello.rb

This will help till an alternate project is found. And we don't have to install rspec version 2.

**Comment by nhquiroz** [comment]
I have a question for those who complete this project and are more advanced in the Ruby section: does The Test-First Ruby section add any value, in the context of the curriculum? If it brings more trouble (and waste of time) than benefits and there's no proper alternative, it could simply be removed. 

I think the TDD approach for learning is greatly cover with the Neo Ruby Koans (which now are added as an additional resource). Maybe, removing the Test-First and adding the Koans later (because it's a little more advanced) in the assignment can be a good replacement. 

I won't complete the Test-First knowing this issues, I've done some of it's exercises before starting with TOP and I prefer the Koans and maybe lots of students gets stuck and frustrated with this.

**Comment by Lenocam** [comment]
Seeing everyone's comments here and experiencing the same difficulties, I suppose I will just move on to whatever is next in the Odin Project curriculum. Is this recommended, or will have have difficulties, because I have not learned what I should have learned in this part of the curriculum? Any recommendations as I move forward?

**Comment by KevinMulhern** [comment]
@Lenocam, you wont have any difficulties with anything by skipping that project.

@nhquiroz 
It probably would be better right now to remove it, due to all the frustrations people have been having. The purpose of the project is to give students a light introduction to ruby the same way that the etch-a-sketch project is meant to be a light introduction the js. Web dev 101 is there just to give students a small taste of everything, with the other courses being the real meat of the curriculum. So finding a good alternative would be the most ideal solution.

**Comment by eriktrautman** [comment]
The real benefit of TFR is that is provides a firm feedback mechanism while still challenging students to actually code on their own.  I wouldn't replace it with anything that uses an embedded REPL precisely because of that.  If there is an alternative problem set that uses the same principles and is equally challenging but actually maintained, I'm open to it.

**Comment by nhquiroz** [comment]
It has no benefits if it doesn't work.

**Comment by Lenocam** [comment]
I agree. If it isn't unusable in it's current state, you would likely have to waist a lot of time trying to make it work, you might as well move on or find something else. I have an RSpec book that is a year old, so I plan to try to use that, but is there something free and online that would help me pick up the same skills I would of had TFR been up to date?

**Comment by nhquiroz** [comment]
@Lenocam I did some TFR exercises and the [Neo Ruby Koans](http://rubykoans.com/) surpasses it, IMHO. 
It's a little more advanced so I wouldn't say it's an "alternative", but after you grasp the basics with the other tutorials listed, is entirely feasible, and you'll learn more about TDD.

The Koans + [Ruby Monk](https://rubymonk.com/) is a great combo.

**Comment by Lenocam** [comment]
@nhquiroz Thanks for the info. I'll check them out.

**Comment by myleschatman** [comment]
@onebree Thank you so much for the tip!

**Comment by Pezz18** [comment]
been faffing for ages! installed rspec 2.14 but still no joy, i get a "you must use ansicon 1.31 or later " 

considering skipping this part now...

**Comment by hamstersky** [comment]
@novneetnov's method works perfectly

**Comment by ad-johnson** [comment]
This isn't a question related to running: looking at the specs, e.g. hello_spec.rb, nowhere is an instance created, e.g. 'hello = Hello.new   hello.hello.should.....  Instead, it seems to imply an instance exists already (or is created on the fly by RSpec), i.e. hello.should.....  I'm a little confused why these don't throw NoMethodError exceptions.  In fact, when I run rake (or even inside my IDE) that's exactly what happens.  Was this pre-v3 behaviour (behind the scenes instance creation)?

**Comment by KevinMulhern** [comment]
This has now been fixed https://github.com/TheOdinProject/curriculum/commit/35cf84d54986f8a7fe1322d4ed19b3f8bf4c9d0a

**Comment by ad-johnson** [comment]
On the one hand great.  On the hand, darn it!  I was two test exercises away from having re-written the whole lot into RSpec 3 and was going to submit it as an alternative and pick up on-going maintenance.

**Comment by KevinMulhern** [comment]
@ad-johnson hey man thank so much for doing that :) sorry for your wasted efforts though :( we need to get the contribution system sorted so people like you can say they are working on features and bug fixes. That will hopefully allow us to avoid situations like this.

**Comment by ad-johnson** [comment]
No problem.  It's not wasted effort, all good learning - really got the hang of context, let, subject, before, is_expected.to

**Comment by KevinMulhern** [comment]
Awesome dude :)

**Comment by iamjackslayer** [comment]
It's 2017 and here I am stuck with this rspec problem. I feel guilty skipping this project tho.
This is what I got after $rake

(in C:/the_odin_project/learn_ruby)
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00000002fce6d8>
C:/the_odin_project/learn_ruby/Rakefile:8:in `new'
C:/the_odin_project/learn_ruby/Rakefile:8:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by KevinMulhern** [comment]
Hey @kendraforrest that isn't the same problem as the original problem in this issue 😉 

I pushed up a fix to the learn_ruby earlier in the week for that. When did you clone the learn_ruby repo?
